### ISSUE TITLE
How to pass a JSON data set as a column data in a YAML file

### ISSUE THREAD

**Issue by savita-malaghan** [database-rider/database-rider#102]
how can i have a key in YAML format which accepts a json data ? I tried to put the json in string format.
But it is giving error like 
org.dbunit.dataset.NoSuchColumnException: table_name.column_name -  (Non-uppercase input column: column_name)  in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.
Ex :  params: '{"comments":"Help this person","test":"false","type":"fire"}' and 
params:[ '{"comments":"Help this person","test":"false","type":"fire"}'] 
Still i am not getting solution for. But with json object data it is working file.

**Comment by rmpestano** [comment]
Hi,

try escaping doulble quotes with `\`, e.g: 

```
params: '{\"comments\":\"...
```

**Comment by savita-malaghan** [comment]
> Hi,
> 
> try escaping double quotes with `\`, e.g:
> 
> ```
> params: "{\"comments\":\"...\"type\":\"fire\"}"
> ```
Hi Pestano,
Still i am getting same error.
org.dbunit.dataset.NoSuchColumnException: custom_actions.PARAMS -  (Non-uppercase input column: params) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.

**Comment by renannprado** [comment]
I have exactly same problem. 

Any idea on how to solve it?

**Comment by renannprado** [comment]
After doing some research and debugging I found out that this was a problem actually of `dbunit` and not within `database-rider`.

The reason why this error happens (even though the exception is a weird one) is because `dbunit` is not capable of understanding the type of the field.

In my case, I'm having a field that is of type `jsonb` in postgresql and even though the below fix works for this case, I'm pretty there must be some caveats. That being said, use you can use the below fix, but it's definitely not a 100% solution. If you (reader) have the time, please send a pull request to `dbunit` to get this fixed.

**CustomPostgresqlDataTypeFactory.java**
```java
package org.dbunit.ext.postgresql;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import org.dbunit.dataset.datatype.AbstractDataType;
import org.dbunit.dataset.datatype.DataType;
import org.dbunit.dataset.datatype.DataTypeException;
import org.dbunit.dataset.datatype.TypeCastException;
import org.postgresql.util.PGobject;

/**
 * TODO: send a pull request to the dbunit project. There was attempted before, but it seems that the
 * TODO: code was not good enough to tbe accepted by them
 * references:
 *  https://sourceforge.net/p/dbunit/feature-requests/188/
 *  https://stackoverflow.com/a/55839637
 */
public class CustomPostgresqlDataTypeFactory extends PostgresqlDataTypeFactory {
  @Override
  public DataType createDataType(int sqlType, String sqlTypeName) throws DataTypeException {
    if (sqlTypeName.equals("jsonb")) {
      return new JsonbDataType();
    } else {
      return super.createDataType(sqlType, sqlTypeName);
    }
  }

  public static class JsonbDataType extends AbstractDataType {

    public JsonbDataType() {
      super("jsonb", Types.OTHER, String.class, false);
    }

    @Override
    public Object typeCast(Object obj) throws TypeCastException {
      return obj.toString();
    }

    @Override
    public Object getSqlValue(int column, ResultSet resultSet) throws SQLException, TypeCastException {
      return resultSet.getString(column);
    }

    @Override
    public void setSqlValue(Object value,
      int column,
      PreparedStatement statement) throws SQLException, TypeCastException {
      final PGobject jsonObj = new PGobject();
      jsonObj.setType("json");
      jsonObj.setValue(value == null ? null : value.toString());

      statement.setObject(column, jsonObj);
    }
  }
}
```
