### ISSUE TITLE
Error with self referenced table while using DbUnit annotation on derived test class

### ISSUE THREAD

**Issue by getarrenspieler** [database-rider/database-rider#103]
If class-level dataset applied and merging setting is set with `@DBUnit` annotation and there is table with foreign key on self (parent-child hierarchy), error `org.dbunit.database.CyclicTablesDependencyException` occurs. It is occurs even merging is `false`: class annotated with `@DBUnit(mergeDataSets = false)`

If same dataset applied to test method, it's ok (when DBUnit annotation is absent on class level).

My test case is derived from base test case:

```java
@RunWith(SpringRunner.class)
@Ignore
@Transactional
@ContextConfiguration({...})
@DBRider
@DBUnit(allowEmptyFields = true,
        caseSensitiveTableNames = true,
        qualifiedTableNames = true,
        dataTypeFactoryClass = PostgresqlDataTypeFactory.class,
        escapePattern = "\"")
public class AbstractDbUnitTest {
}
```
While `mergeDataSets = true` applied to base class - it ok. If `@DbUnit` annotation appears on derived class - exception even `mergeDataSets` attribute not used at all.

Same while attempting set `@DBUnit(mergeDataSets = false)` on a method to disable merging.

Stacktrace:

> Caused by: org.dbunit.database.CyclicTablesDependencyException: Table: crclm.CurriculumContentPart ([CurriculumContentPart])
	at org.dbunit.database.DatabaseSequenceFilter$DependencyInfo.checkCycles(DatabaseSequenceFilter.java:302)
	at org.dbunit.database.DatabaseSequenceFilter.sortTableNames(DatabaseSequenceFilter.java:112)
	at org.dbunit.database.DatabaseSequenceFilter.<init>(DatabaseSequenceFilter.java:67)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.performSequenceFiltering(DataSetExecutorImpl.java:254)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:142)
	... 23 common frames omitted

**Comment by rmpestano** [comment]
Sorry I didn't understood the issue, can you reproduce on [rider-spring tests](https://github.com/database-rider/database-rider/tree/master/rider-spring/src/test/java/com/github/database/rider/spring)?
