### ISSUE TITLE
Feature Request: Dynamic Connection Config based on system properties or environment variables

### ISSUE THREAD

**Issue by markus-meisterernst** [database-rider/database-rider#105]
Hi,

thank you so much for this great project, that helped us a lot, streamlining the DB Integration-Test Process.

Unfortunately I had to extend the com.github.database.rider.core.util.EntityManagerProvider a bit to make passing alternative Connection Properties based on Runtime Arguments actually work.

Maybe I'm too blind to see or there is no other way ?

@DBUnit and persistence.xml are not flexible enough for my setup:

I want to supply the following Properties dynamically to the underlying EntityManagerFactory, so that within the CI Build I can connect to the customer's Database, whereas on my local DevBox I just connect to my MSSQL Docker Image.
Which one to run the DB Tests against is defined by Maven Profiles that define the below Properties according to the intended Runtime Environment.

Considered Dynamic Config Props:

"javax.persistence.jdbc.driver"
"javax.persistence.jdbc.url"
"javax.persistence.jdbc.user"
"javax.persistence.jdbc.password"

Below are the Changes to EntityManagerFactory to make passing the Dynamic Config work:

```
// add an additional Map argument to pass on the above Properties
 public static synchronized EWEntityManagerProvider instance(String unitName, Map config) {
        instance = providers.get(unitName);
        if (instance == null) {
            instance = new EWEntityManagerProvider();
            providers.put(unitName,instance);
        }
        
        try {
            instance.init(unitName, config);
        } catch (Exception e) {
            log.error("Could not initialize persistence unit " + unitName, e);
        }
        
        return instance;
    }

...

// delegate to new init impementation
private void init(String unitName) {
       init(unitName, null);
}

// amplify the init implementation to pass on the 'config' down the line ... to the Persistence.createEntityManagerFactory(..)-Call
private void init(String unitName, Map config) {
        if (emf == null) {
            log.debug("creating emf for unit "+unitName);
            emf = config != null ? Persistence.createEntityManagerFactory(unitName, config) : Persistence.createEntityManagerFactory(unitName);
           ... // unchanged 
       }
    }
```

It would be a great thing to further amplify Database Riders out-of-the-box Capabilities.

That's why I filed this feature request.

Thanks a lot for your time and dedication.

Cheers,

Markus

**Comment by rmpestano** [comment]
Hi @markus-meisterernst, that's interesting I'm just wondering the best way to implement.

I think we could use a convention instead of ading a new map parameter.

For example, the entity manager provider could first look for env and system properties and if they are present then create the entity manager factory based on them. 

```
 private void init(String unitName) {
        if (emf == null) {
            log.debug("creating emf for unit "+unitName);
            Map<String,Object> dbConfig = getDbPropertyConfig(); 
            if(dbConfig != null) {
                emf =   Persistence.createEntityManagerFactory(unitName, dbConfig) :
            } else {
              emf = Persistence.createEntityManagerFactory(unitName)
             }
         
       }
    }
```
`getDbPropertyConfig` would create the config based on system properties or environment variables. If the system property or env variables exists otherwise would return null.

**Comment by markus-meisterernst** [comment]
Hi @rmpestano, 

yes, that would go into the right direction, however, passing the Map is still more flexible, as it allows for configuration in cases where you don't want to use the Runtime Arguments for whatever reasons.

For example when you have a Couple of Test Cases, where each has to be configured differently somehow. Then defining a Profile in the Maven Build (in my example) would not suffice ...

The Best Way would be a mixture of both :-)

That is to grep the (System.Env +) Runtime Arguments and transfer them into a Map (the Part you suggested). 
Then to apply an optional passed in Map to allow to override the Env/Runtime Arguments.

More power is not needed - never ever :-)) 

But then, hey, I would be just happy with the Solution you proposed.

Cheers,

Markus

**Comment by rmpestano** [comment]
Hi, I still don't see a use case for the "mixed approach", would you like to run certain tests with a different setup using the same PU? isn't the case for using multiple PUs or I get it wrong?

**Comment by rmpestano** [comment]
Also, for your case I think you could also fix that using build time properties replacements, example:

src/test/resources/META-INF/persistence.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">

    <persistence-unit name="rules-it" transaction-type="RESOURCE_LOCAL">

    <class>com.github.database.rider.core.model.User</class>
    <class>com.github.database.rider.core.model.Tweet</class>
    <class>com.github.database.rider.core.model.Follower</class>

        <properties>
            <property name="javax.persistence.jdbc.url" value="${db.url}"/>
            <property name="javax.persistence.jdbc.driver" value="${db.driver}"/>
            <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
            <property name="javax.persistence.jdbc.user" value="${db.user}"/>
            <property name="javax.persistence.jdbc.password" value="${db.pass}"/>
           <!-- <property name="eclipselink.logging.level.sql" value="FINE"/>-->
            <property name="eclipselink.logging.parameters" value="false"/>
        </properties>

    </persistence-unit>
</persistence>
```

and at build time you pass those properties by using `-D`:

`mvn test -D db.user=sa -D db.pass=sa -Ddb.url="jdbc:hsqldb:mem:test;DB_CLOSE_DELAY=-1" -D db.driver=org.hsqldb.jdbcDriver

Or the section `<properties>` on a maven profile.

Also to activate properties replacement on src/test/resources folder you'll need to configure your pom like below:

```
 <build>
         
        <testResources>
            <testResource>
                <filtering>true</filtering>
                <directory>src/test/resources</directory>
            </testResource>
           
        </testResources>
```

**Comment by markus-meisterernst** [comment]
Hi @rmpestano, 

I was thinking about it and I got an use case, where even further flexibility is needed. 

Our customer has purchased a MS SQLServer Cluster 2016 recently as part of the Company's consolidation strategy.
There is a Master Instance in the Cluster, which can be used for Writing Database Records.
And there are of course Slave instances, that exclusively serve Reading purposes.

As such, the JDBC URL differs in that the DB Client has to supply the Intend of its operations (Readonly, Read-Write or Write).
Every DB Request is sent to the Master's DB Listener, which then Dispatches those requests according 
to its intend.

So the client ends up with 2 to 3 Persistence Configurations that differ in the URL and possibly the DB User to Access the Database.

Ok, I have to admit that this is rather exotic, and again Runtime/Env variable support would probably suffice 98% of all use cases. 

The Property Replacement as part of the Maven Build through the Resource Plugin though, is not an option (for me) as that is done during Build Time, whereas flexibility is needed (for me) during Runtime when the Tests are actually executed (when Runtime Environments differ).

Hope that makes things clearer, to help you to sort it out :-)

Cheers, Markus

**Comment by markus-meisterernst** [comment]
Feel free to close the issue if you decide not to implement Map support.

Thanks for the discussion anyway :-)

**Comment by rmpestano** [comment]
> Feel free to close the issue if you decide not to implement Map support.

I think it will not hurt, I'll let it open if anyone want to contribute. 

Just summarizing this feature:

1 - On the [init method](https://github.com/database-rider/database-rider/blob/0cb3e34d3131470845660e5e46cb5e7852c54ae5/rider-core/src/main/java/com/github/database/rider/core/util/EntityManagerProvider.java#L77) of em provider look for environment variables and system properties named:
```
"javax.persistence.jdbc.driver"
"javax.persistence.jdbc.url"
"javax.persistence.jdbc.user"
"javax.persistence.jdbc.password"
```
if they are present, then create the emf based on their values as [proposed here](https://github.com/database-rider/database-rider/issues/105#issuecomment-440337697).

2 - Overload `instance` method of emProvider to receive a map of configuration as [proposed here](https://github.com/database-rider/database-rider/issues/105#issue-382718866)

3 - Create integration tests, like [this one](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/EntityManagerCacheTestIt.java) for example, to verify the new feature

**Comment by markus-meisterernst** [comment]
would it be feasible if the `getDbPropertyConfig `-Method would be protected to be able to override the default through subclassing if there is a need (e.g. if there is a hibernate or eclipse link specific value that is to be provided to the EMF) ?

**Comment by rmpestano** [comment]
> another possibility would be inside of getDbPropertyConfig to grep everything from javax.persistence., hibernate., eclipselink.* from the Env and Runtime Arguments and put it in a Map. If the Map is not empty it will be returned, so that the EMF takes notice or else return null 

That's ok however I would only look for mandatory properties (url, user, driver and password) to decide if we'll use the env/runtime properties. Then If mandatory properties are present then populate other properties like javax.persistence.*.

**Comment by rmpestano** [comment]
Again, thank you very much for this contribution @markus-meisterernst!
