### ISSUE TITLE
Transactional dataset comit before test execution

### ISSUE THREAD

**Issue by KaRkY** [database-rider/database-rider#110]
I would like to have a transactional test to be commited before my test code executes. Because my code manages own transactions and has own connection data is not seen inside test.

**Comment by rmpestano** [comment]
Hi, can you provide an example project showing the issue?

**Comment by rmpestano** [comment]
If you use Spring you can put @Transactional on your repositories, it should work.

**Comment by KaRkY** [comment]
The problem is that @Transactional is for my inserts but I am not doing any inserts. I am using it for select testing and I want the dataset to be commited into DB before my code runs.
Example how my test code runs:
```
  @Test
  @DataSet(
    value = "database.yml",
    useSequenceFiltering = true,
    cleanAfter = true,
    transactional = true)
  void returnSliceOf()
  {
    final List<ListVet> list = repository
      .list(Optional.empty(), Optional.of(Slice.of(1, 2)), Optional.empty());

    assertThat(list)
      .hasSize(2)
      .extracting(ListVet::id)
      .containsExactly(Id.of(2L), Id.of(3L));
  }
```

**Comment by rmpestano** [comment]
You don't need to commit a dataset, the dataset will be inserted into DB before the test runs regardless of `transactional=true`. This is the default behavior.

Transaction is just to avoid begin/commit transaction inside your tests but is not related to the declared dataset.

**Comment by KaRkY** [comment]
No when DataSource is set to autoComit=false it does not get comited to DB.

**Comment by rmpestano** [comment]
hmm that's interesting! 

can you provide a sample project? or a testcase on this repo which reproduces this issue?

**Comment by KaRkY** [comment]
Ok will to modify existing spring example to reproduce this exact problem as my project is too big to try to. Will try to do it over the weekend.
