### ISSUE TITLE
Ignore row count when comparing datasets

### ISSUE THREAD

**Issue by iceberk** [database-rider/database-rider#114]
In tests I would like to verify only small subset of existing rows in the table. Let's say I have 'users' table and I need to insert common users rows for most of the tests:
```
common.yml

users:
  - id: 1
    name: User1
  - id: 2
    name: User2
```
Then in some test I want to check update of the user name. For example the test will update name of user with id = 2 from 'User2' to 'Another user 2'. So I would like to have the following in expected dataset:
```
expected.yml

users:
  - id: 2
    name: Another user 2
```
In current implementation the test will fail because row count is obviously different - 1 row expected and 2 rows in actual dataset.
I was able to implement a workaround using PrimaryKeyFilteredTableWrapper in DataSetAssertion class:
```
public class DataSetAssertion {
    private static final DataSetAssert INSTANCE = new DataSetAssert();

    private static ITable filterActualDataset(ITable expectedDataSet, ITable actualDataSet) throws DataSetException {
        String pkName = actualDataSet.getTableMetaData().getPrimaryKeys()[0].getColumnName();
        Set<Object> pkList = new HashSet<>();
        for (int i = 0; i < expectedDataSet.getRowCount(); i++) {
            pkList.add(expectedDataSet.getValue(i, pkName));
        }

        return new PrimaryKeyFilteredTableWrapper(actualDataSet, pkList);


    }

    public static void assertEqualsIgnoreCols(ITable expectedDataSet,
                                              ITable actualDataSet, String[] ignoreCols)
            throws DatabaseUnitException {
        INSTANCE.assertEqualsIgnoreCols(expectedDataSet, filterActualDataset(expectedDataSet, actualDataSet), ignoreCols);
    }
}
```
Can we add some flag/enum to com.github.database.rider.core.api.dataset.ExpectedDataSet annotation to change default checking logic?

**Comment by rmpestano** [comment]
Hi, have you tried `ignoreCols` attribute in `@ExpectedDataset`?

**Comment by rmpestano** [comment]
Hmm I think I understand the issue here, why expected dataset is not something like:

```
users:
  - id: 1
    name: User1
  - id: 2
    name: Another user 2
```

**Comment by iceberk** [comment]
Because there can be a lot of records inserted initially with `@DataSet`. Currently I have to copy/paste all table records from initial data set in expected data set and I'd like to avoid this.
For most of the tests I would like to have in `@ExpectedDataSet` only those records which are relevant for current test, e.g. records that were created/updated by the test.

**Comment by rmpestano** [comment]
If i got It right we may need a "contains" dataset comparison in `DataSetAssertion`

This is what `PrimaryKeyFilteredTableWrapper` is doing?

If so we just need to enable this feature in `@ExpectedDataSet` something like:

```
@ExpectedDataSet(value = "expected.yml", compareOperation=CONTAINS) //by default the operation will be EQUALS
```

WDYT?

Can you provide a PR?

**Comment by iceberk** [comment]
Yes, that's exactly what I'd like to see :smiley: 
Created pull PR #115

**Comment by rmpestano** [comment]
Thank you very much @iceberk, I'll review ASAP!
