### ISSUE TITLE
Question Regarding Usage With Cucumber and Spring Boot

### ISSUE THREAD

**Issue by willweyant** [database-rider/database-rider#119]
I am currently running into an issue when trying to use Database Rider in a project with Cucumber and Spring. I am not sure how to set it up correctly to populate the data sets from the Cucumber step definition file. Cucumber is kicked off from a runner class. The Cucumber step definition class uses Selenium to drive the browser.

If I follow the Cucumber example, it seems to require the CdiCucumberTestRunner class and this conflicts with Spring. I am sure I must be missing something.

 Any help is greatly appreciated.

**Comment by rmpestano** [comment]
Hi @willweyant,

sorry for the delayed response, the only approach I know to use dbrider with Cucumber and SpringBoot and the programmatic creation of datasets: https://github.com/database-rider/database-rider#programmatic-creating-datasets

I hope it helps.
