### ISSUE TITLE
Unable to connect to in-memory HSQLDB with empty username

### ISSUE THREAD

**Issue by rpajanssen** [database-rider/database-rider#131]
We run the unit tests against an in-memory HSQLDB. It has no users. We can connect without specifying a user. 

We annotate our test class with:
@DBUnit(url = "jdbc:hsqldb:mem:testdb", driver = "org.hsqldb.jdbcDriver", leakHunter = true)

We annotate our tests with:
@DBRider
@DataSet(value = "our_data_set.xml", strategy = SeedStrategy.CLEAN_INSERT)

But we get an exception:
java.sql.SQLInvalidAuthorizationSpecException: invalid authorization specification - not found: SA

	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.getConnectionFromConfig(DataSetExecutorImpl.java:473)

The code explicitly throws this exception if the user is empty! I feel we should have the option of an empty user name.

I tried to override some implementations but the code is not open for configuration change. I cannot specify my own DataSetExecutor, the DataSetExecutorImpl implementation class is used everywhere, no factory is used for instantiation.

**Comment by rmpestano** [comment]
Hi, can you try with `1.5.4-SNAPSHOT`? 

[See here](https://github.com/database-rider/database-rider#snapshots) to enable snapshots.

**Comment by rpajanssen** [comment]
Hi, tried it. It now seems to be stuck in some infinite loop. Haven't been able to pinpoint where exactly yet.

A test example can be found in https://github.com/rpajanssen/test-examples 
Failing test : JdbcPersonFinderWithInMemDBUsingDBUnitAnnotationTest

**Comment by rmpestano** [comment]
can't access the repo https://github.com/rpajanssen/test-examples (not found)

**Comment by rpajanssen** [comment]
ooops... sorry... was still private... made it public

**Comment by rmpestano** [comment]
Hi @rpajanssen,

your code is working for me without any modifications (just commented the `@Disabled` on JdbcPersonFinderWithInMemDBUsingDBUnitAnnotationTest.

![Screenshot from 2019-05-02 20-28-14](https://user-images.githubusercontent.com/1592273/57113067-2ee6d300-6d19-11e9-88a4-c0be6093264b.png)
![Screenshot from 2019-05-02 20-28-41](https://user-images.githubusercontent.com/1592273/57113072-33ab8700-6d19-11e9-8fe1-cfb6c88be5d0.png)

**Comment by rpajanssen** [comment]
Hi,

Tried it again on my laptop after a reboot... and it passes now as well. Must have been a weird hickup in IntellijIDEA on my side (ran as unit test and in IDEA terminal as mvn clean test command, but both processes hung. 

Sorry to have wasted your time.

On the up side... I no am able to run the test without specifying a user name! Thanks for that change!

**Comment by rmpestano** [comment]
great, thanks for reporting it.
