### ISSUE TITLE
escapePattern ignored by cleanBefore and cleanAfter

### ISSUE THREAD

**Issue by rkraneis** [database-rider/database-rider#144]
What the title says ;-)
```
Running CreateInitialOrdersTest
2019-06-14 14:49:28 WARN  DataSetExecutorImpl:621 - Could not clear table customers.order, message:Syntax error in SQL statement "DELETE FROM CUSTOMERS.ORDER[*] WHERE 1=1 "; expected "identifier"; SQL statement:
DELETE FROM customers.order where 1=1 [42001-197], cause: null
```
- database-rider 1.7.1
- dbunit 2.5.3 (default transitive dependency)
- h2 1.4.197
- junit-jupiter 5.4.2

Tried both ``@DBUnit(escapePattern = "`?`", qualifiedTableNames = true)`` and
```yaml
properties:
  qualifiedTableNames: true
  escapePattern: "`?`"
```

It does work on a dbunit level. Before adding the properties we couldn't even load and compare the test data as the table name ``order`` is a keyword.

**Comment by rmpestano** [comment]
Hi, can you try with 1.7.2-SNAPSHOT?

You'll need to [enable snapahots](https://github.com/database-rider/database-rider/blob/master/README.adoc#snapshots) repo on your pom.xml.

Thanks for the detailed feedback.

**Comment by rkraneis** [comment]
Everything works fine now. Thank you very much for the quick response!

I guess giving useful feedback is the least I could do :-)

**Comment by rmpestano** [comment]
Version `1.7.2` was just released containing this fix, thanks for the feedback.
