### ISSUE TITLE
DB2 driver not correctly detected 

### ISSUE THREAD

**Issue by frederikb** [database-rider/database-rider#146]
Hi,

I'm currently running into issues that Database Rider is not detecting that I'm running against a DB2 database.

The detection is done in `DriverUtils`:

```java
public static boolean isDB2(String driverName) {
    return hasKeywordInDriverName(driverName, "db2");
}
```

whereas the driver name is retrieved via:
```java
return connection.getMetaData().getDriverName().toLowerCase();
```

We're running tests using the following IBM DB2 driver:
```xml
<dependency>
    <groupId>com.ibm.db2.jcc</groupId>
    <artifactId>db2jcc</artifactId>
    <version>db2jcc4</version>
</dependency>
```
which returns a driver name not containing the keyword `db2`:

```
ibm data server driver for jdbc and sqlj
```
I'm not sure if the name differs throughout the different driver (versions) and what would be the common keyword. Perhaps we can switch to looking for `ibm` or just add is as an `OR` clause?

Is anyone else using DB2?  @abellmann ?

**Comment by rmpestano** [comment]
Hi @frederikb, sorry for the late reply

I've added a SPI so you can return the driver name you need, a bit more complex solution but this way we avoid adding `or`s to the DriverUtils` and somehow we're future proof against any other weird driver name.

To use the SPI you must implement com.github.database.rider.core.spi.DriverNameService interface and also create a file under `src/main/resources/META-INF/services` named: `com.github.database.rider.core.spi.DriverNameService`. The contents of the file is the fully qualified name of you DriverNameService implementation, ex: `com.sample.MyDriverNameService`:

```
package com.sample;

public class MyDriverNameService implements DriverNameService {
    String getDriverName(java.sql.Connection connection) {
        return "db2";//just to match desired driver
    }
}
```

can you test with 1.7.3-SNAPSHOT? you'll need to add [snapshots repo](https://github.com/database-rider/database-rider#snapshots)

If it works for you I can release v1.7.3. 

Thanks for your feedback.

**Comment by frederikb** [comment]
Hi @rmpestano . Sorry for not answering sooner. It took a while until I could pick this project up again.

Your solution gracefully solved the issue I was facing. Thank you very much.

**Comment by rmpestano** [comment]
Hi, better late than never 😆

Thank you for the feedback, glad It worked!
