### ISSUE TITLE
Rider Junit5 - integration with Spring test context 

### ISSUE THREAD

**Issue by ericjturley** [database-rider/database-rider#147]
### Background
In a library intended to be used by a Spring Boot application, the datasource is auto-configured by Spring Boot as an H2 in-memory db during tests.

### Objective
1. Using JUnit 5, ideally, I want to annotate JUnit5 tests with the JUnit5 `@DBrider` annotation. 
1. But I also need the spring test context datasource set up correctly and passed to the db-rider library.
1. Finally, I also want to be able to exclude the JUnit4 lib.

#### Use JUnit 5 annotation
If I use this annotation:
`com.github.database.rider.spring.api.DBRider`
it requires having `rider-spring` on the classpath
The test functions, but relies on `TestRule`, via `com.github.database.rider.core.util.EntityManagerProvider`, requiring me to keep JUnit4 as a dependency

#### Use spring annotation
If I use this annotation and exclude JUnit 4:
`com.github.database.rider.junit5.api.DBRider`
I get: `java.lang.RuntimeException: JDBC connection url cannot be empty`

#### Use JUnit 5 annotation with injected datasource
If I use the `junit5` annotation, but include JUnit4, while injecting a `datasource` and declaring a `connectionHolder`, I get yet a different result where retrieve tests work, but create tests fail.

### MCVE project and additional details
There are several permutations of variables described in the Readme of the MCVE project I submitted: https://github.com/ericjturley/mcve-dbrider-junit5-springboot/blob/master/Readme.md

**Comment by rmpestano** [comment]
Hi @ericjturley, thanks for opening the issue!

@gerosa and @njuro can you help? 

I've made it work partially with junit5 `@DBrider` with the following:

```
import com.github.database.rider.junit5.api.DBRider;           
import com.mcve.dbriderjunit5springboot.BpnsEntityConfiguration;
import com.mcve.dbriderjunit5springboot.PlatformName;
import com.mcve.dbriderjunit5springboot.ProviderName;
import com.mcve.dbriderjunit5springboot.entity.Platform;
import org.springframework.transaction.annotation.Transactional;


@DBRider
@DataJpaTest
@SpringJUnitConfig(BpnsEntityConfiguration.class)
@DataSet("platform/platforms.yml")
class PlatformRepositoryTest {

       @Autowired
	private PlatformRepository platformRepository;

        @Autowired
	DataSource dataSource;

	private ConnectionHolder connectionHolder = () -> dataSource.getConnection();//connection to be used by DBUnitExtension see here: https://github.com/database-rider/database-rider/blob/afc25b186f96c9d54c6ec9bf676874f606f371d4/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L34

}
```  

Database is populated by dbrider accordingly but the problem with this approach is that datasource connection used by `DBUnitExtension` is different than the one used by `platformRepository` which makes tests like below fail:

```
        @Test
	@ExpectedDataSet(value = "platform/platforms-expected.yml",
	                 ignoreCols = "id",
	                 orderBy = "name")
	@DataSet(cleanBefore = true) 
	void save() {
		long rows = countApplicationRows();

		Platform platform = new Platform(PlatformName.LOOPBACK, ProviderName.LOOPBACK);
		Platform saved = platformRepository.saveAndFlush(platform);

		assertThat(saved.getId()).isNotNull();
		assertEquals(rows + 1, countApplicationRows());
	}
``` 

It would be nice to have [SpringRiderTestContext](https://github.com/database-rider/database-rider/blob/master/rider-spring/src/main/java/com/github/database/rider/spring/SpringRiderTestContext.java) working with JUnit5 DBUnitExtension.

As `com.github.database.rider.junit5.api.DBRider` annotation (which activates DBUnitExtension) has the same name as rider-spring annotation we may need a new one or make DBUnitExtension compatible with Spring test context somehow.

Any ideas?

**Comment by rmpestano** [comment]
Can you try with `v1.7.6-SNAPSHOT` @ericjturley?

You can see an [example here](https://github.com/database-rider/database-rider/blob/master/rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitTest.java#L19) just make sure that `DBRider` annotation comes from `junit5` package.

**Comment by rmpestano** [comment]
Iḿ just closing the issue, the fix is part of just relased `v1.8.0`

If you find any problems related to this issue, please reopen it.

**Comment by Tetradeus** [comment]
Hello guys,

I just tried com.github.database-rider:rider-junit5:1.8.1

When running with junit5 only, if still fails with the following error :
java.lang.NoClassDefFoundError: org/junit/rules/TestRule
at com.github.database.rider.junit5.DBUnitExtension.beforeTestExecution(DBUnitExtension.java:42)

This is where EntityManagerProvider is used and EntityManagerProvider still implements org.junit.rules.TestRule making it dependent on junit4 classes. I think this issue or a new one must be open to make it fully compatible with junit5 without junit4 in the classpath ?

**Comment by rmpestano** [comment]
Hi @Tetradeus, good catch, just created issue #168, thank you for the heads up
