### ISSUE TITLE
Unable to execute javascript function in yml

### ISSUE THREAD

**Issue by achyutha526** [database-rider/database-rider#148]
I am trying to load data to DB using YAML file and Spring JDBC. In YAML file, i need to format the date, so have stated creating java script function and trying to invoke it.

Field in YAML:

CRT_TMSTMP: "js:import formatDate from './calculateDate.js'; formatDate('2018-12-1');"

Contents of Javascript file:
---------------------------------
function formatDate(dateInput){
  XXXXXXXX
  XXXXXXXX
  return date.toLocaleDateString();
}
export {formatDate};

I am seeing error:
 Unable to typecast value <js:import formatDate from './calculateDate.js'; formatDate('2018-12-1');> of type <java.lang.String> to TIMESTAMP
	at org.dbunit.dataset.datatype.TimestampDataType.typeCast(TimestampDataType.java:120)

**Comment by rmpestano** [comment]
Hi, you can't import a file inside an yaml dataset. 

Qhat you're trying to achieve?

**Comment by achyutha526** [comment]
I am formatting date in specific format and trying to extract the formatting step to a Javascript function so that I can use across different yaml fiels.

**Comment by rmpestano** [comment]
Why the dbunit default format  (yyyy-mm-dd 
hh:mm:ss) is not enough for your case? Ex:

```
CRT_TMSTMP: 2018-12-01

```

**Comment by rmpestano** [comment]
If you still think you need to format the dates on your datasets I think the only way is through [dataset providers](https://github.com/database-rider/database-rider#dataset-providers)

**Comment by rmpestano** [comment]
Also maybe you can do that with [groovy scriptable datasets](https://database-rider.github.io/database-rider/1.7.2/documentation.html#_seed_database_with_groovy_script_in_dataset), something like below (I didn't test):

```
 DATE: "groovy:Date.parse( 'dd-MMM-yyyy', new Date()).format( 'yyyy-mm-dd' )" 
```

**Comment by achyutha526** [comment]
Thank you for the reply. I am going to use dataset providers for this.
