### ISSUE TITLE
Setup/Expect dataset by method besides annotation

### ISSUE THREAD

**Issue by raderio** [database-rider/database-rider#150]
Besides annotation setup/expect
```
    @Test
    @DataSet(provider = UserDataSetProvider.class, cleanBefore = true)
    public void shouldSeedDatabaseProgrammatically() {
        List<User> users = EntityManagerProvider.em().createQuery("select u from User u ").getResultList();
        assertThat(users).
                isNotNull().
                isNotEmpty().hasSize(3).
                extracting("name").
                contains("@dbunit", "@dbrider", "@new row");
    }
```
It will be great to have possibility to setup/expect by a method
```
    @Test
    public void shouldSeedDatabaseProgrammatically() {
        dbSetup(UserDataSetProvider.class)
        List<User> users = EntityManagerProvider.em().createQuery("select u from User u ").getResultList();
        assertThat(users).
                isNotNull().
                isNotEmpty().hasSize(3).
                extracting("name").
                contains("@dbunit", "@dbrider", "@new row");
    }
```
In this case the library can be used in used in other use-cases, not just for testing.
Also, the method can be more easily extended/override than the annotation.
Method is more flexible, we can pass as parameter even a lambda.
And if besides database in the test we need also to ensure that a notification was sent into a queue, we also are doing it by a method, not an annotation, this will be more consistent.

**Comment by raderio** [comment]
Thank you for the solution.
In this case if library already supports it, it will be even better if the library also will extract this boilerplate in the standard methods(`dbSetup` & `dbExpect`), so no need for everyone to have own methods for that.

IMHO, libraries should provide/support different solutions/approaches, and users should be able to choose what fits better for their application.

BTW, for `dbExpect` is there also a solution?

**Comment by raderio** [comment]
>It is important to note that if you have a running transaction on test method (like this for example)

We now have lambda in Java, so I don't see why we need `@Transactional` annotation anymore.
We do not use `@Transactional` annotation.

>I hope you understand that

Yes, but as I said, now we have lambda, and many use cases when we use annotations can be replaced by lambdas, and must be replaced. Lambda is more flexible, more reusable, composable and less magic.
So, this is why I suggest to add also the methods, not just the annotations.

**Comment by raderio** [comment]
>using it would imply to drop jdk7 support

This is why I suggest to add methods besides annotations and not to remove them, yet :)

>Having said that you could easily wrap the sample code I provided and create dbSetup and dbExpect utility methods, right?

Yes, but as I said
>In this case if library already supports it, it will be even better if the library also will extract this boilerplate in the standard methods(dbSetup & dbExpect), so no need for everyone to have own methods for that.

**Comment by raderio** [comment]
>How would you add an utility method using lambda without breaking projects using JDK7?

The example with lambda was just to elaborate that usually a method with lambda as parameter is better than annotation, in case if lambda support is needed.

So, in this case, utility methods can be added without support of lambda, these methods need to receive just `DataSetProvider` objects.
```
public void dbSetup(DataSetProvider dataSetProvider, /* other parameters */) {
    // ...
}

public void dbExpect(DataSetProvider dataSetProvider, /* other parameters */) {
    // ...
}
```
Support for lambda of course can be added as separate module if will be needed.

**Comment by rmpestano** [comment]
Hi @raderio, for something similar to dbSetup we now have [RiderDSL](https://github.com/database-rider/database-rider#riderdsl) which may do what you need. 
We still miss dbExpect, maybe someone could contribute that to RiderDSL so instead of having `.createDataSet()` at the end, we would have `expectDataSet()`

**Comment by rmpestano** [comment]
Hi again @raderio,

I've just added such feature to RiderDSL, you can find some [examples here](https://github.com/database-rider/database-rider/blob/195faca6bf4438ac10727f1a605daf6cfa81ee73/rider-core/src/test/java/com/github/database/rider/core/dsl/RiderDSLIt.java#L292-L375). 

You can try with latest snapshot or wait until `v1.15.0`.

Thank you for the idea.

**Comment by raderio** [comment]
Great! Thank you.
