### ISSUE TITLE
cleanBefore & excluding some tables

### ISSUE THREAD

**Issue by raderio** [database-rider/database-rider#151]
We are using Spring Boot and we are writing API tests using MockMvc, so when Spring context stats liquibase migration is executed, and liquibase has its tables where stores which migrations was executed.

If we are using `@DataSet("users.yml", clearBefore=true)` than all the data from liquibase's tables are also deleted. 

So, is there a way to specify which tables to exclude from clearing?

**Comment by rmpestano** [comment]
Hi, currently cleanBefore will try to clear all tables. One way to clear only the tables you want is to declare them on the dataset, even If empty.

**Comment by raderio** [comment]
Yes, it is a solution, but in this case we need to specify 50 empty table for each test, which is not the best solution, and in each test those empty tables will be different.

Maybe it is possible to add a new property `excludTables` or something similar?

**Comment by rmpestano** [comment]
Hi,

just added `tablesToClean` property in `@DataSet`, it resolves to a list of table names to be cleaned when `cleanBefore()` or `cleanAfter()` is set to true.

See an [example here](https://github.com/database-rider/database-rider/blob/13669685bd72a4c2880538bb42ad663dff0a61d4/rider-core/src/test/java/com/github/database/rider/core/CleanSpecifiedTablesAfterIt.java#L52).

please try with `v1.7.3-SNAPSHOT`. To enable snapshots,[ see here](https://github.com/database-rider/database-rider#snapshots).

I hope it helps.

**Comment by raderio** [comment]
Well, I was expecting more to have to enumerate tables which I do not want to clean.
Because in this case, I only need to specify 2 tables(of liquibase) in every test.

In case we need to specify which table to clean, it will be more harder, because in every test the list is different, and we need to maintain that list for every test every time we add a new table.

**Comment by rmpestano** [comment]
Got it and makes sense, see updated [example here](https://github.com/database-rider/database-rider/blob/9a7fa271e947b191e4f27b44532ef7b2feb16996/rider-core/src/test/java/com/github/database/rider/core/CleanSpecifiedTablesAfterIt.java#L50).

 please try with latest snapshot, it should be available in next 15 minutes.
