### ISSUE TITLE
DataSet provider ignores caseSensitiveTableNames

### ISSUE THREAD

**Issue by raderio** [database-rider/database-rider#152]
In some projects we have table names in lowercase
```
public class UserDataSetProvider implements DataSetProvider {

        @Override
        public IDataSet provide() throws DataSetException {
            DataSetBuilder builder = new DataSetBuilder();
            IDataSet dataSet = builder
                    .defaultValue("id", -1) //default value for all tables that don't provide a value for 'id' column
                    .table("user") //start adding rows to 'user' table
                        .column("ID",1)
                        .column(name,"@realpestano")
                    .row() //keeps adding rows to the current table
                        .column(id,2)
                        .column("NAME","@dbunit")
                    .table("tweet") //starts adding rows to 'tweet' table
                        .defaultValue("LIKES", 99) //default value only for table tweet, the value will be used if column is not specified
                        .column("ID","abcdef12345")
                        .column("CONTENT","dbunit rules!")
                        .column("DATE","[DAY,NOW]")
                    .table("follower").column(id,1)
                        .column("USER_ID",1)
                        .column("FOLLOWER_ID",2)
                    .table("user")// we still can add rows to table already added
                        .column(name,"@new row")
                    .build();
            return dataSet;
        }
    }
```
```
@DBRider
@DBUnit(caseSensitiveTableNames = true)
class UserTest {

    @Test
    @DataSet(provider = UserDataSetProvider.class, cleanBefore = true)
    public void shouldSeedDatabaseProgrammatically() {
        List<User> users = EntityManagerProvider.em().createQuery("select u from User u ").getResultList();
        assertThat(users).
                isNotNull().
                isNotEmpty().hasSize(3).
                extracting("name").
                contains("@dbunit", "@dbrider", "@new row");
    }
}
```
We get the error "org.dbunit.dataset.NoSuchTableException: The table 'USER' does not exist in schema 'null'"
If we use yaml files everything works perfect with lowercase table names.

**Comment by rmpestano** [comment]
Yes, currently it only looks for the [global config](https://github.com/database-rider/database-rider/blob/9a4688f18c6d2a449974d7bdac6f16de2dabc120/rider-core/src/main/java/com/github/database/rider/core/dataset/builder/DataSetBuilder.java#L50)

So If you config caseSensitiveTableNames  in `src/test/resources/dbunit.yml` then It should work.

A sample config can be [found here](https://github.com/database-rider/database-rider/blob/9a4688f18c6d2a449974d7bdac6f16de2dabc120/rider-core/src/test/resources/config/sample-dbunit.yml#L6)

Please keep this issue open so we can add support for annotation level config also.

**Comment by raderio** [comment]
Yes, it works, thank you.
Also waiting for support in annotation.

**Comment by rmpestano** [comment]
> Also waiting for support in annotation.

Could not add the support for annotation but added support for config into dataset builder itself, see an example here:

https://github.com/database-rider/database-rider/blob/13669685bd72a4c2880538bb42ad663dff0a61d4/rider-core/src/test/java/com/github/database/rider/core/DataSetProviderIt.java#L376-L378

You can try it in v1.7.3-SNAPSHOT
