### ISSUE TITLE
DataSetProvider incompatible data types on extected data set

### ISSUE THREAD

**Issue by raderio** [database-rider/database-rider#153]
```
public class UserDataSetProvider implements DataSetProvider {

        @Override
        public IDataSet provide() throws DataSetException {
            DataSetBuilder builder = new DataSetBuilder();
            IDataSet dataSet = builder
                    .table("user") 
                        .columns("id", "name")
                        .values(1,"@realpestano")
                    .build();
            return dataSet;
        }
    }
```
```
@DBRider
@DBUnit(caseSensitiveTableNames = true)
class UserTest {

    @Test
    @DataSet(provider = UserDataSetProvider.class, cleanBefore = true)
    @ExpectedDataSet(provider = UserDataSetProvider::class)
    public void shouldSeedDatabaseProgrammatically() {
        List<User> users = EntityManagerProvider.em().createQuery("select u from User u ").getResultList();
        assertThat(users).
                isNotNull().
                isNotEmpty().hasSize(3).
                extracting("name").
                contains("@dbunit", "@dbrider", "@new row");
    }
}
```
We get an error
```
junit.framework.ComparisonFailure: Incompatible data types: (table=user, col=id) 
Expected :NUMERIC
Actual   :BIGINT
```
PostgreSQL 11 database.

**Comment by rmpestano** [comment]
Hi, can you try using  a `BigInteger` on id column?

```
public class UserDataSetProvider implements DataSetProvider {

        @Override
        public IDataSet provide() throws DataSetException {
            DataSetBuilder builder = new DataSetBuilder();
            IDataSet dataSet = builder
                    .table("user") 
                        .columns("id", "name")
                        .values(BigInteger.valueOf(1);,"@realpestano")
                    .build();
            return dataSet;
        }
    }

```

**Comment by rmpestano** [comment]
FYI, [here is the method](https://github.com/database-rider/database-rider/blob/59364bffab0b5788832fe68b074b9d7e7cd2a94c/rider-core/src/main/java/com/github/database/rider/core/dataset/builder/BuilderUtil.java#L68) which resolves the column types in DataSetProvider

**Comment by raderio** [comment]
Same issue with `BigInteger`.
It works if setup is by DataSetProvider and expected is by yaml file.
But not works when expected is by DataSetProvider.

**Comment by raderio** [comment]
BTW, in the provided method which resolves the column types in DataSetProvider, I can not find the case/id for `BigInteger`.

**Comment by rmpestano** [comment]
> BTW, in the provided method which resolves the column types in DataSetProvider, I can not find the case/if for BigInteger.

It should fall into last case.

Need some time to investigate, unfortunatelly I've been quite busy lately

**Comment by raderio** [comment]
>It should fall into last case.

Last case is `DataType.NUMERIC`, so maybe this is the issue that is expected `NUMERIC` but actual is `BIGINT`?

**Comment by rmpestano** [comment]
Yea, I think we could add a case for BigInteger -> Bigint

Could you contribute a PR with that?

**Comment by raderio** [comment]
Done.

**Comment by raderio** [comment]
I am trying to run tests. Can you please describe and update the docs what should be configured with docker?

**Comment by rmpestano** [comment]
Hi Alex, you just need It to be instaled, what's the error are you getting?

**Comment by raderio** [comment]
It is installed.
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment.

**Comment by rmpestano** [comment]
Maybe it is the docker version, let me check my env which is working now.

**Comment by raderio** [comment]
The issue with docker is related to permissions.
Solution https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/
