### ISSUE TITLE
[Question] Database not cleared automatically between tests

### ISSUE THREAD

**Issue by abelsromero** [database-rider/database-rider#156]
I am struggling with Rider for the fact that database is never cleared and its state is shared across different test classes, creating some major issues. And I am wondering if I am not using it correctly or is an issue. I am following the example of Quarkus.
The main issue I am finding is tests failing because the data set cannot initialized, because some other test inserted data that prevents some table from being fully deleted.

1. For example, let's have 3 tables: A, B & C, where B & C have a FK to A's id.
A's data in initialized with a yml data set using `@DataSet`.
2. In one test on it's own class I insert a registry in C, and don't delete it. Be it an accident or just because the test failed for some other reason and the manual deletion was not executed.
3. Then, any tests that uses A's dataset fails to start with a message like this
```
should_delete_all_B  Time elapsed: 0.074 s  <<< ERROR!
com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: a.yml
Caused by: org.h2.jdbc.JdbcSQLException: 
Referential integrity constraint violation: "FKJYATY0XA5P7DMGQP41FYB0SNE: PUBLIC.C FOREIGN KEY(A_ID) REFERENCES PUBLIC.A(ID) (1011)"; SQL statement:
delete from A [23503-197]

```

You see this forces to go through all tests trying to find where this data is inserted. It could be a failing test, or just a new test that does not clear it's data.

Seeing this comment https://github.com/database-rider/database-rider/issues/68#issuecomment-359396449, I think we agree data should be reseted on every test, however that's not the case.

**Comment by rmpestano** [comment]
Hi @abelsromero,

for your case you need to specify the cleaning ordering using `tableOrdering` ([see here](https://github.com/database-rider/database-rider/blob/09e34bd47b4b66a3841c63adaea5ec382cfa87fd/rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSet.java#L42) ).

Table ordering is used in two moments, the first is on the CLEAN operation when using CLEAN_INSERT (default seeding strategy) and the latter is when you use `cleanBefore = true`.
 

> Seeing this comment #68 (comment), I think we agree data should be reseted on every test, however that's not the case.

That is the case of declared tables in the dataset if you're using `CLEAN_INSERT`.

I hope it helps

**Comment by abelsromero** [comment]
> I hope it helps

Not really, sorry :%


`tableOrdering` is not very viable here because is a monolithic service without a up-front DB design. We may need to change things, and using `tableOrdering` would imply reviewing lots of tests on every database change.
After some thought, we are just adding `cleanAfter = true` to all test that create data. If it fails we add `disableConstraints` too.

My honest feelings are that I find the defaults error prone and frustrating. Specially when data leaks from one test class to another and 50% of total tests fail and you are unable to reproduce individually.
At least if there was a way to set `cleanAfter = true` or a global `tableOrdering` that is executed always, one could more easily garantee the state of the databases for each test.

I can only imagine technical limitations for data not being cleared (e.g. some vendors provide some optimal "drop database"). The more I think about it, the more I ask myself how others deal with it, since I don't feel is such a weird thing, or it is?

**Comment by rmpestano** [comment]
Hmm, maybe you can use merge datasets:

```
@DBUnit(mergeDataSets = true) //this can be enabled globally in src/main/resources/dbunit.yml
@DataSet(cleanAfter=true)
public class MergeDataSetsIt {

        @Test
        @DataSet("yml/user.yml")
	public void shouldMergeDataSetsFromClassAndMethod() {
         
    }
}

```

Global cleanUp is not possible at the moment, a PR is welcomed. CleanBefore is [done here](https://github.com/database-rider/database-rider/blob/09e34bd47b4b66a3841c63adaea5ec382cfa87fd/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L131)  and `cleanAfter` is [done here](https://github.com/database-rider/database-rider/blob/09e34bd47b4b66a3841c63adaea5ec382cfa87fd/rider-core/src/main/java/com/github/database/rider/core/RiderRunner.java#L118) and [here](https://github.com/database-rider/database-rider/blob/09e34bd47b4b66a3841c63adaea5ec382cfa87fd/rider-cdi/src/main/java/com/github/database/rider/cdi/DBUnitInterceptorImpl.java#L117).

**Comment by rmpestano** [comment]
I think my suggestion will not work because merge datasets ignores class level properties for non array properties, [see here](https://github.com/database-rider/database-rider/blob/09e34bd47b4b66a3841c63adaea5ec382cfa87fd/rider-core/src/main/java/com/github/database/rider/core/util/AnnotationUtils.java#L177). This is basicaly because there is no way to know if for example `cleanAfter` is defined at method level.

**Comment by abelsromero** [comment]
Would it make sense to have a dataset.yml that defines new defaults? Then the annotation can be used to replace them if needed for a test.

**Comment by rmpestano** [comment]
Yes but the main issue is that If we don't define a default on the `@Dataset` annotation we obligate users to define them when they use the annotation. If you know a way to handle that then let's go for it

**Comment by rmpestano** [comment]
Note that the annotation will be used most of the time because datasets may change between tests

**Comment by rmpestano** [comment]
Hi @abelsromero, [with this PR](https://github.com/database-rider/database-rider/pull/180) you can specify cleanBefore in a `@BeforeEach` callback which would result in cleaning db before every test, eg:

```
    @BeforeEach
    @DataSet(cleanBefore = true)
    public void cleanBeforeEach() {

    }
```

I know you would like a way to override defaults but this can help your usecase.
