### ISSUE TITLE
Ingnoring shema name in method  createDataSet()

### ISSUE THREAD

**Issue by eaxdev** [database-rider/database-rider#157]
My dataset look like this:

```yaml
entity.SearchKey:
  - name: "testUser"
```

I using `SpringBoot` and `JUnit4`. I created simple test:

```java
@DBRider
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {TestConfig.class})
@AutoConfigureMockMvc
public class SearchKeyControllerTest {
    @Test
    @DataSet(value = "search_key.yml")
    public void tryToCreateSearchKeyWithDuplicateName() throws Exception {
       //some test
    }
}
```

But, when I try run my test, I get error:
```
Caused by: org.dbunit.dataset.NoSuchTableException: entity.SearchKey
	at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:305)
	at org.dbunit.operation.DeleteAllOperation.execute(DeleteAllOperation.java:109)
	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:166)
	... 24 more
```
This is because schema was ignoring! This screenshot in the debug shows this:
![error](https://user-images.githubusercontent.com/13472225/65376672-6a277580-dcab-11e9-8f64-766da57b59ac.png)

`resultDataSet` contains `entity.SearchKey`, It's ok, but method `org.dbunit.database.DatabaseDataSet.getTableMetaData` want only table name, without schema.  

TableName in this screen contains `entity.SearchKey`  instead simple `SearchKey`:
![tableName](https://user-images.githubusercontent.com/13472225/65376733-39940b80-dcac-11e9-8dbf-dff6cb344147.png)

My `dbunit.yml`:

```yaml
properties:
  caseSensitiveTableNames: true
  qualifiedTableNames: true
```
Say please, how can I fix it. Thx!

**Comment by eaxdev** [comment]
I added `metadataHandler: !!org.dbunit.ext.mysql.MySqlMetadataHandler {}` in `dbunit.yml` and it work for me

**Comment by rmpestano** [comment]
Thanks for sharing the solution!
