### ISSUE TITLE
absolute path with spaces to sql script  is not treated correctly and trow FileNotFoundException

### ISSUE THREAD

**Issue by TonnTamerlan** [database-rider/database-rider#158]
In case when the absolute path to the sql script file contains spaces than this script cannot be read for execution.

`
2019-11-13 12:24:59 [main] WARN  c.g.d.r.c.d.DataSetExecutorImpl - Could not read script file /home/service/target/test-classes/some%20directory%20with%20space/clear_tables.sql. Error in line 0.

java.io.FileNotFoundException: /home/service/target/test-classes/some%20directory%20with%20space/clear_tables.sql. (No such file or directory)
`

It is not difficult to rename some folders in the local machine, but in remote environment it can be like a challenge. Particularly Jenkins names folders as job names and they can contain spaces.

**Comment by rmpestano** [comment]
Thank you!

**Comment by TonnTamerlan** [comment]
@rmpestano Could you tell please when will it be released?
