### ISSUE TITLE
Not relevant json during export database to dataset json file

### ISSUE THREAD

**Issue by TonnTamerlan** [database-rider/database-rider#161]
During exporting database data to json file in the case when last values are null then there is added extra comma that is not valid json format
I mean, when we have a row with the next values:
```
|   column_1   | column_2 | column_3 | column_4 |
| -------------| -------- | -------- | -------- |
|  some value  |   null   |    42    |   null   |
```
then will be generated next json with the extra comma in the last object parameter
```(javascript)
{
    "tableName":[
         {
            "column_1": "some value",
            "column_3": 42,
        }
    ]
}

```

[Pull reauest](https://github.com/database-rider/database-rider/pull/160)

**Comment by TonnTamerlan** [comment]
@rmpestano When can it be released? We use json import in our project and should correct files after importing

**Comment by rmpestano** [comment]
Hi @TonnTamerlan, It was just released, thank you for the contribution!
