### ISSUE TITLE
Use SpringExtension.getApplicationContext() in DBUnitExtension

### ISSUE THREAD

**Issue by sbrannen** [database-rider/database-rider#165]
## Overview

The following...

https://github.com/database-rider/database-rider/blob/c31923614bf1a0252e92ddd5b1eb2d9bde5480f1/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L108-L110

... can be simplified as:

```java
DataSource dataSource = SpringExtension.getApplicationContext(extensionContext).getBean(DataSource.class);
```

## Related Issues

- #147

**Comment by rmpestano** [comment]
Thank you for the hint @sbrannen!
