### ISSUE TITLE
Since 1.9.0, @BeforeEach calls occurring before dataset is loaded

### ISSUE THREAD

**Issue by ericjturley** [database-rider/database-rider#178]
I'm running into a problem while integrating 1.9.0 and 1.9.1, and I'm wondering if it's known.
In many of my tests, the `@BeforeEach` functions set up some data using dbrider.
Previous to 1.9.0, those worked as expected, but now I'm finding that calls like the one below aren't working the same - as if the dataset is NOT LOADED YET.
```
     @BeforeEach
     fun setUp() {
         endpoint = endpointRepository.findById(9905L).orElseThrow()
         numRowsBeforeTest = numRowsCurrently(appAccountRepository)
     }
```
The first line throws an exception, and the var for the second line is set to zero - as if the data set was not yet loaded.

**Comment by rmpestano** [comment]
Hi, I think it never worked because we always used `BeforeTestExecutionCallback` to read dataset value, [see here](https://github.com/database-rider/database-rider/blob/bf8dd53625b7e1195816bacfcfac2b871e152356/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L39).  This callback runs after BeforeEach as the [javadoc says](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/extension/BeforeTestExecutionCallback.html):

>  BeforeTestExecutionCallback defines the API for Extensions that wish to provide additional behavior to tests immediately before each test is executed.
Such callbacks will be invoked after any user defined setup methods (e.g., @BeforeEach methods).

**Comment by ericjturley** [comment]
It was different when I was using:
* 1.7.1
* `com.github.database.rider.spring.*` package

Migrating to 1.9.1 may not have included the change. But perhaps changing from the spring package to the `junit5` package did.
I'm attempting to look into it now.

One thing I'm sure of - making the change ABSOLUTELY made the difference. 
My tests used to RELY on the `@BeforeEach` annotation, and they passed. Now every test which relies on it, fails.

Regardless of the change which caused this, IMHO, there ought to be a way to access loaded dataset data before and after each test.

**Comment by ericjturley** [comment]
I'm sure you already know this, but it looks to me that the `spring` package's use of JUnit 4 Rules are what created the behavior where datasets were loaded before the `@BeforeEach` -annotated method call.

I think junit5 db-rider should at least offer the configuration option to use the `BeforeEachCallback` instead, so that loaded-dataset access is possible in the `@BeforeEach` functions.

**Comment by rmpestano** [comment]
Yes, as stated on the readme and docs, spring module is based on junit4.

Unfortunatelly we don't have to much to do in dbrider side, you could call DatasetExecutor and populate db on your beforeEach call, for example see here: https://github.com/database-rider/database-rider/blob/master/README.adoc#dataset-executor

I hope It helps

**Comment by ericjturley** [comment]
What about this bit I proposed? Can we not use the different callback?

> I think junit5 db-rider should at least offer the configuration option to use the `BeforeEachCallback` instead, so that loaded-dataset access is possible in the `@BeforeEach` functions.

**Comment by rmpestano** [comment]
Yes, I think It is possible to have a config for enabling that but It should be done on `@DBRider` annotation from juni5 module.
 I'll have a look If I find time over the weekend but If anyone else wants to contribute and have questions just let me know

**Comment by rmpestano** [comment]
Hi @ericjturley, 

I've just opened a PR to enable datasets to be loaded in Before and after each callbacks **but note that you have to specify the DataSet you want to load.**

Please have a look at [this example](https://github.com/database-rider/database-rider/pull/180/files#diff-f1c3073f647a2baf59200ba9c9f5ab47).

**Comment by ericjturley** [comment]
Hi, @rmpestano 
That's definitely helpful and better in some circumstances! :)

I'm seeing, tho, that only one dataset will be loaded in `@BeforeEach`, per class. We often have different datasets per test function. I see that that is mitigated by the fact that whatever a class needs to access during `@BeforeEach` should be available in that dataset, but that requires splitting up datasets into "common" and "function-specific".

Still, that's really cool :)

I noticed on line 41 in the PR where the `BeforeEachCallback` is implemented, but don't see that the `AfterEachCallback` is implemented. But the test passes - so I'm curious how that works...

**Comment by rmpestano** [comment]
>  I'm seeing, tho, that only one dataset will be loaded in @BeforeEach, per class. 

You can can specify multiple datasets in `@DataSet`, e.g:  `@DataSet(value = {"dataset1.yml", "dataset2.json", "dataset3.xml"})`

> We often have different datasets per test function 

Yes and that's the most common case where you declare `@DataSet` on your test method. I don't know if I got the issue here, maybe you can provide some examples.

> I noticed on line 41 in the PR where the BeforeEachCallback is implemented, but don't see that the AfterEachCallback is implemented. But the test passes - so I'm curious how that works...

So the main issue with `AfterEachCallback` is that it is executed after the AfterEach method itself (see extensions [callback order here](https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order)). So in order to get dataset loaded before the AfterEach method I'm calling the AfterEach cllback logic [manually in the extension here](https://github.com/database-rider/database-rider/pull/180/files#diff-af3d61df03d97812814d89ef694f3b06R109), after test execution.

**Comment by ericjturley** [comment]
Sorry - I'm not being clear. I'm aware that more than one datset can be specified on `@Test` and now, `@BeforeEach`.

What I mean is that ideally:

As a configuration option (perhaps set before running tests), for each `@Test`:
1. The dataset is loaded during `BeforeEachCallback` instead of `BeforeTestExecutionCallback` - without having to specify datasets on the `@BeforeEach` method - so that the dataset can be queried and assertions made on initial state prior to the test.
2. The dataset cleanup is done during `AfterEachCallback` so that assertions can be made on the final state of the data during `@AfterEach`.

**Comment by rmpestano** [comment]
> so that the dataset can be queried and assertions made on initial state prior to the test.

Why do you need to make assertions before test? isn't it sufficient that database state is ensured when test is exucuted? do you have an example where current setup does not solve your problem?

> The dataset cleanup is done during AfterEachCallback so that assertions can be made on the final state of the data during @AfterEach.

That can be done with `@ExpectedDataSert`, database state will be asserted based on a dataset after test execution, without the need for writting any code, just specify the dataset.

I'm sorry, I still can see your use case, do you have code examples?

**Comment by ericjturley** [comment]
```kotlin


import com.github.database.rider.core.api.dataset.DataSet
import com.github.database.rider.core.api.dataset.ExpectedDataSet
import com.github.database.rider.spring.api.DBRider
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig

@DataJpaTest(showSql = false)
@SpringJUnitConfig
@DBRider
@DataSet(value = ["baseDataSet.yml"])
internal open class AppAccountRepositoryTest(private val someRepository: SomeRepository) {

    private var aThing: AThing? = null
    private var numRowsBeforeTest: Long = 0

    /**
     * Perform initial state verifications, and store pre-test data (repository row count)
     * for later comparison
     */
    @BeforeEach
    fun setUp() {
        aThing = someRepository.findById(9905L).orElseThrow() // <- This fails because data is not initialized 
        numRowsBeforeTest = someRepository.count()            // <- This fails because data is not initialized
    }

    /**
     * Perform final state verifications
     */
    @AfterEach
    fun tearDown() {
        aThing = someRepository.findById(9905L).orElseThrow()
    }

    /**
     * Save an object, and verify row count
     */
    @Test
    @ExpectedDataSet(value = ["expected/afterSaveAndFind.yml"])
    fun saveAndFind() {
        val somethingSaved = someRepository.save(something)
        assertEquals(numRowsBeforeTest + 1, someRepository.count())
    }

}
```

**Comment by rmpestano** [comment]
Why are you concerned with database state before and after the test? How important is that for your business logic?

In your example you can `remove` both:

`assertEquals(numRowsBeforeTest + 1, someRepository.count())`

And the `afterEach` method and put your desired db state after test execution in `expectedDataSet`

You don't need to have class level variable for controlling number of rows, just check db state in `@ExpectedDataSet`

If you want a dataset to be loaded in all tests without needing to specify on all of them, then use the new feature which accepts `@DataSet` in BeforeEach callback.

I hope It helps.
