### ISSUE TITLE
DataSetExecutorImpl#executeStatements swallows exception

### ISSUE THREAD

**Issue by renannprado** [database-rider/database-rider#179]
So at the [following line](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L462) you can see that the `DataSetExecutorImpl` swallows an exception in case executing the statement fails.

I believe the behavior should be: either rethrow the exception (causing your test to fail) or return a boolean  which can be asserted by the test to ensure that it succeeded (in case that's the intention of the test).

**Comment by rmpestano** [comment]
Hi there, yes, I think we should only warn and rethrow, thanks for the heads up

**Comment by renannprado** [comment]
That'd be great! It's not a backwards compatible behavior, but I believe it's the right thing to do.

I'm not super familiar with the codebase of the lib, but I believe I can create a patch for it.

So the release is roughly once per month?

**Comment by rmpestano** [comment]
Hi again,

> renannprado opened this issue 7 hours ago · 2 comments
Comments
@renannprado renannprado commented 7 hours ago
So at the following line you can see that the DataSetExecutorImpl swallows an exception in case executing the statement fails.

I believe the behavior should be: either rethrow the exception (causing your test to fail) or return a boolean which can be asserted by the test to ensure that it succeeded (in case that's the intention of the test).

@rmpestano rmpestano commented 6 hours ago
Hi there, yes, I think we should only warn and rethrow, thanks for the heads up

@renannprado renannprado commented 4 hours ago
That'd be great! It's not a backwards compatible behavior, but I believe it's the right thing to do.

Yes, release 1.10.0 and state that in release notes!

> I'm not super familiar with the codebase of the lib, but I believe I can create a patch for it.

It would be really great! 

> So the release is roughly once per month?

We don't follow a release schedule, it depends on how many and how critical the new contributions are.
