### ISSUE TITLE
Sql handle issue in DataSetExecutorImpl.readScript* when value string contains ";"

### ISSUE THREAD

**Issue by cz3pearl** [database-rider/database-rider#189]
Current DataSetExecutorImpl in version 1.10.1 will handle

INSERT INTO TABLE_NAME VALUES (10, "user;name")

as two sql

INSERT INTO TABLE_NAME VALUES (10, "user
 
name")

**Comment by rmpestano** [comment]
Fixed by #188, thank you @cz3pearl!
