### ISSUE TITLE
rider-spring create compile time error in java 11 for package import javax.xml.namespace.QName;

### ISSUE THREAD

**Issue by abhijava2** [database-rider/database-rider#190]
I am using spring rider with spring boot 2.2. based mircoservice using java 11.
I am facing compilation error due to this dependency spring rider added into my pom.xml

spring-rider version: 1.10.0
java 11
spring boot 2.2.4
error message : The package javax.xml.namespace is accessible from more than one module: <unnamed>, java.xml

error line : import javax.xml.namespace.QName;

**Comment by rmpestano** [comment]
Hi @abhijava2, sorry for the late response but you still face the issue?

If yes, can you share a reproducer project?

Thanks
