### ISSUE TITLE
Support for explicit schema configuration

### ISSUE THREAD

**Issue by beskow** [database-rider/database-rider#191]
We build a multi-tenant solution based on separate schema per tenant, and hence we have the same tables defined in multiple schemas. Because of this, we run into problems with AmbiguousTableNameException (see e.g http://dbunit.sourceforge.net/apidocs/org/dbunit/database/AmbiguousTableNameException.html). Since we use Postgres, constraining visible tables based on user credentials is not possible, and using qualifiedTableNames prevents reusing DataSets.

We therefore need to be able to pass in a schema when the DatabaseConnection is created, which occurs in a private method in RiderDataSource. The easiest way would be to extend the DBUnit configuration mechanism with a schema option, e.g.

dbunit.yml:

    properties:
      ...
      schema: public
      ....

or using an annotation:

    @DBUnit(cacheTableNames = false, allowEmptyFields = true, batchSize = 50, schema = "public")

**Comment by rmpestano** [comment]
Fixed by #192, this feature will be available in `v1.11.0` to be released in next days. Thank you @beskow!
