### ISSUE TITLE
Foreign key constraint violation during `clearDatabase`

### ISSUE THREAD

**Issue by iakunin** [database-rider/database-rider#202]
## Short problem description
Unable to clear database completely because of a foreign key constraints violation.

## Software versions
* postgres: 11.5
* database-rider: **rider-spring:1.10.0** with underlying **rider-core:1.10.0**

## Steps to reproduce
:warning: To reproduce this problem you should have [Docker](https://docs.docker.com/get-docker/) installed on your environment.

1. Clone the repo https://github.com/iakunin/codexia-bot:
```
git clone git@github.com:iakunin/codexia-bot.git && cd codexia-bot
```
2. Checkout to specific branch:
```
git checkout rider-fk-violation
```
3. Run the test with problem
```
bash bin/gradle_in_docker.sh clean test --info --tests *SendReviewsIntegrationTest.reviewSentWith500
```
4. Grep the postgres container logs 
```
cat var/pg-container.log |  grep -v "SELECT NULL AS TABLE_CAT" | grep -v "FROM pg_catalog.pg_type" | grep -v "pg_catalog.pg_namespace" | tail -n16
```

And you will see the following output:
```
2020-04-17 11:26:45.671 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.codexia_project where 1=1
2020-04-17 11:26:45.671 UTC [69] ERROR:  update or delete on table "codexia_project" violates foreign key constraint "codexia_review_codexia_project_id_fkey" on table "codexia_review"
2020-04-17 11:26:45.671 UTC [69] DETAIL:  Key (id)=(5) is still referenced from table "codexia_review".
2020-04-17 11:26:45.671 UTC [69] STATEMENT:  DELETE FROM public.codexia_project where 1=1
2020-04-17 11:26:45.672 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.codexia_review where 1=1
2020-04-17 11:26:45.672 UTC [69] ERROR:  update or delete on table "codexia_review" violates foreign key constraint "codexia_review_notification_codexia_review_id_fkey" on table "codexia_review_notification"
2020-04-17 11:26:45.672 UTC [69] DETAIL:  Key (id)=(1) is still referenced from table "codexia_review_notification".
2020-04-17 11:26:45.672 UTC [69] STATEMENT:  DELETE FROM public.codexia_review where 1=1
2020-04-17 11:26:45.673 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.codexia_review_notification where 1=1
2020-04-17 11:26:45.675 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.databasechangelog where 1=1
2020-04-17 11:26:45.676 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.databasechangeloglock where 1=1
2020-04-17 11:26:45.676 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.github_repo where 1=1
2020-04-17 11:26:45.677 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.github_repo_source where 1=1
2020-04-17 11:26:45.678 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.github_repo_stat where 1=1
2020-04-17 11:26:45.679 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.hackernews_item where 1=1
2020-04-17 11:26:45.680 UTC [69] LOG:  execute <unnamed>: DELETE FROM public.stars_up_result where 1=1
```

Pay attention to this: `ERROR:  update or delete on table "codexia_project" violates foreign key constraint "codexia_review_codexia_project_id_fkey" on table "codexia_review"`. 
I think, that is pretty clear sign of a problem.

As a result, the table `codexia_project` is not cleared as expected.

It is worth mentioning that corresponding exception is not rethrown, but just logged and swallowed ([link to source](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L637-L638)).

## Suggested solution
Decorate the [com.github.database.rider.core.dataset.DataSetExecutorImpl#clearDatabase](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L603) method with [disableConstraints()](https://github.com/database-rider/database-rider/blob/b03cf80002ab82e7f918aa56aa8852896f3bac77/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L326) call before and with [enableConstraints()](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L389) call after.

Something like this:
```
/**
 * @throws SQLException if clean up cannot be performed
 */
@Override
public void clearDatabase(DataSetConfig config) throws SQLException {

    disableConstraints();

    // the original code left intact

    enableConstraints();
}
```

**Comment by iakunin** [comment]
@rmpestano what do you think about this issue?

**Comment by kayma-hl** [comment]
Makes absolutely sense to me as you are cleaning the database.

**Comment by iakunin** [comment]
@kayma-hl would it be OK if I open a pull-request with solution I suggested?

**Comment by arhohuttunen** [comment]
I got intrigued because I have been using this myself without problems.

```
$ ./gradlew test --tests *SendReviewsIntegrationTest.reviewSentWith500
BUILD SUCCESSFUL in 56s
```

Are you sure there's not something else going on, like do you happen to have a postgresql server instance running on localhost?

**Comment by iakunin** [comment]
> Are you sure there's not something else going on, like do you happen to have a postgresql server instance running on localhost?

Yes, I'm sure. There is no need to run a separate postgresql server, because I'm using [testcontainers](https://www.testcontainers.org/) in the example.

Can you see the `var/pg-container.log` file after gradle build finished?

**Comment by arhohuttunen** [comment]
```
$ cat var/pg-container.log |  grep -v "SELECT NULL AS TABLE_CAT" | grep -v "FROM pg_catalog.pg_type" | grep -v "pg_catalog.pg_namespace" | tail -n16

2020-04-17 14:48:58.035 UTC [70] DETAIL:  parameters: $1 = '5'
2020-04-17 14:48:58.039 UTC [70] LOG:  execute <unnamed>: update public.codexia_review_notification set updated_at=$1, codexia_review_id=$2, response=$3, response_code=$4, status=$5 where id=$6
2020-04-17 14:48:58.039 UTC [70] DETAIL:  parameters: $1 = '2020-04-17 17:48:58.024757', $2 = '1', $3 = '<200 OK OK,[matched-stub-id:"97daf627-1ded-44d8-9f7e-9b43776f9788", server:"Jetty(9.4.20.v20190813)", transfer-encoding:"chunked", vary:"Accept-Encoding, User-Agent"]>', $4 = '200', $5 = 'SUCCESS', $6 = '4'
2020-04-17 14:48:58.041 UTC [70] LOG:  execute S_1: COMMIT
2020-04-17 14:48:58.059 UTC [69] LOG:  execute <unnamed>: select id, uuid, codexia_review_id, status, response_code, response, created_at, updated_at from codexia_review_notification order by id
2020-04-17 14:48:58.061 UTC [69] LOG:  execute <unnamed>: select id, uuid, codexia_project_id, author, reason, text, created_at, updated_at from codexia_review order by id
2020-04-17 14:48:58.064 UTC [69] LOG:  execute <unnamed>: BEGIN
2020-04-17 14:48:58.064 UTC [69] LOG:  execute <unnamed>: delete from hackernews_item where 1 = 1
2020-04-17 14:48:58.064 UTC [69] LOG:  execute <unnamed>: delete from stars_up_result where 1 = 1
2020-04-17 14:48:58.064 UTC [69] LOG:  execute <unnamed>: delete from github_repo_stat where 1 = 1
2020-04-17 14:48:58.065 UTC [69] LOG:  execute <unnamed>: delete from github_repo_source where 1 = 1
2020-04-17 14:48:58.065 UTC [69] LOG:  execute <unnamed>: delete from github_repo where 1 = 1
2020-04-17 14:48:58.065 UTC [69] LOG:  execute <unnamed>: delete from codexia_review_notification where 1 = 1
2020-04-17 14:48:58.065 UTC [69] LOG:  execute <unnamed>: delete from codexia_review where 1 = 1
2020-04-17 14:48:58.065 UTC [69] LOG:  execute <unnamed>: delete from codexia_project where 1 = 1
2020-04-17 14:48:58.067 UTC [69] LOG:  execute S_2: COMMIT
```

**Comment by rmpestano** [comment]
I think if you use disableConstraints=true [in your test](https://github.com/iakunin/codexia-bot/blob/3f7a2750218b3d2de1ba891823d744cc5b2d991c/src/test/java/dev/iakunin/codexiabot/codexia/cron/SendReviewsIntegrationTest.java#L93) it should work because we run disableConstraints before clearing the database, [see here](https://github.com/database-rider/database-rider/blob/b03cf80002ab82e7f918aa56aa8852896f3bac77/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L113-L116), can you try that?

**Comment by rmpestano** [comment]
Hmmm but for the test you'll want to have it enabled, of course. 

Can you send a PR for that?

**Comment by iakunin** [comment]
> Hmmm but for the test you'll want to have it enabled, of course.

@rmpestano that's exactly what I wanted to write you just now =)

**Comment by iakunin** [comment]
@arhohuttunen seems that you're running the tests on `master` branch. Are you sure that you've done `git checkout rider-fk-violation` ?

**Comment by arhohuttunen** [comment]
```
$ git branch
  master
* rider-fk-violation
```

**Comment by iakunin** [comment]
@arhohuttunen could you, please, run `gradle test` exactly as I described in the issue? Via `bin/gradle_in_docker.sh`. I suppose the problem could be either in OS environment or in cached gradle-dependencies.

For elimination the problem with cached dependencies you can also try to run build without any build cache at all (from the project root dir):
```
docker run \
    --tty \
    --interactive \
    --privileged \
    --rm \
    --volume=${PWD}:/home/gradle/project \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --workdir=/home/gradle/project \
    gradle:6.0.1-jdk11 \
    gradle clean test --info --tests *SendReviewsIntegrationTest.reviewSentWith500
```

After that you'll need to change the ownership of newly created files. You can do that by using this command:
```
docker run \
    --tty \
    --interactive \
    --privileged \
    --rm \
    --volume=${PWD}:/home/gradle/project \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --workdir=/home/gradle/project \
    gradle:6.0.1-jdk11 \
    chown -R $(id -u):$(id -g) .
```

**Comment by arhohuttunen** [comment]
Well, I made all the tests in your test class use `cleanBefore` and `cleanAfter` instead of the custom cleanup script and now it fails.

It seems to fail because it's deleting the tables in the wrong order, as the order should be reversed. The default dbunit behaviour:

> DbUnit inserts and updates rows in the order they are found in your dataset; deletes on the other hand are done in reverse order. You must therefore order your tables and rows appropriately in your datasets to prevent foreign keys constraint violation.

Should database-rider do the same? Disabling the constraints sounds a little dirty if there is something in the database with foreign keys that is not defined in the datasets.

**Comment by rmpestano** [comment]
If you use CLEAN_INSERT strategy DBUnit will delete in reverse order of the tables declared in the dataset. In case of `cleanBefore=true` there is no dataset involved, we try to clean all tables, not only the ones declared in the dataset. You can also specify the order of tables to be deleted by cleanBefore in tableOrdering property of `@DataSet`

**Comment by iakunin** [comment]
> Can you send a PR for that?

@rmpestano here you are: https://github.com/database-rider/database-rider/pull/203

**Comment by arhohuttunen** [comment]
Ah, I see, then it makes sense. Doesn't that mean that the table ordering is not needed anymore then?

**Comment by rmpestano** [comment]
>  Doesn't that mean that the table ordering is not needed anymore then?

Maybe, the problem is that not all DBs are supported in disabled constraints, also there is one DB (don't remember which one) that you can configure it in a way that you cannot disable constraints,.

So I think we should keep the table ordering

**Comment by rmpestano** [comment]
This issue was implemented by #203 and will be available in `v1.13.0`

**Comment by arhohuttunen** [comment]
I haven't been able to dig down into the root cause, but after updating to 1.13.0 version some existing tests in our project started to fail because they are not throwing an exception from foreign key constraint violations anymore. Downgrading `database-rider` to 1.12.0 the tests still work.

**Comment by rmpestano** [comment]
Hi @arhohuttunen, interesting. If you find the cause and can create a reproduced that would be great!

Also, if you can checkout 1.13.0 tag and just comment out [these changes](https://github.com/database-rider/database-rider/pull/203/files#diff-91367f3f37f42c0105bc9f9dd65dad9bR606-R649) to see if it related with the fix then it can be easier to find the root cause.

**Comment by arhohuttunen** [comment]
First of all I need to tell that we are not using `disableConstraints` anywhere. The test pass when you run them individually. But running the suite of all tests makes the foreign key related tests to fail.

What seems to happen is that when we hit the test in question, the code calls `enableConstraints` automatically, but that is being skipped because the `isConstraintsDisabled` flag is false.

What is the lifecycle of this state? Could it be possible that if not all the tests are using the same database, the constraints are not re-enabled correctly? Because if I run a set of tests that are using the same database, then that set will pass.

**Comment by rmpestano** [comment]
> What is the lifecycle of this state? 

So if you use `cleanBefore=true` or `cleanAfter=true`, since v1.13.0 we are disabling constraints during the cleanUp and re-enabling after cleanUp. 
We clean during [dataset creation](https://github.com/database-rider/database-rider/blob/acdb79a49780f3651fadafd4c040cb250d5d1c85/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L116) and
DataSet creation is invoked by [DBUnitRule](https://github.com/database-rider/database-rider/blob/acdb79a49780f3651fadafd4c040cb250d5d1c85/rider-core/src/main/java/com/github/database/rider/core/DBUnitRule.java#L76), [Junit5Extension](https://github.com/database-rider/database-rider/blob/acdb79a49780f3651fadafd4c040cb250d5d1c85/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L279), [RiderSpring](https://github.com/database-rider/database-rider/blob/acdb79a49780f3651fadafd4c040cb250d5d1c85/rider-spring/src/main/java/com/github/database/rider/spring/DBRiderTestExecutionListener.java#L25) CDI Interceptor or RiderDSL

**Comment by arhohuttunen** [comment]
I'm having a little trouble extracting an example that I could share but I'm giving this out to illustrate what is happening:

```kotlin
@DBRider
@TestPropertySource(properties = [
    "spring.datasource.url = jdbc:tc:postgresql:10.7-alpine://hostname/database"
])
class ExampleTest {
    @Test
    @Order(1)
    @DataSet(cleanBefore = true)
    fun makeTheSecondTestFail() {
    }

    @Test
    @Order(2)
    @DataSet("users.yml")
    fun constraintViolation() {
        val user = createUser(
            userId = "987d68a6-bd95-4830-a938-a9b735800e37",
            addressId = "5cf7387d-5f61-406f-b306-e4e9c2a2f0bf"
        )

        val exception = assertThrows<PersistenceException> {
            userRepository.save(user)
            entityManager.flush()
        }
        // fails because it's not throwing the exception

        assertThat(exception).isCausedByConstraintViolation("user_address_id_fkey")
    }
}
```
Removing the first test makes the second one pass.

**Comment by rmpestano** [comment]
Maybe re-enabling constraints is not possible in postgres. 

Can you try the following in the version that works (`v1.12.0`)?

```
class ExampleTest {
    @Test
    @Order(1)
    @DataSet(disableConstraints = true)
    fun makeTheSecondTestFail() {
    }

    @Test
    @Order(2)
    @DataSet("users.yml")
    fun constraintViolation() {
        val user = createUser(
            userId = "987d68a6-bd95-4830-a938-a9b735800e37",
            addressId = "5cf7387d-5f61-406f-b306-e4e9c2a2f0bf"
        )

        val exception = assertThrows<PersistenceException> {
            userRepository.save(user)
            entityManager.flush()
        }
        // fails because it's not throwing the exception

        assertThat(exception).isCausedByConstraintViolation("user_address_id_fkey")
    }
```

**Comment by rmpestano** [comment]
Can you try with `v1.13.1-SNAPSHOT` @arhohuttunen? you'll need to [enable snapshots repo ](https://github.com/database-rider/database-rider#snapshots)on your build system.

**Comment by arhohuttunen** [comment]
I tried adding the cleanup to the second method as well and it works in `v1.13.0`:

```
@Test
    @Order(2)
    @DataSet("users.yml", cleanBefore = true)
```

Could it be actually that this happens because of transactions, because `@DataJpaTest` is adding the `@Transcational` annotation?

I also noticed that we were accidentally using `rider-spring` instead of `rider-junit5` but it seems like the latter one does not work with Spring `@Transactional`, see [comment](https://github.com/database-rider/database-rider/issues/183#issuecomment-625623123).

**Comment by arhohuttunen** [comment]
When you disable transactional tests it works as well:

```kotlin
@DataJpaTest
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@DBRider
@TestPropertySource(properties = [
    "spring.datasource.url = jdbc:tc:postgresql:10.7-alpine://hostname/database"
])
class ExampleTest {
    @Test
    @Order(1)
    @DataSet(cleanBefore = true)
    fun makeTheSecondTestFail() {
    }

    @Test
    @Order(2)
    @DataSet("users.yml")
    fun constraintViolation() {
        val user = createUser(
            userId = "987d68a6-bd95-4830-a938-a9b735800e37",
            addressId = "5cf7387d-5f61-406f-b306-e4e9c2a2f0bf"
        )

        val exception = assertThrows<PersistenceException> {
            userRepository.save(user)
            entityManager.flush()
        }

        assertThat(exception).isCausedByConstraintViolation("user_address_id_fkey")
    }
}
```

**Comment by rmpestano** [comment]
> I also noticed that we were accidentally using rider-spring instead of rider-junit5 but it seems like the latter one does not work with Spring @Transactional, see comment.

yea, If you use JUnit5 then you should use `@DBRider` from JUnit5 module. The transactional issue may be related to the fact that the spring repository already has transactional annotation. Also note that in JUnit5 module we don't integrate with spring transaction context as we do in spring module. In JUnit5 we just get the connection from spring datasource and use that to populate the database in dbrider.

**Comment by arhohuttunen** [comment]
I wasn't aware that the JUnit 5 module is not hooking up to the Spring transaction context. We are pretty much using `@DataJpaTest` everywhere instead of `@SpringBootTest`. This definitely happens because of the transactions. I'll continue the discussion in the other issue.
