### ISSUE TITLE
AmbiguousTableNameException caused by ‘same table name for different oracle user’

### ISSUE THREAD

**Issue by irvingqiu0823** [database-rider/database-rider#205]
AmbiguousTableNameException occuerd when i used db-rider for oracle database.
It happens when different oracle users has the same table name.
How to use @Dataset when this phenomenon exists?

**Comment by rmpestano** [comment]
Hi, have you tried to specify the schema?

` @DBUnit(schema = "mySchema")`

you can specify it for all tests in [dbunit.yml](https://github.com/database-rider/database-rider#332-dbunit-configuration)

**Comment by rmpestano** [comment]
One thing that I saw in this [SO answer ](https://stackoverflow.com/a/10108123/1260910) is that you can use `qualifiedTableNames`, maybe that helps as well:

`@DBUnit(qualifiedTableNames = true)`

**Comment by irvingqiu0823** [comment]
@rmpestano Thanks bro, I've tried those two ways. The first one works(@DBUnit(schema = "mySchema")), and the second one didn't work(@DBUnit(qualifiedTableNames = true).

Have you ever tried to use dbrider along with ORM such as mybatis ? How can I use it without connecting to the real environment ?

**Comment by rmpestano** [comment]
Hi @irvingqiu0823, if you use SpringBoot you can configure test database using a test profile, for example [here](https://github.com/rmpestano/springboot-dbunit-testcontainers/blob/master/src/test/resources/application-integration-test.properties) we configure postgres test db using test containers. Later we activate such [profile in the test](https://github.com/rmpestano/springboot-dbunit-testcontainers/blob/0f6a0f6114744a8012c364a13cf57ba3852fc377/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitIt.java#L32).  

There is also [docker container for Oracle](https://www.testcontainers.org/modules/databases/oraclexe/) so you just need to find a way to change the db configuration on the tests and that depends on the technology you use.

I hope it helps.

**Comment by rmpestano** [comment]
Also In CDI you can use bean specialization to override db configuration, [see here](https://github.com/database-rider/database-rider/blob/aa142b4a4cabb47589ad222c150ad73ea59453c5/rider-examples/jpa-productivity-boosters/src/test/java/com/github/database/rider/examples/CdiTestConfig.java#L12).

**Comment by irvingqiu0823** [comment]
@rmpestano OK, I got U. I guess if I don't want to use a real DB, I have to use an implement of memory DB such as hsqldb. I was just wondering how to use pure data instead of using a DB instance, and could test sql at the same time. But it seems unrealistic.

**Comment by rmpestano** [comment]
Hi, with [test containers](https://www.testcontainers.org/) and docker it is not unrealistic but recommended to test against a real db.

**Comment by irvingqiu0823** [comment]
I will try it later. Thanks

**Comment by rmpestano** [comment]
I'll close this issue, if you have more questions, please open a new one. 

Thanks for your feedback!
