### ISSUE TITLE
Need ability to load datasets from an URL

### ISSUE THREAD

**Issue by duschata** [database-rider/database-rider#209]
As far as I understood the DataSetExecutorImpl, there is no way to pass URLs as datasets. The datasets are always loaded from the classpath. To load datasets from outside the classpath I've  modified the DataSetExecutorImpl, so that the dataset path is checked whether it is possibly an URL. If it does not, then simply continue to search in classpath/resources/datasets. The original behavior does not change.

https://github.com/database-rider/database-rider/compare/master...duschata:tmp_getDatasetByURL

If you think this is useful and agree to the changes, I would like to request a PR. Otherwise I am open to further suggestions.

Kind regards,
Tom

**Comment by rmpestano** [comment]
Hi @duschata,

Just to understand the use case, your idea is to share datasets among different applications? 

If that's the case maybe we could load datasets from jar files, we support sql scripts in jars (see [here](https://github.com/database-rider/database-rider/blob/2364adebc70fbc46d48f843df134b376d9c7a2f0/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L806)), maybe we could do something similar with datasets, WDYT?

Thank you for the idea and feedback!

**Comment by duschata** [comment]
Hi Rafael @rmpestano 
to briefly explain the use case: I wrote a gradle plugin, which starts a rest service (in this case it is the authentication service keycloak, but it could also be something else)
All of our applications - which we test with arquillian by the way - require this service in integration tests.
Before the actual tests start, this service must be deployed, started and needs a defined database state (all done by the plugin).

The plugin is configurable from the outside and, as a parameter for this plugin we have paths to the xml, json, yml files for the initialization. As databases, we have a colorful mix of Oracle, H2 and mysql
I have seen that RiderDSL does exactly what I need for my usecase, except that it cannot load the datasets from absolute paths.

Hence the idea with the URL: the datasets that I want to load from the absolute path begin with file: // and are therefore easily distinguishable. Other protocols (such as http) would also be possible, the only exception is the csv-clause, because we need a folder there. However, we could theoretically limit the protocol to files.

the method loadDataset()
https://github.com/database-rider/database-rider/blob/2364adebc70fbc46d48f843df134b376d9c7a2f0/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L241

is public and was good entry point for me.

https://github.com/database-rider/database-rider/blob/2364adebc70fbc46d48f843df134b376d9c7a2f0/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L591

is private and I cannot overwrite it for my purposes

BTW - the lines

https://github.com/database-rider/database-rider/blob/2364adebc70fbc46d48f843df134b376d9c7a2f0/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L256-L259

are probably redundant. I can't see any behavior there, which is not implemented in the exception block.

Possible further solutions (than the last one) would be:

to add getDataSetStream to the interface (DataSetExecutor) to let the implementation decide how to get the stream. The prerequisite for this solution would be that all file handlers called in the method loadDataset() will use this one getDataSetStream() method, but this would be possible.
or
to overload the loadDataset method like this: loadDataset(String name, DataStreamHandler sthImplementingLoadDataset).

Greetings from Darmstadt/Germany

Tom

**Comment by rmpestano** [comment]
Hi @duschata, thank you for the details

> is public and was good entry point for me.

Yea, I think that's the best place to change but I think we should try to load from URL at the end of the method because it's a fairly uncommon use case, what do you think?

> BTW - the lines ... are probably redundant. I can't see any behavior there, which is not implemented in the exception block.

Yes, looks like so


Can you open a PR for this?

Thank you again for the feedback, cheers!

**Comment by duschata** [comment]
I would like to run all Tests before PR. I' ve no clue about the docker tests. Please give me a hint. Greetings Tom

**Comment by rmpestano** [comment]
Hi for docker tests you just need to have docker installed on your machine, [see here](https://docs.docker.com/docker-for-windows/install/)

If you already have It installed and is facing any error, post the error stacktrace here

**Comment by duschata** [comment]
I know, I'm Linux user and have already installed docker. Maybe I've an issue with permissions.

**Comment by rmpestano** [comment]
Maybe you just need to upgrade your docker installation otherwise you can just ignore them for now and write non docker based test. The docker tests will run on CI when you submit the PR.

**Comment by duschata** [comment]
No problem. I fixed it. Docker tests are running now. The only problem was that you must login into https://index.docker.io/v1/ to run the tests.

**Comment by duschata** [comment]
Hi Rafael, probably you know the adoc(umentation) better than I. Where is the the best place to document my changes?

Greetings Tom (PR submitted)

**Comment by rmpestano** [comment]
Hello Tom, 

I think we can add a subsection to the [configuration section](https://github.com/database-rider/database-rider#33-configuration). 

It can be the first subsection (before `DataSet Configuration`) and be called **Loading datasets**, what do you think?

**Comment by rmpestano** [comment]
I think it is more appropriate to add inside [dataset configuration section](https://github.com/database-rider/database-rider#331-dataset-configuration), at the end, after will talk about `@DataSet` (just before 3.3.2), WDYT?

**Comment by duschata** [comment]
Hi Rafael,
I've also updated the documentation. Have a look there.

**Comment by rmpestano** [comment]
Thank you very much @duschata, your contribution will be available in `v1.15.0` which will be released in next weekend.

**Comment by duschata** [comment]
@rmpestano thank your for maintenanting this project and merging the new feature
