### ISSUE TITLE
Replacer from dbunit.yml is not applied for expected datasets

### ISSUE THREAD

**Issue by DaryaKolyadko** [database-rider/database-rider#212]
Hello.

I am using dbrider 1.14.0.

I need to replace values in all expected datasets.
I wrote custom replacer and added it into config dbunit.yml like:
```
properties:
  replacers: [!!com.example.CustomDbRiderReplacer {}]
```

Unfortunately it didn't work.

What I mentioned during debugging dbrider code is that for initial datasets all replacers from global config (dbunit.yml) and DataSet annotation config are applied.
But during comparison with expected dataset only annotation specific replacers are taking into account.

Code fragment from com.github.database.rider.core.RiderRunner where replacers from ExpectedDataSet are passing:
```
    private void performDataSetComparison(RiderTestContext riderTestContext) throws DatabaseUnitException {
        ExpectedDataSet expectedDataSet = riderTestContext.getAnnotation(ExpectedDataSet.class);

        if (expectedDataSet != null) {
            riderTestContext.getDataSetExecutor()
                    .compareCurrentDataSetWith(new DataSetConfig(expectedDataSet.value())
                                    .disableConstraints(true).datasetProvider(expectedDataSet.provider()),
                            expectedDataSet.ignoreCols(),
                            expectedDataSet.replacers(),
                            expectedDataSet.orderBy(),
                            expectedDataSet.compareOperation());
        }
    }
```

And that is the fragment of repalcer processing:
```
 @Override
    public void compareCurrentDataSetWith(DataSetConfig expectedDataSetConfig, String[] excludeCols,
                                          Class<? extends Replacer>[] replacers, String[] orderBy, CompareOperation compareOperation) throws DatabaseUnitException {
        IDataSet current = null;
        IDataSet expected = null;
        List<Replacer> expectedDataSetReplacers = new ArrayList<>();
        if (replacers != null && replacers.length > 0) {
            for (Class<? extends Replacer> replacerClass : replacers) {
                try {
                    expectedDataSetReplacers.add(replacerClass.newInstance());
                } catch (InstantiationException | IllegalAccessException e) {
                    throw new IllegalArgumentException(replacerClass.getName() + " could not be instantiated as Replacer");
                }
            }
        }
```

dbUnitConfig repalcers are not used at all.

I would expect replacers to be merged from several sources same as for DataSet processing.

**Comment by rmpestano** [comment]
Hi @DaryaKolyadko,

I was trying to remember the rationale of having replacers in `@ExpectedDataSet` instead of using the global replacers, do you remember @vinsgithub?

I couldn't find a reason, so I maybe we should deprecate `replacers` property in `@ExpectedDataSet` and only use global replacers, what do you think @database-rider/rider-community?

**Comment by vinsgithub** [comment]
Hi @rmpestano ,
I should resume the project, In my PR there was an explanation
https://github.com/database-rider/database-rider/issues/100
I currently have no time to deep dive into the question and give a more concrete answer.
Really, really sorry.

**Comment by rmpestano** [comment]
Hi @vinsgithub, yea I read the explanation but still don't get why replacers cannot be shared, maybe an example?

> This configuration object is strictly tight to (input) DataSet whereas only connection is used to read ExpectedDataSet. Replacers cannot (and shouldn't, I think) be in common with ExpectedDataSet

please take your time, no rush.

Thank you!

**Comment by rmpestano** [comment]
Also, instead of deprecate `replacers` property in `@ExpectedDataSet` you can also define it on `@DataSet` and then document how they should apply (I think annotation should have precedence over global configuration) so we can have consistent behavior of `replaces` between `@DataSet` and `@ExpectedDataSet`

**Comment by rmpestano** [comment]
Hi @DaryaKolyadko, I have added replacer property to `@DataSet` as well so both annotations have it.   

The logic is that replacer declared at annotation level will replace the global configuration one.  

You can try it in`v1.14.1-SNAPSHOT` by [enabling snapshots repo](https://github.com/database-rider/database-rider#snapshots).

This will be available in `v1.15.0`.

Thank you for the feedback

**Comment by DaryaKolyadko** [comment]
Hi @rmpestano , thanks for your answer and work!

The changes you've listed sound like a good feature but actually does not resolve the issue I tried to describe.

With changes of your commit `@DataSet` annotation processing uses 3 sources of replacers:
- global config `dbunit.yml`
- `@DBUnit(replacers = "..")`
- annotation itself `@DataSet(replacers = "..")`

While` @ExpectedDataSet` uses only 1 source of replacers:
- annotation itself `@ExpectedDataSet(replacers = "..")`

It would be nice to have `@ExpectedDataSet` be processed in the same way as `@DataSet` is.

**Comment by rmpestano** [comment]
Hi @DaryaKolyadko,

yes you're right, now it should be ok.

Thank you again!

**Comment by DaryaKolyadko** [comment]
Hi @rmpestano! 

Just tested new snapshot with `@ExpectedDataSet`
Works like a charm! Now looks at all 3 sources of replacers.

Thank you!

**Comment by rmpestano** [comment]
Thank you for the feedback!
