### ISSUE TITLE
Export binary data (byte [])

### ISSUE THREAD

**Issue by Antonio-Raposo** [database-rider/database-rider#216]
Hello.
I have a blob column in my database and while importing is a breeze, exporting data I get some weird Strings like "[B@3fb4beb1", which result from the Object.toString() method on the byte array. These objects should be exported the same way as they are imported, in base64 encoding.
I suggest an improvement in YMLWriter, at line 93 of version 1.14.0, replacing
```
if(values[i] != null){
    out.write(values[i].toString());
}
```
with
```
if(values[i] != null){
    if(values[i] instanceof byte[]){
        out.write(Base64.getEncoder().encodeToString(values[i]));
    } else {
        out.write(values[i].toString());
    }
}
```
Hope this helps.

António.

**Comment by rmpestano** [comment]
Hi @Antonio-Raposo,

can you try with v`1.14.1-SNAPSHOT`? you'll need to [enable snapshots repo](https://github.com/database-rider/database-rider#snapshots) on your build. 

Thank you for the feedback!

**Comment by Antonio-Raposo** [comment]
Yes, it looks great. I am in the process of replacing lots of native inserts to prepare the database with @DataSet annotations and being able to export the prepared database is indeeed a great help.
Thank you.

**Comment by rmpestano** [comment]
Thank you for opening this issue.
