### ISSUE TITLE
Dynamic class loading 

### ISSUE THREAD

**Issue by akondasif** [database-rider/database-rider#219]
Greetings, 

We are researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of dynamic class loading. [OWASP](https://rules.sonarsource.com/java/tag/owasp/RSPEC-2658)  says "Dynamically loaded classes could contain malicious code executed by a static class initializer i.e. you wouldn't even have to instantiate or explicitly invoke methods on such classes to be vulnerable to an attack."

Hopefully, you agree and will fix it.

Source: https://github.com/database-rider/database-rider/blob/master/rider-cdi/src/main/java/com/github/database/rider/cdi/DataSetProcessor.java and https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java and https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/util/ClassUtils.java

**Comment by rmpestano** [comment]
Hello @akondasif, sorry for the late reply and thanks for looking into this.

This library is not a long-running process on any operating system, it's lifespan is attached to the test execution phase (e.g maven/gradle test phase) and will be terminated after that. Do you still think that can be issue?
