### ISSUE TITLE
RiderDSL should have one instance per thread

### ISSUE THREAD

**Issue by duschata** [database-rider/database-rider#223]
Hallo All.
please have a look at this changes:

https://github.com/database-rider/database-rider/compare/master...duschata:thread_local_issue?diff=split

I'm not the super thread expert but I think the current master implementation does not have the behavior which people expect. The if(INSTANCE=null) block is only entered one time (when the first thread asks for an instance) and then never again. I think we must give every thread a new Instance. Greetings Tom

**Comment by rmpestano** [comment]
Hey @duschata, you're right, the idea is to have one instance per thread, can you submit the PR?

Thank you again!
