### ISSUE TITLE
Limit the database type.

### ISSUE THREAD

**Issue by kerraway** [database-rider/database-rider#227]
We use MySQL in our dev/test/production environment, and use H2 in unit test environment.

Configuration is in src/main/resources/datasource.xml and src/test/resources/datasource.xml.

If the developer rename the src/test/resources/datasource.xml config file, the MySQL datasource will be used in unit test environment. And if the developer run unit tests, the @DataSet will clear the data in MySQL database.

So I wonder to know how to limit the database type for database-rider or dbunit in unit test environment? In this way, We don't need to worry the data in MySQL database.

**Comment by rmpestano** [comment]
Hi, I don't think there is a solution for the this, the same can happen with other tools like Flyway, Liquibase or Hibernate where a misconfiguration can harm your db.

Now the question is, why a dev would hardcode production db connection in the application? This information should be outside the application

**Comment by kerraway** [comment]
We use `src/main/resources/datasource.xml` to configure MySQL datasource, and use separate configuration files to provide dev/test/production jdbc url/username/password/etc. And we use `src/test/resources/datasource.xml` to configure H2 datasource in unit test environment.

When developer removes or renames the `src/test/resources/datasource.xml`, Spring will load `src/main/resources/datasource.xml` file in unit test environment.

So I want a configuration for specifying database type, and I can configure the database type to "H2" in unit test environment.
May be in dbunit.yml configuration file?

**Comment by rmpestano** [comment]
If you're using Spring then I suggest using it to configure your datasource and not rely on `dbunit.yml`. Have you tried using `@ActiveProfiles` to specify the test configuration? See an [example here](https://github.com/rmpestano/springboot-dbunit-testcontainers/blob/0f6a0f6114744a8012c364a13cf57ba3852fc377/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitIt.java#L32).

**Comment by kerraway** [comment]
We aren't using SpringBoot, just Spring Framework. And we use `src/test/resources/datasource.xml` and  `src/main/resources/datasource.xml` to divisive official and unit-test environment.

I think using `@ActiveProfiles`, also have the possibility to harm the mysql db due to misconfiguration.

If I configure the database type that database-rider or dbunit can operate, misconfiguration wouldn't harm mysql db.

**Comment by rmpestano** [comment]
I don't understand how we can solve that on dbrider level. Do you have an example of how that would work?

**Comment by kerraway** [comment]
Thx for your help, I don't have any solution yet. I will do some research.
