### ISSUE TITLE
Columns are ignored if they are not supplied in the first row for that table in the dataset

### ISSUE THREAD

**Issue by manoswerts** [database-rider/database-rider#232]
This issue occurs again: https://github.com/database-rider/database-rider/issues/34

In this case, column 3 of row 2 isn't persisted:
```
<table1 column1="row1col1" column2="row1col2"/>
<table1 column1="row2col1" column2="row2col2" column3="row2col3"/>
```

It is when I just change the order:
```
<table1 column1="row2col1" column2="row2col2" column3="row2col3"/>
<table1 column1="row1col1" column2="row1col2"/>
```

The order shouldn't matter.

**Comment by rmpestano** [comment]
Hi, please provide more input so anyone can try to help. Not everyone has the context for what is the issue.

Can you provide sample code or even better, a PR with a failing test on our test suite?

Thank you for the feedback!

**Comment by brunneng** [comment]
Hi, I have the same issue :(

**Comment by brunneng** [comment]
```
<table1 column1="row1col1" column2="row1col2"/>
<table1 column1="row2col1" column2="row2col2" column3="row2col3"/>
```
In the XML configuration (didn't check in other) seems only columns mentioned in the first row (in this case: column1, column2) are inserted for all subsequent rows of the table. column3 for all rows is null, after applying dataset.

So as workaround we should make sure, that the first row contains the most full list of columns and rows with nulls should follow after.
Using **rider-spring:1.16.1**.

**Comment by rmpestano** [comment]
Hi guys, looking at the [PR](https://github.com/database-rider/database-rider/pull/33), it was fixed for YAML dataset.

For XML we use standard dbunit [XML datasets](https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L17-L23) so maybe consider opening an issue at dbunit project

**Comment by rmpestano** [comment]
Closing as it's not related to DBRider
