### ISSUE TITLE
Cucumber | Inject Data To Custom Replacer

### ISSUE THREAD

**Issue by Raawaan** [database-rider/database-rider#234]
Hello,

i'd like to replace ticketId to the test seed data
i've tried to implement Replacer interface but there is no way to inject data dynamically (we are not able to use spring beans)
```
public class TicketIdReplacer implements Replacer {

    @Override
    public void addReplacements(ReplacementDataSet dataSet) {
        dataSet.addReplacementSubstring("$ticketId","ADD VARIABLE");
    }
    
}
```
note: implementing beanFactoryAware interface didn't fix the issue.

**Comment by rmpestano** [comment]
Hi, can you share your test class and the dataset?

**Comment by Raawaan** [comment]
Hello,

Seed File 
```  
<CAMPAIGNS id="$ticketId" name="$campaignName" />
```

adding replacer to dataSet config

```
    public void runDataSet(String dataSetName) {
        DataSetConfig dataSetConfig = new DataSetConfig(dataSetName);
        Class[] replacers = new Class[]{CampaignCustomReplacer.class};
        dataSetConfig.setReplacers(replacers);
        dbUnitExecutor.createDataSet(dataSetConfig);
    }
```

**Comment by rmpestano** [comment]
Your code looks ok, I need to have a further look

**Comment by Raawaan** [comment]
the issue is in my TicketIdReplacer class
```
public class TicketIdReplacer implements Replacer {

    @Override
    public void addReplacements(ReplacementDataSet dataSet) {
        dataSet.addReplacementSubstring("$ticketId",**"HERE"**);
    }
    
}
```
i want to pass variable to TicketIdReplacer instead of "HERE" above, so the ticketId value added to every test case is different.
note: the TicketIdReplacer is instantiated by database rider

**Comment by rmpestano** [comment]
I see, replacers cannot do that for you.

Maybe you can explain the whole use case, why do you need to have a dynamic ticketId in dataset? 

If you share a complete test case with you test, dataset and what you're trying to do, maybe I can help
