### ISSUE TITLE
Is there any way in Database Rider to reduce duplication of @DataSet configuration properties?

### ISSUE THREAD

**Issue by brunneng** [database-rider/database-rider#237]
Hi, is there any way in Database Rider to reduce duplication of **DataSet** configuration properties?

For example, suppose we have:

```
@DataSet(value = "yml/test1.yml", cleanAfter = true, skipCleaningFor = {"zone_code", "product_code", "product_type", "user_type"})
public void test1() {
  //...
}

@DataSet(value = "yml/test2.yml", cleanAfter = true, skipCleaningFor = {"zone_code", "product_code", "product_type", "user_type"})
public void test2() {
  //...
}
```
Here as you can see **cleanAfter** and **skipCleaningFor** are duplicated. And this is just an example. The list of skipCleaningFor can be even longer. Having hundreds of tests with the same list of skipped tables is a nightmare. Imagine we need to change this list in hundreds of places.

Extracting this list to some static final variable is not an option, because parameters to annotation can be only true inline constants (you will get compilation error).

[Meta datasets](https://github.com/database-rider/database-rider#38-meta-datasets) are one of the ways of reducing duplication but they include ALL properties, and it's not possible to override some of the properties (like the **value** in my example)

[Merge datasets](https://github.com/database-rider/database-rider#39-merge-datasets) looks promising, but not sure...

**Comment by rmpestano** [comment]
Hi @brunneng, yea that's not so simple problem to solve, mainly because with primitive values in `@DataSet` like `cleanAfter` there's no way to distinguish if the value was provided by the user or it's the default value in the annotation that's being used.

I think merge datasets can help but another alternative can be [DataSet providers](https://github.com/database-rider/database-rider#311-dataset-providers) where you can compose/merge providers easily, [see here](https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/test/java/com/github/database/rider/core/DataSetProviderIt.java#L321-L352) for example.

**Comment by brunneng** [comment]
@rmpestano Thanks, it's interesting, but I can't find the ability to configure clearing of db tables from DataSetBuilder / IDataSet.

**Comment by rmpestano** [comment]
"but I can't find the ability to configure clearing of db tables from DataSetBuilder / IDataSet." All tables declared in dataset will be cleared before the dataset data is inserted, so you just have to declare `zone_code`,  `product_code` etc... in dataset provider like `DefaultTablesForCleaningProvider`:

```
public class DefaultTablesForCleaningProvider implements DataSetProvider {

        @Override
        public IDataSet provide() {
            return new DataSetBuilder()
                    .table("zone_code")
                    .columns("id")
                     .table("product_code")
                     .columns("id")
                    .build();
        }
    }
```

**Comment by brunneng** [comment]
But I want to **skip cleaning** for these tables and to clean all the others.

**Comment by rmpestano** [comment]
I see, for that you either use as on your first comment or just don't use cleanBefore/After and don't declare the tables.

**Comment by brunneng** [comment]
Seems I figured out how to do it using merging datasets.
First, we need some **BaseTest** for all our tests with the config of **skipCleaningFor** :
```
@DataSet(value = "yml/empty.yml", cleanAfter = true, skipCleaningFor = {"zone_code", "product_code", "product_type", "user_type"})
class BaseTest
```
Where empty.yml it's just some empty dataset to avoid error during tests execution.
Then, in the test class, we put
```
@DbUnit(mergeDataSets = true)
@DBRider
MyTest extends BaseTest {
   @DataSet(value = "yml/test1.yml", cleanAfter = true)
   public void test1() {
     //...
   }

   @DataSet(value = "yml/test2.yml", cleanAfter = true)
   public void test2() {
     //...
   }
```
And that's it - the config is no longer duplicated!
