### ISSUE TITLE
Usage of RiderDataSource by DataSetExecutorImpl leaks db connections

### ISSUE THREAD

**Issue by nruzic** [database-rider/database-rider#241]
Hi guys, I have problems on my project with db connection leakage caused by dbridder.

I think that problem is in few places in DataSetExecutorImpl where RiderDataSource member variable is just annulated before closing connection hold by RiderDataSource instance:

- https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L1049
- https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L506
- https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L1049
- https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L1070

I'm not a dbridder expert. Can someone please double check my findings.

**Comment by rmpestano** [comment]
Hi @nruzic, the sql connection is stored in ConnectionHolder object which is reused by the executor in multiple tests.

What's the issue are you facing? do you have any reproducer project?

Thanks for the feedback.
