### ISSUE TITLE
Slow Sequence Filtering on real database

### ISSUE THREAD

**Issue by RomashkoVictor** [database-rider/database-rider#242]
Hi everyone.
I use Database rider with postgres database in docker container. I found out, that tests are becoming slower and slower when we add tablse into DataSet. After some investigation, I found that DBrider during SequenceFiltering the method 'RiderSequenceFilter#getDependencyInfo' use big amount of test time( nearly 90%).
It use DBUnit to retrieve 'allDependentTables', 'allDependsOnTables' and order tables to perform in correct order delete and instert calls.

The issue is that this method is called for every table in DataSet and for every test.

I disabled sequence filtering and added table ordering and received following test times:
33 test methods took **1m 6s** to run, after optimization they took **7 seconds**.

I propose three features.

1. tableOrdering parameter of '@DataSet' annotation is very uncomfortable.
`
@DataSet(value = "dataset.yml", useSequenceFiltering = false, tableOrdering = {"table1",
      "table2", "table3", "table4", "table5", "table6"})
`
We cannot move those String array to one place, so we should duplicate very long array in each method. It very inconvinient to support.
Can we ordering tables as they exist in dataset file(in our case in yml file)? 
Now implementation use HashMap and ordering in yml file was broken. We can use LinkedHashMap and save initial ordering of dataset.

2. Can we merge '@DataSet' annotation that is placed on test method and class. This feature allow us to place some configuration, like useSequenceFiltering or tableOrdering in one place( base abstract class) and in each test simple specify dataset location.

3. Reduce number of calls to 'RiderSequenceFilter#getDependencyInfo'. We can store information about our table relations and if we retrieve metadata for _table1_ in one test method, no necessity to do it in other test method.

**Comment by rmpestano** [comment]
Hi @RomashkoVictor, for `1` and `2` have a look at [mergeDatasets feature](https://github.com/database-rider/database-rider/issues/237#issuecomment-699518522).

For 3 I'm not sure, needs further investigation

**Comment by RomashkoVictor** [comment]
@rmpestano Thanks for quick feedback.
Unfortunatelly [mergeDatasets feature](https://github.com/database-rider/database-rider/issues/237#issuecomment-699518522) solution isn't work in our case.
What we have:
`
@DBRider
@DataSet(useSequenceFiltering = false, tableOrdering = {"table1", "table2"})
abstract class BaseTest {
`

`class ConcreteText extends BaseE2ETest {
@Test
  @DataSet(value = "dataset.yml")
  @ExpectedDataSet(value = "dataset.yml"})
  void retrieveAll() throws Exception {
`
dbunit.yml
`properties:
  caseSensitiveTableNames: true
  schema: schema
  allowEmptyFields: true
mergeDataSets: true`

And this fails with error:
`Caused by: java.lang.RuntimeException: No dataset loaded for name 
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.loadDataSet(DataSetExecutorImpl.java:295)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.loadDataSets(DataSetExecutorImpl.java:305)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:149)
	... 74 more
`
This error is due 'AnnotationUtils#mergeDataSetAnnotations'
`public static DataSet mergeDataSetAnnotations(DataSet classLevelDataSet, DataSet methodLevelDataSet) {

        //only the lists are merged
        String[] value = joinArray(classLevelDataSet.value(), methodLevelDataSet.value());
`
Here method merge two arrays and we receive array with two elements: {"", "dataset.yml"}

For me is quite unusual to set **mergeDataSets** property. Why does this property in DBUnit annotation and false by default?
In Spring are many annotation are merged by default if you use them on class and test method.

What about **1** feature, it isn't related to merging datasets? This feature may replace _tableOrdering_  paramether at all.

**Comment by RomashkoVictor** [comment]
Ok, [mergeDatasets feature](https://github.com/database-rider/database-rider/issues/237#issuecomment-699518522) I didn't correctly read the unswer. Yes, if I add 'empty.yml' dataset,  the **2** feature is working.
may be it will be useful to fix merging error with empty dataset name?

Simply replace 
`public static DataSet mergeDataSetAnnotations(DataSet classLevelDataSet, DataSet methodLevelDataSet) {

        //only the lists are merged
        String[] value = joinArray(classLevelDataSet.value(), methodLevelDataSet.value());
`
by something like that
`
public static DataSet mergeDataSetAnnotations(DataSet classLevelDataSet, DataSet methodLevelDataSet) {

        //only the lists are merged
        String[] value = joinArray(classLevelDataSet.value(), methodLevelDataSet.value());
        value = removeEmptyAndNullElements(value);
        String[] tableOrdering = joinArray(classLevelDataSet.tableOrdering(), methodLevelDataSet.tableOrdering());
        String[] executeStatementsBefore = joinArray(classLevelDataSet.executeStatementsBefore(), methodLevelDataSet.executeStatementsBefore());
        String[] executeStatementsAfter = joinArray(classLevelDataSet.executeStatementsAfter(), methodLevelDataSet.executeStatementsAfter());
        String[] executeScriptsAfter = joinArray(classLevelDataSet.executeScriptsAfter(), methodLevelDataSet.executeScriptsAfter());
        String[] executeScriptsBefore = joinArray(classLevelDataSet.executeScriptsBefore(), methodLevelDataSet.executeScriptsBefore());
        String[] skipCleaningFor = joinArray(classLevelDataSet.skipCleaningFor(), methodLevelDataSet.skipCleaningFor());
        Class<? extends Replacer>[] replacers = joinReplacers(classLevelDataSet.replacers(), methodLevelDataSet.replacers());
        DataSet mergedDataSet = new DataSetImpl(value, methodLevelDataSet.executorId(), methodLevelDataSet.strategy(), methodLevelDataSet.useSequenceFiltering(), tableOrdering, 
                methodLevelDataSet.disableConstraints(), methodLevelDataSet.fillIdentityColumns(), executeStatementsBefore, executeScriptsAfter, executeScriptsBefore, executeStatementsAfter,
                methodLevelDataSet.cleanBefore(), methodLevelDataSet.cleanAfter(), methodLevelDataSet.transactional(), skipCleaningFor, replacers);
        return mergedDataSet;
    }

    public static String[] removeEmptyAndNullElements(String[] values) {
        List<String> result = new ArrayList<>(values.length);
        for(String value:values){
            if(value != null && !value.trim().isEmpty()) {
                result.add(value);
            }
        }
        return result.toArray(new String[0]);
    }
`

**Comment by rmpestano** [comment]
Hi @RomashkoVictor, can you create a separated issue for the mergeDataSets problem?

Thank you for the feedback!

**Comment by RomashkoVictor** [comment]
@rmpestano Yes, created https://github.com/database-rider/database-rider/issues/243

**Comment by RomashkoVictor** [comment]
My second proposal was implemented in https://github.com/database-rider/database-rider/issues/247

**Comment by rmpestano** [comment]
Can we close this issue?

**Comment by RomashkoVictor** [comment]
I think yes, because I don't know is it possible to implement third improvement and may be it will be difficult and unnecessary.

**Comment by rmpestano** [comment]
Hi @RomashkoVictor, in next version you'll also be able to disable filtering globally, see #252.

**Comment by RomashkoVictor** [comment]
@rmpestano Great, thanks)

**Comment by vaa25** [comment]
@rmpestano @RomashkoVictor you can cache DependencyInfo in RiderSequenceFilter for third improvrment:

```
private static final Map<String, RiderSequenceFilter.DependencyInfo> DEPENDENCY_INFO_CACHE = new ConcurrentHashMap<>();

private static RiderSequenceFilter.DependencyInfo getDependencyInfo(
            IDatabaseConnection connection, String tableName, DBUnitConfig dbUnitConfig)
            throws SearchException
    {
        logger.debug("getDependencyInfo(connection={}, tableName={}) - start", connection, tableName);

        if(!dbUnitConfig.isCaseSensitiveTableNames() && tableName != null) {
            tableName = applyCaseInSensitiveStrategy(tableName, dbUnitConfig);
        }

        if (DEPENDENCY_INFO_CACHE.containsKey(tableName)){
            return DEPENDENCY_INFO_CACHE.get(tableName);
        } else {
            ...
            DEPENDENCY_INFO_CACHE.put(tableName, info);
            logger.debug("New DependencyInfo for {} created}", tableName);
            return info;
      }
}
```

**Comment by rmpestano** [comment]
Hello @vaa25,

if all tests are passing after the change I'm happy to merge the PR, can you open one?

Thank you!

**Comment by vaa25** [comment]
@rmpestano Sure. Here you are. https://github.com/database-rider/database-rider/pull/258 . I tested it using as library in my project.
