### ISSUE TITLE
[Improvement] Add IncludeReplacer

### ISSUE THREAD

**Issue by GithubMood** [database-rider/database-rider#244]
### Motivation
When working with the database column that contains large text or some non-trivial format (like JSON/XML) it will be more convenient to move the content of the column into a separate file.

### Scope
Implement ClasspathFileReplacer that allows using the link to the classpath file in the column value.

**Comment by rmpestano** [comment]
Thank you so much @GithubMood, this feature will be available in `v1.17.0` to be released (I hope) today.
