### ISSUE TITLE
Add support of multiple datasets for different datasources in the same test

### ISSUE THREAD

**Issue by GithubMood** [database-rider/database-rider#248]
### Motivation

In the complex application that works with multiple relational databases, there is a need for integration testing with running 2 databases simultaneously. It would be good to have an option for managing datasets for different databases in the same test (for instance: use case of transferring data from one database to another).

### Scope
As it is a challenging requirement it makes sense to reduce the scope and consider the changes only for the Spring extension for the momment.

### Possible solution design

Provide support for multiple DBRider annotations on the same test by combining dataset/expected-dataset inside the DBRider annotation. 

For instance:
![image](https://user-images.githubusercontent.com/23056623/98696754-d9af6700-237c-11eb-954c-a043111a13e6.png)

### Limitation
1. Using DBRider annotation attributes like dataSet/expectedDataSet may be allowed only for the case of multiple databases. Single database cases should use Dataset/ExpectedDataSet annotation directly for simplicity.
2. In case of using multiple DBRider annotations on the same test, all Dataset/ExpectedDataSet outside the scope of DBRider annotation will be ignored or restricted.

### Blokers

For implementing the proposed design, the version of Java should be at least 8 for compiling. Currently, the compilation of the source code is done on version 7 (that does not support repeatable annotations).

### Open questions

@rmpestano Please let me know if there is a chance of using the newer version of Java? It would be enough to update the version only for the module **"rider-spring"**. I would have a try of implementing the proposed solution.
If any comments/suggestions from your side, please share them with me.

**Comment by GithubMood** [comment]
Maybe I was too hurry when saying that Java 7 is a blocker. 
We can just use aggregate annotation.

Something like this:
![image](https://user-images.githubusercontent.com/23056623/98714549-b04d0600-2391-11eb-9359-e4466e70b9d9.png)

**Comment by rmpestano** [comment]
Hi @GithubMood, thanks for the idea but I think using RiderDSL would be easier in such cases. I mean, for a DBRider perspective I think there will be a lot of changes to support a not so common use case. 
If you can prepare a PR and show I'm wrong, that that can be done with small changes only on Spring module than maybe we can add it.

With RiderDSL you can easily work with multiple DS:

```
@RunWith(SpringRunner.class)
@DBRider(dataSourceBeanName = "data-source-2")
@ContextConfiguration(classes = TestConfig.class)
public class MultipleDataSourcesRiderDSLIt {

    @Autowired
    @Qualifier("data-source-2")
    private DataSource secondaryDataSource;

    @Autowired
    private DataSource defaultDataSource;

    private JdbcTemplate jdbcTemplate;

    @Test
    @DataSet(value = "ds2-test.yml")//populate secondary
    public void shouldUseSecondaryDataSource() throws SQLException, DatabaseUnitException {
        withConnection(defaultDataSource.getConnection())
                .withDataSetConfig(new DataSetConfig("test.yml"))
                .createDataSet(); //populate data in default ds
        jdbcTemplate = new JdbcTemplate(secondaryDataSource);
        Set<String> expected = new HashSet<>(Arrays.asList("value1", "value2"));
        Set<String> actual = new HashSet<>(jdbcTemplate.queryForList("SELECT value FROM Entity2", String.class));
        assertThat(actual).containsExactlyElementsOf(expected);
        withConnection()
                .withDataSetConfig(new DataSetConfig("test.yml"))
                .expectDataSet(); //expect data in default ds
    }
```

WDYT?

**Comment by GithubMood** [comment]
@rmpestano yeap, you are absolutely right. Much easier to use RiderDSL in such cases. 
Also, if I got your point, RiderDSL will work in any environment (Spring, Junit5, Cucumber). So I totally agree with you that supporting another approach is not worth:)

Thank you for your time!

Closing the issue then.
