### ISSUE TITLE
[Postgres] [OID] [Quarkus] [rider-cdi] java.lang.ClassCastException: class io.agroal.pool.wrapper.ConnectionWrapper cannot be cast to class org.postgresql.PGConnection

### ISSUE THREAD

**Issue by coiouhkc** [database-rider/database-rider#253]
Using `rider-cdi` (`1.18.0`) in Quarkus, trying to validate test results via `@ExpectedDataSet` for a table containing an `oid`-typed column I get above exception

`java.lang.ClassCastException: class io.agroal.pool.wrapper.ConnectionWrapper cannot be cast to class org.postgresql.PGConnection
`
### Stacktrace
>        at org.dbunit.ext.postgresql.PostgreSQLOidDataType.getSqlValue(PostgreSQLOidDataType.java:42)
>	  at org.dbunit.database.ForwardOnlyResultSetTable.getValue(ForwardOnlyResultSetTable.java:104)
>	  at org.dbunit.dataset.DefaultTable.addTableRows(DefaultTable.java:139)
>	  at org.dbunit.database.CachedResultSetTable.<init>(CachedResultSetTable.java:69)
>	  at org.dbunit.database.CachedResultSetTableFactory.createTable(CachedResultSetTableFactory.java:61)
>	  at org.dbunit.database.DatabaseDataSet.getTable(DatabaseDataSet.java:338)
>	  at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1004)
>	  at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1062)
>	  at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1057)
>	  at com.github.database.rider.cdi.DataSetProcessor.compareCurrentDataSetWith(DataSetProcessor.java:155)

### Reason
`PostgreSQLOidDataType` gets a `Agroal`-wrapped connection and cast fails

### Suggestion
Could you unwrap the connection prior to passing it to DBUnit, maybe in https://github.com/database-rider/database-rider/blob/06f738fdfe6ab7f2d5a6711c1115c5e5672025f0/rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java#L84?

### Also
Possibly related to #111

**Comment by rmpestano** [comment]
Hi, have you tried rider-cdi 1.21.0?

Also, we have [postgres test here](https://github.com/database-rider/database-rider/blob/06f738fdfe6ab7f2d5a6711c1115c5e5672025f0/rider-core/src/test/java/com/github/database/rider/core/PostgreSQLDatabaseIt.java#L28)  , How a failing test would look like?

Thanks for the feedback.

**Comment by coiouhkc** [comment]
Hi @rmpestano, i've tried the latest version, it's still failing. You'll find a small reproducer project here https://github.com/coiouhkc/dbrider-issue-253 (just execute `DbRiderIssue253Test`, it uses `testcontainers` to bootstrap a postgres for the test, so you'll need docker on the test machine).

**Comment by rmpestano** [comment]
Thank you very much for the reproducer.

Can you try with `v1.21.1-SNAPSHOT`? You'll need to [enable snapshots repo](https://github.com/database-rider/database-rider#snapshots) on your project.

**Comment by coiouhkc** [comment]
Hi @rmpestano, thanks for the quick fix - i tried it in both reproducer and real projects and both now work OK with regards to the issue. When do you plan to release the fix?

**Comment by rmpestano** [comment]
Hi, thanks for checking!

`1.21.1` should be at maven central in next hours.

Thank you again!
