### ISSUE TITLE
DBUnitInterceptorImpl seems to be relying on junit4 being transitively provided by dbunit

### ISSUE THREAD

**Issue by coiouhkc** [database-rider/database-rider#254]
Hi @rmpestano 
thanks again for the great tool!
I'm trying to workaround the https://sourceforge.net/p/dbunit/bugs/437/ (basically building a custom version of `rider-cdi` using custom version of `dbunit`) and i've noticed, that in the `master` of `dbunit` JUnit 4 is marked optional in `pom.xml`.
Does it make sense from your point of view to rely on JUnit 4 being provided for `rider-cdi` by dbunit? It's not given, that each project using `rider-cdi` is also using JUnit 4, in fact we're using JUnit 5 in our project ;)
Would it be better to maybe remove https://github.com/database-rider/database-rider/blob/1c2ba2aaa9ee1b4cc1f1ba101c619c480052ee7b/rider-cdi/src/main/java/com/github/database/rider/cdi/DBUnitInterceptorImpl.java#L41-44 from `DBUnitInterceptorImpl` and maybe provide this functionality in a separate `@Interceptor` with a higher `@Priority`?
Possibly related: #207 to make it consistent with JUnit 5

**Comment by rmpestano** [comment]
Hi @coiouhkc, sorry for the late reply  

> Does it make sense from your point of view to rely on JUnit 4 being provided for rider-cdi by dbunit? It's not given, that each project using rider-cdi is also using JUnit 4, in fact we're using JUnit 5 in our project ;)

I agree and I really don't remember why we're checking for junit 4 callback methods on the interceptior, so I think we can remove it:
``` 
 Method method = invocationContext.getMethod();
        if (method.isAnnotationPresent(Before.class) || method.isAnnotationPresent(BeforeClass.class) || method.isAnnotationPresent(After.class) || method.isAnnotationPresent(AfterClass.class)) {
            return invocationContext.proceed();
        }
```

can you provide a PR?

Thank you for the feedback!

**Comment by coiouhkc** [comment]
Hi @rmpestano , from what i've seen it could be related to #93 ... meanwhile i will prepare the PR.

**Comment by rmpestano** [comment]
Hi again @coiouhkc,

I have played a bit with this issue, have a look here: https://github.com/database-rider/database-rider/pull/257

Let me know what do you think

**Comment by coiouhkc** [comment]
Hi @rmpestano , from what i could understand it looks good, i'd only suggest to make the behaviour configurable, e.g. add a configuration property or add a `dbrider`-specific annotation like `IgnoreDBRiderInterceptor` o.s. 
I think it would be more flexible.

**Comment by rmpestano** [comment]
Thanks for the feedback.

For now, I don't think we need to make it configurable mainly because it's cdi module specific config and I don't think it would be nice to have it in global config. 

Also, creating an annotation only for that would add a bit of complexity we may not need.

Let's start with this constant set of annotations which I think will cover most of the cases and then if users have issues we can think of something else.     

Sounds good?

**Comment by coiouhkc** [comment]
Perfect!
