### ISSUE TITLE
DBUnitInterceptorImpl does not pass the expected CompareOperation to the dataSetExecutor compareCurrentDataSetWith

### ISSUE THREAD

**Issue by fcota92** [database-rider/database-rider#261]
When we use the `@ExpectedDataSet` annotation like in the following example, the CDI `DBUnitInterceptorImpl` only pass the  `value`, `provider` and `ignoreCols` properties.  Other properties, like `compareOperation`, `orderBy` and `replacers` are ignored.

```java
@ExpectedDataSet(value = "expectedUsersContains.yml", compareOperation = CompareOperation.CONTAINS, orderBy = "name")
```

One of the 2 calls to the `compareCurrentDataSetWith` in the `DBUnitInterceptorImpl`:

```java
dataSetProcessor.compareCurrentDataSetWith(
        new DataSetConfig(expectedDataSet.value())
                .datasetProvider(expectedDataSet.provider())
                .disableConstraints(true),
        expectedDataSet.ignoreCols());
```

**Comment by rmpestano** [comment]
Thanks for heads up
