### ISSUE TITLE
Missing data with HikariCP and autocommit=false

### ISSUE THREAD

**Issue by mbunzel** [database-rider/database-rider#262]
I'm not too familiar with DBUnit so perhaps I'm missing something obvious, but Database Rider doesn't seem to insert any data when the DataSource is wrapped in a Hikari pool with the autocommit property set to false. 

I've created a very simple reproducer [here](https://github.com/mbunzel/rider-hikari-autocommit) based on your spring boot examples. The tests succeed when spring.datasource.hikari.auto-commit in application.properties is set to true and fails when set to false.

**Comment by rmpestano** [comment]
Hi @mbunzel, 

Sorry for the late reply and thank you for the reproducer!

Can you try with v`1.26.1-SNAPSHOT` ([check here](https://github.com/database-rider/database-rider#snapshots) how to enable rider snapshots)?

**Comment by rmpestano** [comment]
The fix was release in v`1.27.0`, if the issue persists please open a new issue with the details, thanks!
