### ISSUE TITLE
Problems with inserting xml datasets into Oracle 19 DB

### ISSUE THREAD

**Issue by duschata** [database-rider/database-rider#265]
Hi All, hi Rafael (again),
I got this stack when I tried to read xml datasets into an Oracle 19 database. I hope the information is sufficient, otherwise I can also send a few lines of code.
Any ideas what could have gone wrong? Regards,

Tom

`
 DBUnit configuration for dataset executor 'default':cacheConnection: true
cacheTableNames: true
caseInsensitiveStrategy: UPPERCASE
columnSensing: true
leakHunter: false
mergeDataSets: false
schema: null
schema: 
tableType: [TABLE]
allowEmptyFields: false
fetchSize: 100
qualifiedTableNames: false
batchSize: 100
batchedStatements: false
caseSensitiveTableNames: false
replacers: [com.github.database.rider.core.replacers.DateTimeReplacer@361c20dc, com.github.database.rider.core.replacers.UnixTimestampReplacer@29b3be74, com.github.database.rider.core.replacers.NullReplacer@1a18a28]

13:27:43.248 [DEBUG] [org.dbunit.database.DatabaseConnection] Database connection info: 
        database product name=Oracle
        database version=Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
        database major version=19
        database minor version=0
        jdbc driver name=Oracle JDBC driver
        jdbc driver version=19.8.0.0.0
        jdbc driver major version=19
        jdbc driver minor version=8

13:27:43.248 [DEBUG] [org.dbunit.database.DatabaseConnection] validateSchema(validateStrict=false) - start
13:27:43.248 [DEBUG] [org.dbunit.database.DatabaseConnection] Schema is null. Nothing to validate.
13:27:43.248 [INFO] [org.dbunit.database.DatabaseConfig] The property ending with 'schema' was not found. Please notify a dbunit developer to add the property to the class org.dbunit.database.DatabaseConfig
13:27:43.248 [INFO] [org.dbunit.database.DatabaseConfig] The property ending with 'replacers' was not found. Please notify a dbunit developer to add the property to the class org.dbunit.database.DatabaseConfig
13:27:43.892 [WARN] [com.github.database.rider.core.dataset.DataSetExecutorImpl] Can't resolve schema
java.sql.SQLException: ResultSet.next was not called
        at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:374)
        at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:596)
        at com.github.database.rider.core.dataset.DataSetExecutorImpl.resolveSchema(DataSetExecutorImpl.java:761)
        at com.github.database.rider.core.dataset.DataSetExecutorImpl.resolveSchema(DataSetExecutorImpl.java:775)
        at com.github.database.rider.core.dataset.DataSetExecutorImpl.disableConstraints(DataSetExecutorImpl.java:348)
        at com.github.database.rider.core.dataset.DataSetExecutorImpl.clearDatabase(DataSetExecutorImpl.java:610)
        at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:131)
        at com.github.database.rider.core.dsl.RiderDSL.createDataSet(RiderDSL.java:34)
        at com.github.database.rider.core.dsl.RiderDSL$DBUnitConfigDSL.createDataSet(RiderDSL.java:145)
        at com.github.database.rider.core.dsl.RiderDSL$DBUnitConfigDSL$createDataSet$0.call(Unknown Source)

[...]

 Caused by: com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: file:/home/tom/src/java/gradle-keycloak-plugin/src/test/resources/datasets/initmigration.xml
13:30:46.843 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:173)
13:30:46.843 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dsl.RiderDSL.createDataSet(RiderDSL.java:34)
13:30:46.843 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dsl.RiderDSL$DBUnitConfigDSL.createDataSet(RiderDSL.java:145)

[...]

] Caused by: java.lang.RuntimeException: Error while disabling referential constraints on schema null
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dataset.DataSetExecutorImpl.disableConstraints(DataSetExecutorImpl.java:366)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dataset.DataSetExecutorImpl.clearDatabase(DataSetExecutorImpl.java:610)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:131)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 45 more
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Could execute statements:error occurred during batching: ORA-00903: invalid table name

 at oracle.jdbc.driver.OracleStatement.executeLargeBatch(OracleStatement.java:4659)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4527)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:237)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.database.rider.core.dataset.DataSetExecutorImpl.executeStatements(DataSetExecutorImpl.java:462)
13:30:46.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 48 more

`

**Comment by duschata** [comment]
Hi All,
finally (hours later) I've changed some lines of code and it works for me. The problem occours only if DataSetConfig.cleanBefore is set to true, because this flag disables/enablesContraints.

https://github.com/database-rider/database-rider/blob/52d14ea8436f0fa01a5d8cc844bf1437726e7001/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L391-L393

The qualifiedTableName and the contraintName is wrapped into singleQuotes " ' " and this seems not to work with Oracle 19. Removing this single quotes works for me, but I don't know if there are side effects, if the " ' " is not set.

**Comment by rmpestano** [comment]
Hi @duschata,

interesting, can you open a PR for that? 

Also, can someone test this on an older oracle version?  

Thank you for the feedback!

**Comment by rmpestano** [comment]
Fixed by #266, thank you @duschata
