### ISSUE TITLE
Escape double-quote and backslash characters when exporting data in YML and JSON format

### ISSUE THREAD

**Issue by beskow** [database-rider/database-rider#267]
We use embedded JSON as string values in a couple of tables, which cause issues when exporting data in YAML or JSON format (since the embedded JSON uses double-quotes for element names). Any double-quote or backslash character in a value should be properly escaped using \" and \\ respectively, in order to produce valid YAML or JSON.

**Comment by rmpestano** [comment]
Fixed by #268, thank you @beskow
