### ISSUE TITLE
Loading script file from within jar

### ISSUE THREAD

**Issue by jenskreidler** [database-rider/database-rider#27]
"As a Maven user with a centralized 'seeding'-project, I'd like database-rider to read the scripts/yaml files from within a potentially external jar."

I'm using Maven as build tool and centralize several "common" seeding files (sql, yml) in a separate project.
When executing integration tests with maven, `@Dataset(executeScriptsBefore="/a/b/c.sql", value="y/z.yml")` is not able to pick up the resource coming from a jar dependency (i.e. `jar:file:/home/foo/z.jar!/a/b/c.sql` from the local maven repository that's present in the mvn execution's classpath).

Database-rider should pick up the resource using e.g. a JarURLConnection or any other applicable solution.

I could provide a prototype implementation in DataSetExecutorImpl where the script resource is read appropriately in "public void executeScript(String scriptPath)".

**Comment by rmpestano** [comment]
Hi @jenskreidler,

that seems a really nice feature :+1: . I would be very happy to review and assist you in the pull request. 

Scripts a being [loaded here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L528) at the moment.
