### ISSUE TITLE
NPE on test methods not annotated with @DataSet (junit 5)

### ISSUE THREAD

**Issue by salashnik** [database-rider/database-rider#29]
Falls in `DBUnitExtension.afterTestExecution` if in test class annotated `@ExtendWith(DBUnitExtension.class)` exist test method without `@DataSet` because no executor present

as i see this is can be easy fixied:
instead

```java
DBUnitConfig dbUnitConfig = dbUnitTestContext.getExecutor().getDBUnitConfig();
```
must be
```java
DataSetExecutor executor = dbUnitTestContext.getExecutor();
DBUnitConfig dbUnitConfig = executor != null ? executor.getDBUnitConfig() : null;
```

**Comment by rmpestano** [comment]
Hi, nice catch, do you want to provide PR with an associated test case?

Thank you!

**Comment by salashnik** [comment]
done ;)

**Comment by salashnik** [comment]
may be have some sense don't exit when no `@DataSet` (shouldCreateDataSet) specified in `beforeTestExecution` and perform all operations with default values?

in current implementation if no `@DataSet` present will be skipped ststements & script executions, comparing and exporting datasets.

**Comment by rmpestano** [comment]
Hi there, about default values which dataset we would load before test execurion? Do you have an example?

**Comment by salashnik** [comment]
hmm. i'm really need some rest ;-)))
really all scripts/statements contained in `DataSet` annotation and no any changes in `before` needed.

but, may be some sense create executor in `after` if it is null for comparing and exporting?
