### ISSUE TITLE
Seed database with sql files

### ISSUE THREAD

**Issue by jenskreidler** [database-rider/database-rider#290]
As a developer, I want to use my yaml-based test-data-suite to initally feed an other test database instance. For doing so, I'd like to export/convert my *.yml files to sql-files and feed any database with that.

Is this feature included in database-rider? Or should one do an other trick, just in my mind would be: let a dbrider-unit-test point to a test database and run it hollowly against that database. Using the @DataSet capablities in order to seed the test database with the yml-testdata?

**Comment by rmpestano** [comment]
Hey @jenskreidler, I couldn't get the idea, do you have any code sample on how the feature look like? in my understand it's something a db migration tool would do but maybe I got it wrong

**Comment by jenskreidler** [comment]
@rmpestano : having a quick glance at that API it looks great and something I do soon really need. Thank you for that clue!
