### ISSUE TITLE
Config to apply uppercase to the table and columns names

### ISSUE THREAD

**Issue by gerosa** [database-rider/database-rider#32]
I'm using H2 database and its default behavior is to uppercase table and column names that are not quoted. DBUnit does the same thing when it generates the insert query. But Rider is not following this pattern and it only works if I keep all names in upper case in the yml file.

Is there a way to config this behavior?

**Comment by rmpestano** [comment]
Hi @gerosa,

In dbrider  1.0.0 we always used uppercase [[see here when we changed it](https://github.com/database-rider/database-rider/pull/22/commits/784e20f89b605735ec082197e6117a7b7b1385e6)] so it worked in H2 but breaks databases with case sensitive table names. 

So regarding  your suggestion I think it is nice and we can add a new property called 'uppercaseDatasets' which when true will create datatasets in uppercase.

What do you think? would you like to provide a pull request? [Here ](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/resources/default/dbunit.yml) is the default configuration file (can be [overriden by user](https://github.com/database-rider/database-rider#user-content-configuration)) and [here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java) is the class which reads this configuration

**Comment by rmpestano** [comment]
Done in PR #38
