### ISSUE TITLE
Enable support for datasets with the ".yaml" extension

### ISSUE THREAD

**Issue by renke0** [database-rider/database-rider#323]
As of now, creating datasets with the `.yaml` extension will result in an error, since `DataSetExecutorImpl::loadDataSet` is only looking up for files with the `.yml` extension.

Since both forms are valid and `.yaml` even being [the preferred format in yaml.org](https://yaml.org/faq.html), I believe this format should be supported as well.

**Comment by rmpestano** [comment]
Hi @renke0, makes sense.

It should be available in v`1.25.0` which should be out this weekend, thanks for the feedback!

**Comment by rmpestano** [comment]
v`1.25.0` was just released
