### ISSUE TITLE
Constraint handling uses unquoted table names 

### ISSUE THREAD

**Issue by ferdi-github** [database-rider/database-rider#328]
Currently there seems to be no way to use the `disableConstraints` feature on a database that contains tables named using reserved words (for example "USER" in an oracle database).

DBUnit itself provides a parameter `escapePattern` to work around this issue. However the constraint handling code in `DataSetExecutorImpl` does not take quoting into account 
https://github.com/database-rider/database-rider/blob/7e192aee0fc4b8b15074d1bbfa8e40ae9e4b51ce/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L386 

Note that the mentioned code source does support quoting:
- https://github.com/arteam/unitils/blob/master/unitils-core/src/main/java/org/unitils/core/dbsupport/OracleDbSupport.java#L190
- https://github.com/arteam/unitils/blob/master/unitils-core/src/main/java/org/unitils/core/dbsupport/DbSupport.java#L396

It would be great if database-rider either applies DbUnit's `escapePattern` setting or at least provides a dedicated configuration parameter.

**Comment by rmpestano** [comment]
Hi @ferdi-github, makes sense. Let's try to get this into next release (sorry for the late reply)

**Comment by rmpestano** [comment]
Hi again @ferdi-github, can you try with `1.25.1-SNAPSHOT`? You'll have to enable snapshots on your build, [see here](https://github.com/database-rider/database-rider#snapshots)

**Comment by rmpestano** [comment]
Thank you for your feedback, v`1.26.0` was just released containing this fix.
