### ISSUE TITLE
help: unable to set a working project with existing entities

### ISSUE THREAD

**Issue by phgachoud** [database-rider/database-rider#337]
Hi, I'm desperatly trying to make it work, dont know where to begin with. The logs tell it seems to work, but no data seems to be inserted into DB from the xml file. How can I debug the insert part from given xml file to method???!!!

Test class
-----

    package com.xpo.ltl.reweigh.agedprocessing.module.dao;

    import com.github.database.rider.core.DBUnitRule;
    import com.github.database.rider.core.api.dataset.DataSet;
    import com.github.database.rider.core.api.dataset.SeedStrategy;
    import com.github.database.rider.core.util.EntityManagerProvider;
    import com.xpo.ltl.api.exception.ServiceException;
    import org.apache.logging.log4j.LogManager;
    import org.apache.logging.log4j.Logger;
    import org.junit.Rule;
    import org.junit.jupiter.api.BeforeEach;
    import org.junit.jupiter.api.Test;
    import org.junit.runner.RunWith;
    import org.junit.runners.JUnit4;
    import org.mockito.Spy;

    import java.util.List;

    @RunWith(JUnit4.class)
    class RwgLogHeaderDaoTest {

        private static final Logger logger = LogManager.getLogger(RwgLogHeaderDaoTest.class);

        @Rule
        public EntityManagerProvider emProvider = EntityManagerProvider.instance("in-memory-persistence-unit-1");

        @Rule
        public DBUnitRule dbUnitRule = DBUnitRule.instance(emProvider.connection());

        @Test
        @DataSet(value = "datasets/LogHeaderManager_scenario1.xml",
                strategy = SeedStrategy.UPDATE,
                disableConstraints = true,
                cleanAfter = true,
                transactional = true)
        void findAllAgedHeaders() throws ServiceException {
            //emProvider = EntityManagerProvider.instance("in-memory-persistence-unit-1");
            //int maxDays = appContext.getAgedRecordAgeMax() + 1;//should not be duplified, a public method should be available into the dao for that
            List resultList = EntityManagerProvider.em().createQuery("FROM RwgLogHeader").getResultList();
            if (resultList.size() > 0){
                logger.info("Yeah!");
            }else{
                assert false: "NOT FOUND";
            };
        }
    }

Persistence.xml
-----

    <?xml version="1.0" encoding="UTF-8"?>
    <persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">

        <persistence-unit name="in-memory-persistence-unit-1" transaction-type="RESOURCE_LOCAL">
            <provider>org.hibernate.ejb.HibernatePersistence</provider>
    
            <class>....entity.RwgLogHeader</class>
            <class>....entity.RwgLogDetail</class>

            <properties>
    
    
    
                <property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect" />
                <property name="javax.persistence.jdbc.driver" value="org.h2.Driver" />
                <property name="javax.persistence.jdbc.url" value="jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=Oracle" />

                <property name="javax.persistence.jdbc.user" value="sa" />
                <property name="javax.persistence.jdbc.password" value="" />
                <property name="hibernate.hbm2ddl.auto" value="create-drop" />
                <property name="hibernate.show_sql" value="true" />

                <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
                <property name="eclipselink.logging.level" value="INFO"/>
                <property name="eclipselink.logging.level.sql" value="FINE"/>
                <property name="eclipselink.logging.parameters" value="false"/>
            </properties>

        </persistence-unit>

    </persistence>

xml file
----
    <?xml version="1.0" encoding="UTF-8"?>
    <dataset>
        <RWG_LOG_HEADER LOG_HEADER_ID="1"
                        PRO_NBR_TXT="0346555040"
                        ...
 PLT_PRO_IND="N" />
    ...

    </dataset>

POM
--------
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <groupId>...</groupId>
        <artifactId>...</artifactId>
        <version>1.0.0.0</version>
        <name>...</name>
        <packaging>jar</packaging>

        <parent>
            ...
        </parent>

        <properties>
            <junit.version>5.3.2</junit.version>
            <jdk.version>1.8</jdk.version>
            <hibernate.version>5.4.5.Final</hibernate.version>
            <hibernate.c3p0.version>5.4.5.Final</hibernate.c3p0.version>
            <maven.surefire.version>3.0.0-M4</maven.surefire.version>
        </properties>

        <dependencies>
        ...
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-core</artifactId>
                <version>${hibernate.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-c3p0</artifactId>
                <version>${hibernate.c3p0.version}</version>
            </dependency>
            <dependency>
                <groupId>javax.transaction</groupId>
                <artifactId>jta</artifactId>
                <version>1.1</version>
            </dependency>
            <dependency>
                <groupId>com.oracle.database.jdbc</groupId>
                <artifactId>ojdbc8</artifactId>
                <version>19.8.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>2.14.0</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>4.4</version>
            </dependency>

            
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>5.7.2</version>
            </dependency>
            
            <dependency>
                <groupId>com.github.database-rider</groupId>
                <artifactId>rider-core</artifactId>
                <version>1.25.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.github.database-rider</groupId>
                <artifactId>rider-junit5</artifactId>
                <version>1.25.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>1.4.200</version>
                <scope>test</scope>
            </dependency>
            

            <dependency>
                <scope>test</scope>
                <groupId>org.eclipse.persistence</groupId>
                <artifactId>eclipselink</artifactId>
                <version>3.0.1</version>
            </dependency>
    
    
    
    
    
    
    
            <dependency>
                <scope>test</scope>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-entitymanager</artifactId>
                <version>5.5.3.Final</version>
            </dependency>
        </dependencies>

        <build>
            <sourceDirectory>src/main/java</sourceDirectory>
            <testSourceDirectory>src/test/java</testSourceDirectory>
            <plugins>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven.surefire.version}</version>
                    
                    <configuration>
                        <enableAssertions>true</enableAssertions>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.0.0</version>
                    <executions>
                        <execution>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>add-source</goal>
                            </goals>
                            <configuration>
                                <sources>
                                    <source>src/generated/java</source>
                                </sources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.7.0</version>
                    <configuration>
                        <source>${jdk.version}</source>
                        <target>${jdk.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <executions>
                        ...
                    </executions>
                </plugin>
            </plugins>
        </build>
    </project>

**Comment by rmpestano** [comment]
Hi, I think you're mixing junit4 (junit rule) and junit5 implementation.

For junit rule to work you need to use junit4 `@Test` annotation but you're using junit5 test. 

If you want to keep using junit5 you have to use junit5 runner and dbrider extension (and provide the jdbc connection without junit rule), [see docs here](https://github.com/database-rider/database-rider#junit-5) and [example test here](https://github.com/database-rider/database-rider/blob/a7acac2c207346611e2e7231b5853b6d0efe353f/rider-junit5/src/test/java/com/github/database/rider/junit5/DBUnitJUnit5It.java#L21-L33).  


I hope it helps.

**Comment by phgachoud** [comment]
> Hi, I think you're mixing junit4 (junit rule) and junit5 implementation.
> 
> For junit rule to work you need to use junit4 `@Test` annotation but you're using junit5 test.
> 
> If you want to keep using junit5 you have to use junit5 runner and dbrider extension (and provide the jdbc connection without junit rule), [see docs here](https://github.com/database-rider/database-rider#junit-5) and [example test here](https://github.com/database-rider/database-rider/blob/a7acac2c207346611e2e7231b5853b6d0efe353f/rider-junit5/src/test/java/com/github/database/rider/junit5/DBUnitJUnit5It.java#L21-L33).
> 
> I hope it helps.

@rmpestano  Thank you very much, afford make it run with junit5 with nativeQuery, but not its not working from criteriaQry, any idea why?

**Comment by phgachoud** [comment]
Found out, if you dont mix native query and criteriaQry into the same test method it works, found how but not why
