### ISSUE TITLE
Could not find script engine by name 'urn'

### ISSUE THREAD

**Issue by JapuDCret** [database-rider/database-rider#344]
In our tests we see multiple outputs like
```bash
Jul 27, 2021 10:15:08 AM com.github.database.rider.core.api.dataset.ScriptableTable getScriptEngine
WARNING: Could not find script engine by name 'urn'
```
The tests do however still work as expected tho.

Our tests persist data with column values like `urn:my-service:aggregate:14c2ad6a-8fde-4728-875a-c119e3437541` based on the [URN convention](https://en.wikipedia.org/wiki/Uniform_Resource_Name).

We are currently using
```xml
        <dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-junit5</artifactId>
            <version>1.21.0</version>
            <scope>test</scope>
        </dependency>
```

The issue might be related to Issue #58. However, we are using version `1.21.0` as stated above.

**Comment by rmpestano** [comment]
Hi @JapuDCret, if you update to `1.26.0` you should not see the warn anymore, please let me know.

**Comment by JapuDCret** [comment]
Thank you, this did indeed fix it!
