### ISSUE TITLE
Rider-Spring: Roll back inserted data set after every test

### ISSUE THREAD

**Issue by raphiz** [database-rider/database-rider#354]
Hi :wave: 

I tried to integrate database rider into an existing project. I started to write database rider tests with the same mindset I used to write tests for spring data, where spring rolls back the database after every test. However, this does not apply to data sets inserted by database rider. I would expect the behavior of `@DataSet(cleanAfter = true)` for every test to ensure, that tests do not influence each other.

I created a [simple sample application](https://github.com/raphiz/database-rider-example/) that illustrates this problem: When Running all tests of [`DemoApplicationTests`](https://github.com/raphiz/database-rider-example/blob/main/src/test/kotlin/com/example/demo/DemoApplicationTests.kt) consecutively, the last one will fail. Running just the failing test works fine, because it is not influenced by the test data sets from the previous test(s).

Is this the intended behavior or have I configured something incorrectly? If it is indeed intended behavior, is there a way to configure database rider to clean the database after every test by default, without having to set `cleanAfter = true`  on every `@DataSet`?

**Comment by raphiz** [comment]
@rmpestano thanks for your investigations! The suggested `alwaysCleanAfter` (and `cleanBefore`) seems to be the thing I was looking for. I'll gave it a a try and opened a PR: #355

**Comment by rmpestano** [comment]
Thank you for the PR @raphiz! 

v`1.30.0` should be released today with your contribution.


About my previous comment, the merging works like that so the primitive values are also "merged" when the strategy is `CLASS`, I just added a test for that.
