### ISSUE TITLE
H2: Cleaning up database is not working

### ISSUE THREAD

**Issue by shoutcool** [database-rider/database-rider#36]
i have one single test wich looks like follow:

```java
    @Test
    @DataSet(transactional=true, cleanBefore=true, cleanAfter=true)
    @ExpectedDataSet(value = "insertNewReportDefinition_expected.yml")
    public void insert_reportDefinion_success() {
    	ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());
    	
        ReportDefinition d = new ReportDefinition();
    	d.setBezeichnung("bezeichnung");
    	d.setFormatStandard("pdf");
    	d.setIstAktiv(true);
    	d.setTyp("typ");
    	
        testee.persist(d);
    }
```
my expected dataset looks like this:
```yml
LP_T_RPT_REPORTDEFINITION:
  - IDREPORT: 1
    BEZEICHNUNG: bezeichnung
    FORMATSTANDARD: pdf
    ISTAKTIV: 1
    TYP: typ  
```

If i execute the test once, everything works perfectly. But if i duplicate the whole test, the second one always fail.

```java
    @Test
    @DataSet(transactional=true, cleanBefore=true, cleanAfter=true)
    @ExpectedDataSet(value = "insertNewReportDefinition_expected.yml")
    public void insert_reportDefinion_success() {
    	ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());
    	
        ReportDefinition d = new ReportDefinition();
    	d.setBezeichnung("bezeichnung");
    	d.setFormatStandard("pdf");
    	d.setIstAktiv(true);
    	d.setTyp("typ");
    	
        testee.persist(d);
    }

    @Test
    @DataSet(transactional=true, cleanBefore=true, cleanAfter=true)
    @ExpectedDataSet(value = "insertNewReportDefinition_expected.yml")
    public void insert_reportDefinion_success2() {
    	ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());
    	
        ReportDefinition d = new ReportDefinition();
    	d.setBezeichnung("bezeichnung");
    	d.setFormatStandard("pdf");
    	d.setIstAktiv(true);
    	d.setTyp("typ");
    	
        testee.persist(d);
    }
```

the exception message is: 
junit.framework.ComparisonFailure: value (table=LP_T_RPT_REPORTDEFINITION, row=0, col=IDREPORT) expected:<[1]> but was:<[2]>

It seems like the persisted entry from the first test, is not cleaned. And after executing the second test case, the table contains two entries, instead of just one. The IDREPORT Column is defined as GenerationType.IDENTITY. 

I am using a **H2 in-memory-database** with the following properties defined:
```xml
<property name="javax.persistence.jdbc.url" value="jdbc:h2:mem:test;"/>
<property name="javax.persistence.jdbc.driver" value="org.h2.Driver"/>
<property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
<property name="eclipselink.logging.level" value="FINE" />
```

I tried all different combinations of CLEAN_INSERT, cleanBefore, cleanAfter, but the behaviour is always the same. Like this, my tests are not usable, because all tests are related to each other.

**Comment by shoutcool** [comment]
On the console output i see the following error, for every table defined in persitstence.xml:
```
Internal Exception: org.h2.jdbc.JdbcSQLException: Table "LP_T_RPT_REPORTDEFINITION" not found
Table "LP_T_RPT_REPORTDEFINITION" not found; SQL statement:
DROP TABLE lp_t_Rpt_ReportDefinition [42102-192]
Error Code: 42102
Call: DROP TABLE lp_t_Rpt_ReportDefinition
Query: DataModifyQuery(sql="DROP TABLE lp_t_Rpt_ReportDefinition")
```

Is it maybe related to the [#32](https://github.com/database-rider/database-rider/issues/32)?

**Comment by shoutcool** [comment]
I just checked it with the built-in H2 Webserver. While executing my tests i stopped and took a look at the database. Indeed the data from the first test is still there. 

On the Webserver i saw also, that the table names are all UPPERCASE. So the exception posted in previous comment is because of this. Do you guys agree that it's because of the CaseSensitive Issue with H2?

**Comment by rmpestano** [comment]
Hi @shoutcool,

can you try to declare an empty dataset with this content:

empty.yml
```
LP_T_RPT_REPORTDEFINITION:

```
and use it on your tests:

```
 @Test
    @DataSet(value="empty.yml", transactional=true, cleanBefore=true, cleanAfter=true)
    @ExpectedDataSet(value = "insertNewReportDefinition_expected.yml")
    public void insert_reportDefinion_success() {
    	ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());
    	
        ReportDefinition d = new ReportDefinition();
    	d.setBezeichnung("bezeichnung");
    	d.setFormatStandard("pdf");
    	d.setIstAktiv(true);
    	d.setTyp("typ");
    	
        testee.persist(d);
    }

    @Test
    @DataSet(value="empty.yml", transactional=true, cleanBefore=true, cleanAfter=true)
    @ExpectedDataSet(value = "insertNewReportDefinition_expected.yml")
    public void insert_reportDefinion_success2() {
    	ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());
    	
        ReportDefinition d = new ReportDefinition();
    	d.setBezeichnung("bezeichnung");
    	d.setFormatStandard("pdf");
    	d.setIstAktiv(true);
    	d.setTyp("typ");
    	
        testee.persist(d);
    }
```

**Comment by shoutcool** [comment]
Hi @rmpestano 

i just checked it, but the behaviour is still the same. 
I switched to derby in-memory database. I just made the changes at the persistence.xml, but i did not changed anything in my classes. Then everything worked as expected.

So it seems definitely to be a H2 related issue.

**Comment by rmpestano** [comment]
Hi @shoutcool,

Can you share a sample project? In dbrider tests we use hsqldb, have you tried with that? Also have you tried with dbrider 1.0.0? we have changed table name case sensitive mechanism in 1.1.0 and maybe It is affecting your setup.

Thank you

**Comment by shoutcool** [comment]
Hi @rmpestano 

I made a little demo project where you can reproduce the error. 
Just modify the persistence.xml (see my comments in the file). Then you will see if you run the tests with derby, they are successful. If you run them with h2 the tests fail.

[database-rider.zip](https://github.com/database-rider/database-rider/files/1185996/database-rider.zip)

**Comment by rmpestano** [comment]
Hi @shoutcool,

I think I've just found your issue. The problem is that in expected datasets you are comparing primary key (ID) and it is not reseted between tests hence the comparison failure:

```
junit.framework.ComparisonFailure: value (table=LP_T_RPT_REPORTDEFINITION, row=0, col=IDREPORT) 
Expected :1
Actual   :2
 <Click to see difference>

```

To fix it you can use regex for ID column in expected datasets:

```
LP_T_RPT_REPORTDEFINITION:
  - IDREPORT: "regex:\\d+"
    BEZEICHNUNG: bezeichnung
``` 

Here is an updated zip using H2:

[database-rider-test2.zip](https://github.com/database-rider/database-rider/files/1186081/database-rider-test2.zip)

Hope it works for you too.

**Comment by shoutcool** [comment]
Hi @rmpestano 

Are you sure, that the cause is only the resetting of the primary key? 
If you set a breakpoint at the second test and then take a look at the in memory-database (like i did once), then you will see that the whole entry from the first test is still there.

At the javadoc the following is mentioned for the "cleanBefore" attribute :  
_...Database_ Rider will try to _**delete database**_ before test..._  

Therefore i would mark this issue as a bug, because deleting the database should delete everything (even all constraints, indexes, sequences, e.g.)

Thank you for your workaround. But i think i will stay with derby. When i extacly know which ID i am expecting, i prefer to check it explicitely.

**Comment by rmpestano** [comment]
Hi,

I think it is working here, see image below:

![dbunit-count](https://user-images.githubusercontent.com/1592273/28776538-636c2f16-75cd-11e7-8b1e-b14517649d97.png)

Also try counting on each test to verify that:

```
@Test
	@DataSet(transactional = true, cleanBefore = true)
	@ExpectedDataSet(value = "insertNewReportDefinition_expected.yml")
	public void insert_reportDefinion_success() {
		long count = (Long) em().createQuery("select count(r) from ReportDefinition r").getSingleResult();
		assertEquals(0L,count);
		ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());

		ReportDefinition d = new ReportDefinition();
		d.setBezeichnung("bezeichnung");
		testee.persist(d);
	}

	@Test
	@DataSet(value = "updateNewReportDefinition_given.yml", transactional = true, cleanBefore = true)
	@ExpectedDataSet(value = "updateNewReportDefinition_expected.yml")
	public void update_reportDefinion_success() {
		long count = (Long) em().createQuery("select count(r) from ReportDefinition r").getSingleResult();
		assertEquals(1L,count);// one record is inserted by updateNewReportDefinition_given.yml
		ReportDefinitionDao testee = new ReportDefinitionDao(emProvider.getEm());

		ReportDefinition d = testee.findById(1);
		d.setBezeichnung("bezeichnung2");
	}
```

Here both tests are passing.
