### ISSUE TITLE
Spring @Transactional tests is broken in version 1.27

### ISSUE THREAD

**Issue by vkrauze** [database-rider/database-rider#365]
We'are using tests annotated with Spring @ Transactional to roll back database-rider data inserts after test:
```java
@RunWith(SpringJUnit4ClassRunner.class)    
@DBRider    
@DBUnit    
@Transactional    
public class MyTest {
```

With database-rider 1.26 it works fine.

After updating database-rider to 1.27 our tests broke. We have found a cause in database-rider DataSetExecutorImpl source:
```java
    @Override    
    public void createDataSet(DataSetConfig dataSetConfig) {    
        printDBUnitConfiguration();    
        if (dataSetConfig != null) {   
            IDataSet resultingDataSet = null;   
            try {   
                getRiderDataSource().setConnectionAutoCommit(true);
```

setConnectionAutoCommit(true) here breaks transactional behaviour of our tests.

Maybe this setConnectionAutoCommit operator can be made optional so that it can be switched off by some new parameter?

**Comment by jpbassinello** [comment]
I am having the same issue

**Comment by rmpestano** [comment]
Hey guys, I'll have a look when time permits

**Comment by rmpestano** [comment]
Thank you all for the help!
