### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by alxxyz** [database-rider/database-rider#369]
We are now migrating a lot of our microservices from PostgreSQL to MongoDB and will be really great to have support also for this database.

**Comment by rmpestano** [comment]
Hi @alxxyz, unfortunately that's not possible because we use dbunit and jdbc under the hoods which are not compatible with Mongo.

There's a tool which is quite similar to dbrider for nosql databases called `NoSQLUnit`, have you checked that?  https://github.com/lordofthejars/nosql-unit
