### ISSUE TITLE
disableConstraints=true for H2 executes non-H2 SQL Statement

### ISSUE THREAD

**Issue by bergerst** [database-rider/database-rider#375]
I am using h2 version 2.0.202 and DBRider 1.32.0.

When I use `@DataSet(value = "datasets/mydataset.yml", disableConstraints = true)`, this line will run a `SET foreign_key_checks=0` statement, which is not supported by H2.

Instead, the command should be `SET REFERENTIAL_INTEGRITY FALSE` per documentation: https://www.h2database.com/html/commands.html#set_referential_integrity

So currently, I cannot use DataSets which would violate foreign key constraints.

**Comment by soriajuan** [comment]
@bergerst This error also have a side effect on cleaning tables before tests. It doesn't. At most, log a warning "Could not clean database before test.". Oh... and this is regardless of global or dataset cleanBefore configuration.

**Comment by rmpestano** [comment]
Hey folks, would you open a PR to incorporate that fix?

Thank you for the feedback!

**Comment by bergerst** [comment]
@rmpestano See #376

**Comment by rmpestano** [comment]
Yes, just saw and came back here to comment, not sure how I missed that ;(. I'll try to release the fix today, thank you!

**Comment by rmpestano** [comment]
@bergerst, do you know if we're going to break users using H2 1.x? I want to make it clear in the release notes as well as increment the minor versions instead the patch

**Comment by bergerst** [comment]
According to https://web.archive.org/web/20190517154357/https://www.h2database.com/html/commands.html it looks like the command already existed for version 1.4.199.

I think `SET REFERENTIAL_INTEGRITY` exists since the beginning of H2 and `SET foreign_key_checks` was never officially supported. Now the support has been fully dropped.

**Comment by rmpestano** [comment]
Got it, thank you!

**Comment by Matrino** [comment]
Hey, after upgrade still not functioning, yet another error comes.

Should we in generall wair for the version, where h2 v.2 is supported or should it already be supported?

Thanks a lot in advance.

`WARN` com.github.database.rider.core.dataset.DataSetExecutorImpl - Could not clean database before test.
java.lang.RuntimeException: Could not execute statements:This feature is not supported: "META"
Feature not supported: "META"; SQL statement:
DELETE FROM INFORMATION_SCHEMA.INDEX_COLUMNS where 1=1 [50100-202]``

**Comment by bergerst** [comment]
In my projects, we haven't encountered any errors after upgrading.

@Matrino It's probably not related to disableConstraints but another DBRider feature. Maybe it's caused by your own project files? I can't find anything with `INDEX_COLUMNS` in this project.

It's probably best if you create a new bug report for your issue since it doesn't match my reported one.

**Comment by rmpestano** [comment]
> It's probably best if you create a new bug report for your issue since it doesn't match my reported one.

Yea, can you create a new issue @Matrino? also it would be nice if we could reproduce in one of the DBRider samples.

Thanks for the feedback!
