### ISSUE TITLE
Multiple schemas using YML file

### ISSUE THREAD

**Issue by jrmatos** [database-rider/database-rider#39]
Hi guys,

I need to work with a set of tables but some of them are in another database schema. I have already set the property DatabaseConfig.FEATURE_QUALIFIED_TABLE_NAMES to true, but I can't still use my tables with the syntax SCHEMA.TABLE_NAME (eg: school.student:). Is there a way to do this? I'm using the 1.0.0 version.

Thanks.

**Comment by rmpestano** [comment]
Hi, in flayway example datasets we are using schema, see here: https://github.com/database-rider/database-rider/blob/master/rider-examples/jOOQ-DBUnit-flyway-example/src/test/resources/datasets/authors.yml

Now about multiple schemas on the same test it isnt suppoted yet, ser issue #14
