### ISSUE TITLE
Usage with Spock

### ISSUE THREAD

**Issue by skylvsme** [database-rider/database-rider#460]
In my application I'm using Spock with Spring Boot (building by Gradle if it's important) and want to introduce Database Sets into my tests. I tried to use Database Rider with runtime H2 in my Spring context, following [this example](https://github.com/rmpestano/spring-events/blob/master/src/test/java/com/sambrannen/spring/events/repository/EventRepositoryTests.java), but it seems not to be working.

My configuration: 

build.gradle
```gradle
        [another dependencies]
	testRuntimeOnly 'com.h2database:h2:2.1.212'

	testImplementation "org.spockframework:spock-core:2.1-groovy-3.0"
	testImplementation 'org.spockframework:spock-spring:2.1-groovy-3.0'
	testImplementation("com.github.database-rider:rider-junit5:1.32.3") {
		exclude group: 'org.slf4j'
	}
}

tasks.named('test') {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
}
```

UserServiceTest.groovy
```groovy
import com.github.database.rider.core.api.dataset.DataSet
import com.github.database.rider.junit5.api.DBRider
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import myproject.UserRepository
import spock.lang.Specification

@DBRider
@SpringBootTest
@ActiveProfiles("test")
@DataSet("datasets/userTest.yaml")
class UserServiceTest extends Specification {

    @Autowired
    UserRepository repository

    def "create user"() {
        expect:
        repository.findAll().size() > 0
    }

}
```

application-test.yaml
```yaml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
```

userTest.yaml
```yaml
user:
  - uid: "qwerty_uidrr"
```

My user model
```java
@Getter
@Setter
@Entity
@Table(name = "users")
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    private String uid;

}
```

Result of test
```
Condition not satisfied:

repository.findAll().size() > 0
|          |         |      |
|          []        0      false
```

**Comment by rmpestano** [comment]
Hi @skylvsme, 

There is no Spock integration as of now, what you could do is to use [RiderDSL](https://github.com/database-rider/database-rider#riderdsl) instead of `@DataSet`, see some [examples here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/dsl/RiderDSLIt.java#L31).

Can you share your project so I can have a look? Maybe the Spock integration is not so hard

**Comment by skylvsme** [comment]
Hi @rmpestano, thanks for appointment! But how can I inject database connection from Spring to RiderDSL?
