### ISSUE TITLE
`executorId` and multiple database tests

### ISSUE THREAD

**Issue by lanxx019** [database-rider/database-rider#47]
Currently, if we want to use `DbUnitRule` with multiple databases in different tests, we have to:

- Add `executorId` on the `DbUnitRule.instance` call.
- Add `executorId` on every `DataSet` annotation.

I am not sure what is the correct way of doing this. But this seems very excessive. E.g. we already initialize the `DbUnitRule` instance as a `TestRule` per class with a `executorId`, why do we still need to repeat the `executorId` on every single `DataSet` annotation? Can we infer the `executorId` from `DbUnitRule` instance itself? IMHO, we probably should not mix more than one database connection in a single test.

As far as I can tell, [these lines](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/DBUnitRule.java#L86-L89) can be improved:

- Why do we need these three line in the first place? Don't we have `executor` as an instance on the outer class already?
- If we indeed need these three lines to be able to query the `executor` instance based on the passed in `executorId` from `@DataSet` annotation, I think we should change [this line](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/DBUnitRule.java#L86) since by default `executorNameIsProvided` is always `true` with the `executorId` set to `default`. This leads to unexpected NPE if all the `DbUnitRule` instance are created with `executorId` set to some other values.
- Can we do something like:
  - Use outer `executor` by default
  - If `DataSet` pass a `executorId` other than `default`, then query that `executor`?

**Comment by rmpestano** [comment]
Hi, 

"IMHO, we probably should not mix more than one database connection in a single test."

That's the real problem, If we do not support multiple dbs on the same test then things would be much simpler as you noticed.

Having said that I think we could have a property to disable(or enable) multiple dbs support on same test. What do you think?

Would you like to contribute that?

**Comment by lanxx019** [comment]
If that is a design choice, what do you think about setting the default value of `executorId` in `DataSet` to `""`. This way, we can simply skip the `if` check on `executorNameIsProvided` and the attached `executor` would be used.

I do not mind doing the PR.

**Comment by rmpestano** [comment]
> ...what do you think about setting the default value of executorId in DataSet to "" 

I got it now, just did that. 

thank you.

**Comment by lanxx019** [comment]
Perfect, thank you!
