### ISSUE TITLE
Dependencies with vulnerabilities

### ISSUE THREAD

**Issue by JCrAg** [database-rider/database-rider#478]
Hi guys. 
I've detected some dependencies you are using which are vulnerable. 
One of them is commons-collections (now is recomended to use commons-collections4), which is used by DBUnit 2.7.0 too. If this one would be updated i think DBUnit could be upgraded to its actual latest version 2.7.3.
I would like to know if is in your scope to fix them.

**Comment by dtorrensf** [comment]
+1

**Comment by rmpestano** [comment]
Hi @JCrAg, yes I think we can upgrade them, would you like to provide a PR?

Thanks for the heads up 👍

**Comment by rmpestano** [comment]
Hi again @JCrAg, I could only find commons-collections being used in one of the sample projects:
<img width="672" alt="Screen Shot 2022-07-31 at 16 34 44" src="https://user-images.githubusercontent.com/1592273/182031372-eb0a54f8-aef8-4a1b-bdbd-6fccb7fa4a6b.png"> 

So dbrider is not bringing into to the library. I'm upgrading dbunit to `2.7.3` as pr suggestion, thank you!

**Comment by rmpestano** [comment]
Alright, now I got it, dbunit itself is bringing it so the upgrade should fix
