### ISSUE TITLE
Support for jakarta persistence

### ISSUE THREAD

**Issue by mkwapisz** [database-rider/database-rider#496]
Is there any version of dbrider for Jakarta standard.
After the migration to Hibernate Jakarta I get the following message:
```
com.github.database.rider.junit5.DBUnitExtension executeDataSetForCallback
WARNING: Could not find dataset annotation from callback method: public void pl.kurs.model.clients.ClientJpaTest.clean()
com.github.database.rider.junit5.DBUnitExtension executeExpectedDataSetForCallback
WARNING: Could not find expectedDataSet annotation annotation from callback method: public void pl.kurs.model.clients.ClientJpaTest.clean()
java.lang.NoClassDefFoundError: javax/persistence/Persistence
```

The EntityManagerProvider is dependent to javax namespace, not jakarta.

**Comment by rmpestano** [comment]
Hi @mkwapisz, unfortunately we don't. Does it work if you add  `javax.persistence:persistence-api:1.0.2` dependency to your test classpath?

**Comment by mkwapisz** [comment]
Thanks for the reply. EntityManagerProvider is a very convenient way to get connection regardless JPA implementation used. I changed ConnectionHolder to
`private ConnectionHolder connectionHolder = () -> ((SessionImpl) em.unwrap(Session.class)).connection();`
which is absolutely Hibernate specific but it seems to work.

**Comment by mkwapisz** [comment]
I just copied two files to my project EntityManagerProvider and PropertyResolutionUtil, added prefix Jakarta to their names, replaced javax with jakarta and everything works.

**Comment by rmpestano** [comment]
Hi @mkwapisz, do you think we can support both Jakarta and javax packages? Otherwise we'll have to distribute 2 binaries of dbrider. Let me know if you have any idea

**Comment by DeMol-EE** [comment]
My two cents is that it may be worth supporting two binaries, at least for a while. Perhaps it’s possible to support both simultaneously but I think most libraries/frameworks decided to forking their release (Hibernate, mapstruct...). It’s an unfortunate side effect of the Jakarta EE transition but I believe unavoidable to move to Jakarta eventually.
I know that it’s an issue for our development team and we’re considering forking dbrider ourselves to able to continue to use it. @mkwapisz could you elaborate on what you did? You were able to continue using the javax release of dbrider in a jakarta application? FYI, we’re using dbrider with Quarkus.

**Comment by rmpestano** [comment]
Hi @DeMol-EE, we have a quarkus sample in the rider-examples module, can you check why that one works? Is it because of an older version of quarkus?

If it is a blocker for users we can definitely release 2 binaries

**Comment by DeMol-EE** [comment]
Hi @rmpestano. To clarify: we are currently using dbrider with Quarkus 2.16.4.Final without issue. Soon, however, they will release Quarkus 3.0.0, which is based on Jakarta EE 10 instead of 9.1, which means the namespace for cdi imports will change from javax to jakarta. We’ve already attempted to migrate our Quarkus project to the 3.0.0.Beta1 release (in order to have access to Hibernate 6 / JPA 3), but in doing so we can no longer run our tests that use dbrider. I know we’re maybe a bit early with migrating, but I did find that other dependencies we have all seem to have a jakarta-capable version already (mapstruct, ph-schematron...). Quarkus 3 may be brand new, but Jakarta EE 10 has been around for a few months now...

**Comment by Clockwerk300** [comment]
Why do you not try em.unwrap(Connection.class)? It just need to be inside a transaction I think.

**Comment by sjaakd** [comment]
First of all, this is a really nice way to test your DB interaction. Thanks for that.

However, I'm facing the same problem here. We went to Quarkus 3.0, actually with the reason that it supports Hibernate 6.2.1. Main advantage here is that we can use H2 with spatial extensions out of the box in combination with Database Rider / Rider-CDI. 

Only, a bit unfortunate, to discover (after a day of refactoring) that Rider-CDI is also dependent on Hibernate 4.3.5 and javax. I really would like to have additional binaries for Jakarta EE 10. Or perhaps someone figured out how to integrate this with Quarkus 3.0?

**Comment by rmpestano** [comment]
Hey folks, I'll start working on this one later this week and the idea is to have a dedicated artifact for jakarta. Hopefully we'll have a release by the end of the week. I'll keep you posted, cheers!

**Comment by rmpestano** [comment]
Hi folks, no much progress here, I've tried to upgrade the quarkus-dbunit-sample (see this db-rider [branch](https://github.com/database-rider/database-rider/tree/quarkus-3/rider-examples/quarkus-dbunit-sample)) but whenever I run the tests I get `No entities ware found`:

```
java.lang.IllegalStateException: No entities were found. Did you forget to annotate your Panache Entity classes with '@Entity'?

	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.getEntityManager(AbstractJpaOperations.java:67)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.getEntityManager(AbstractJpaOperations.java:53)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.findAll(AbstractJpaOperations.java:294)
	at com.github.quarkus.sample.domain.Book.findAll(Book.java)
	at com.github.quarkus.sample.QuarkusDBUnitTest.shouldFindAllBooks(QuarkusDBUnitTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

It works when I switch to quarkus 2.9.x, does anyone has any clue?

**Comment by matjazs** [comment]
I've only briefly examined the sample and noticed that the Book entity still has the javax annotation in the quarkus-3 branch. The migration steps are documented [here](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#jpa--hibernate-orm).

**Comment by DeMol-EE** [comment]
@rmpestano I took a look and saw a few things that looked a bit off. I wanted to try to fix them and finally got the tests to pass:

<img width="594" alt="image" src="https://github.com/database-rider/database-rider/assets/1039594/54ded1b0-ea3f-4609-9e41-0b5d29837bd2">

However, I’m afraid that I have made more changes than necessary. Therefore I think it’s best that I give you my ideas and let you make the changes yourself. Things I took into consideration:

* pom files that still have dependencies on javax specs, directly or transitively:
  * hibernate and eclipselink still pulling in persistence 2 (bumping to > 6.0.0 and 4.0.0 respectively (I used 6.2.3.Final and 4.0.1) should transitively pull in persistence 3)
  * javax.enterprise:cdi-api:2.0 -> jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1
  * javax:javaee-api:7.0 -> jakarta.platform:jakarta.jakartaee-api:10.0.0
  * javax.servlet:javax.servlet-api:3.1.0 -> jakarta.servlet:jakarta.servlet-api:6.0.0
* javax.<...> imports -> replace javax with jakarta
  * this is true for practically all javax. imports except javax.sql.DataSource
* javax.persistence properties -> replace javax with jakarta
* Hibernate 6 breaking changes (mostly in rider-core, util package, getting a connection via `connection()` no longer exists, but perhaps you can do it via `getJdbcConnectionAccess().obtainConnection()`)

I made changes in many places but it is my guess that it should be doable with only changes to rider-parent, rider-core, rider-cdi and the quarkus sample.

**Comment by rmpestano** [comment]
You guys are amazing, thank you! Let you know when we have something to test

**Comment by rmpestano** [comment]
Hey folks, can you guys try using this rider-cdi version on your quarkus 3 tests?

```
<dependency>
      <groupId>com.github.database-rider</groupId>
      <artifactId>rider-cdi</artifactId>
      <version>1.37.2-SNAPSHOT</version>
      <scope>test</scope>
      <classifier>jakarta</classifier>
      <exclusions>
        <exclusion>
          <artifactId>stax-api</artifactId>
          <groupId>stax</groupId>
        </exclusion>
      </exclusions>
    </dependency>

<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by DeMol-EE** [comment]
Thanks for the effort @rmpestano. It’s not quite working yet. Here are my observations:

* database-rider is still pulling in javax.enterprise:cdi-api:2.0
<img width="563" alt="image" src="https://github.com/database-rider/database-rider/assets/1039594/88ea23c4-6a17-4796-b213-b598e86e7928">

* dbunit.yml is giving issues regarding a custom datatypeFactory, which used to work fine before (we extend PostgresqlDataTypeFactory to deal with jsonb columns). It seems like the yml processor is not happy with `!!`:

dbunit.yml:
```
caseInsensitiveStrategy: LOWERCASE
alwaysCleanBefore: true
disableSequenceFiltering: true
properties:
  schema: public
  datatypeFactory: !!foo.bar.baz.testutils.dbunit.DataTypeFactory { }
```

error:
```
Global tag is not allowed: tag:yaml.org,2002:foo.bar.baz.testutils.dbunit.DataTypeFactory
 in 'reader', line 6, column 20:
      datatypeFactory: !!foo.bar.baz.testutils ... 
```

**Comment by DeMol-EE** [comment]
Further note: the issue seems to be with snakeyaml. Excluding it and manually re-adding the dependency on an older version (e.g. 1.33) solves the issue. Maybe a new security setting that needs to be set? 1.33 -> 2.0 seems like a major release, after all.

**Comment by rmpestano** [comment]
Hey guys, thanks for testing! I'll downgrade the snakeyaml.

I'm not sure how to automate the jakarta classifier release so I'll probably release it manually and figure it out later.

**Comment by rmpestano** [comment]
Just release rider `1.38.1`  which should fix this issue:

```
  <dependency>
      <groupId>com.github.database-rider</groupId>
      <artifactId>rider-cdi</artifactId>
      <version>1.38.1</version>
      <scope>test</scope>
      <classifier>jakarta</classifier>
      <exclusions>
        <exclusion>
          <artifactId>stax-api</artifactId>
          <groupId>stax</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

Thank you all for the help and please re-open this issue if you still face any issues.

**Comment by Christoph-W** [comment]
Jakarta is spreading around:
- Spring Boot 3.x is replacing javax with jakarta, while 2.7.x is running our of support.
- Spring Framework 6.0 sets baseline to jakarta
- Hibernate 6.x moved from javax to jakarta

We use rider-junit5 and rider-spring, both serve imports to javax.persistence.* or require rider-core, which uses javax.
Would it be possible to provide a jakarta variant like it was done for cdi?
Or would it be easier in the long run to update some deprecated dependencies to fully replace the javax requirements?

**Comment by rmpestano** [comment]
Hi @Christoph-W, we have a dedicated issue for that, [see here](https://github.com/database-rider/database-rider/issues/561). Please share your input there.

Also, can you help by providing a sample app which reproduces the error, that helps a lot in getting support for fixing an issue
