### ISSUE TITLE
FlatXmlDataSetLoader doesn't allow reading the dtd from the same folder as the xml

### ISSUE THREAD

**Issue by linux-china** [database-rider/database-rider#50]
Load xml with DTD failed. code as following 
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "test.dtd">
<dataset>
    <PEOPLE id="1" nick="leijuan"/>
</dataset>
```

I think  same problem here: https://github.com/springtestdbunit/spring-test-dbunit/issues/57

**Comment by rmpestano** [comment]
Hi, van you try with 1.2.4-SNAPSHOT? You Will nerd tô declare snapshot repo:https://github.com/database-rider/database-rider#12-snapshots

**Comment by linux-china** [comment]
@rmpestano   yes, 1.2.4-SNAPSHOT is ok. thanks.  Any plan to release a new version?

**Comment by rmpestano** [comment]
> Any plan to release a new version?

It was just released, thank you for your feedback!

**Comment by ahrytsiuk** [comment]
Hello @rmpestano, seems this issue is back starting from version `1.15.0`.
Should this issue be reopened or create a new one is preferable?

**Comment by rmpestano** [comment]
Hi @ahrytsiuk, I'll reopen this one

**Comment by rmpestano** [comment]
Hi again @ahrytsiuk, I completely forgot about this issue, can you create a new one and add some context/sample reproducer?
