### ISSUE TITLE
Unable to insert records with sequence

### ISSUE THREAD

**Issue by achyutha526** [database-rider/database-rider#51]
Hi,

I am unable to insert the below data using database rider. The primary key EMAIL_ADDR_ID is DB sequence.
```
DB.EMAIL_ADDRESS:
  - EMAIL_ADDR_ID: email_addr_seq.nextval
    ADDR_STATUS_CD: "INVL"
```

Error:
Caused by: org.dbunit.dataset.datatype.TypeCastException: Unable to typecast value <email_addr_seq.nextval> of type <java.lang.String> to DECIMAL
	at org.dbunit.dataset.datatype.NumberDataType.typeCast(NumberDataType.java:83)
	at org.dbunit.dataset.datatype.NumberDataType.setSqlValue(NumberDataType.java:108)
	at org.dbunit.database.statement.SimplePreparedStatement.addValue(SimplePreparedStatement.java:73)
	at org.dbunit.operation.RefreshOperation$RowOperation.execute(RefreshOperation.java:189)

**Comment by rmpestano** [comment]
Hi @achyutha526,

you can't reference a sequence inside a dataset. What you want to achieve with that?  a random number can be generated with scripts, [see here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/resources/datasets/yml/random-replacements.yml#L2).

**Comment by achyutha526** [comment]
Thanks, @rmpestano for the details.  We want to use database rider to populate the records into the table EMAIL_ADDRESS. The primary key is EMAIL_ADDR_ID is the primary key and it is configured as a sequence. We don't want to break the sequence as application also populates the data into this table while executing the tests.

**Comment by kaustubhshete** [comment]
Hi @rmpestano, Does database rider have the capability to use oracle sequencer i.e. in this example email_addr_seq.nextval to generate the next sequence ?

**Comment by rmpestano** [comment]
Hi guys,

Datasets hold static data, the only exception are [scriptable datasets](https://database-rider.github.io/database-rider/1.2.4/documentation.html#Dynamic-data-using-scritable-datasets).

Why is the ID or sequence number important for your tests? are you making assertions on it?

If yes you can use fixed numbers and also make sure to clear sequences (you can [execute scripts ](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/ScriptsIt.java#L48)before tests for example) to not create conflicts with seq numbers.

**Comment by achyutha526** [comment]
@rmpestano thank you for the info. we are using scripted dataset approach.
