### ISSUE TITLE
Inconsistent logging across framework

### ISSUE THREAD

**Issue by jowko** [database-rider/database-rider#519]
Some classes in this framework use `java.util.logging.Logger` for logger creation and others use `org.slf4j.LoggerFactory`.
We configured log4j2 with slf4j in our tests for logging and we see that some logs are ignoring our log4j settings and log in their own format. Examples: https://github.com/database-rider/database-rider/search?q=java.util.logging.Logger

I think that logging should be unified, preferably to slfj4.

**Comment by rmpestano** [comment]
Hi @jowko, can you give a try on v`1.35.2-SNAPSHOT` to verify the problem was fixed?  You'll need to enable [rider snapshots](https://github.com/database-rider/database-rider#snapshots).

**Comment by jowko** [comment]
@rmpestano Hello. I checked this on 1.35.2-SNAPSHOT and it looks that it is working correctly.
When I set ERROR log level in log4j.properties I did not saw any logs from database rider.
When I set INFO logging level, it looks that logging is unified.
Thanks for the changes.
Do we know when the version 1.35.2 will be released?

**Comment by rmpestano** [comment]
Hey @jowko, 1.36.0 is being released today, thank you!
