### ISSUE TITLE
It's not possible to use dbunit.yaml (instead of yml)

### ISSUE THREAD

**Issue by tiagomistral** [database-rider/database-rider#548]
This is just a minor issue but it's not possible to use the file dbunit with .yaml extension since the code only looks for dbunit.yml .

This is not a problem with this library itself, but it would be an asset if the existence of the file with both extensions was verified.

As the helm chart checks for the existence of yaml files with this extension, I can't have a pattern in my project.

Thanks in advance

**Comment by rmpestano** [comment]
Hey @tiagomistral, would you or anyone like to contribute and fix that with a PR?

Thank you for the feedback.

**Comment by tiagomistral** [comment]
Yes sure :D

Do I had permissions to create a PR? Can you point some guide how to do it?

**Comment by rmpestano** [comment]
> Yes sure :D
> 
> Do I had permissions to create a PR? Can you point some guide how to do it?

Hey Tiago, yes you should be able to fork the project, push the changes to your branch and open a PR.

On top of my head [this](https://github.com/database-rider/database-rider/blob/bfeaaaf422c509e83a144c3e6c14f6a561494b89/rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java#L117) is the only place where we read that file. 

If you make that change, just add a [test here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java) for the new suffix should be enough

Let me know if you need any help

**Comment by tiagomistral** [comment]
I think I create the PR correctly :D

Let me know if something else is needed from my side.

With this change we find some file with name 'dbunit' without the extension and use the first valid (at least I hope so)

**Comment by tiagomistral** [comment]
Hello @rmpestano 

Can you re-run the build? I fix the issues (I hope) :P

**Comment by tiagomistral** [comment]
I didn't find the comment @rmpestano :'D

**Comment by rmpestano** [comment]
Check the "conversation" tab on the [PR here ](https://github.com/database-rider/database-rider/pull/555)

**Comment by tiagomistral** [comment]
I don't see any comment :P

![image](https://user-images.githubusercontent.com/9108922/235157826-8789d4ce-67a6-4aaf-a49e-3ef2a8dea756.png)

**Comment by rmpestano** [comment]
@tiagomistral, I think we should enforce the format (yaml/yml), WDYT? 
<img width="810" alt="Screenshot 2023-04-30 at 08 20 26" src="https://user-images.githubusercontent.com/1592273/235338984-bc74adfd-29eb-4aff-b84e-dc0cea003f4d.png">

**Comment by tiagomistral** [comment]
My idea was more I'm going to use the first file started by "dbunit" that is valid. But I accept the suggestion :)

Can you validate?

**Comment by tiagomistral** [comment]
I think on that, but then we will allow the usage of 'dbunit.potatos.yaml' file, right?   :P

**Comment by rmpestano** [comment]
True that, let's keep it strict as your last changes, just check my last comment, in case you still can't see PR comments, here it is:
![Screenshot_20230502-175925](https://user-images.githubusercontent.com/1592273/235721114-e83c5291-ff2c-4394-af0d-ed6c567c97db.jpg)

**Comment by tiagomistral** [comment]
I can't see your comments :/ For some reason they are "pending"

I change the code accordingly ;)

**Comment by rmpestano** [comment]
Thanks a lot @tiagomistral, I'll try to release 1.37.0 tomorrow. Cheers!

**Comment by vladimirfx** [comment]
1.37.0 core - config not found not `dbunit.yml` nor `dbunit.yaml`. Files not listed by call `Thread.currentThread().getContextClassLoader().getResourceAsStream("")`. In same time direct call `Thread.currentThread().getContextClassLoader().getResourceAsStream("dbunit.yaml")` is returning file content.

Env: Java 17, Gradle 8.1.1, Quarkus 3.0.2 (using `@QuarkusTest`)

**Comment by rmpestano** [comment]
Hey @vladimirfx, thanks for the heads up. I'll have a look

**Comment by rmpestano** [comment]
Hi again @vladimirfx, I could not reproduce it on our quarkus [sample app](https://github.com/database-rider/database-rider/blob/master/rider-examples/quarkus-dbunit-sample/src/test/java/com/github/quarkus/sample/QuarkusDBUnitTest.java). Besides using version 3.x, do you see any other difference on your test setup? 

It would be nice if you could share a sample project that reproduces the issue

**Comment by rmpestano** [comment]
I've changed the dbunit config loading a bit, can you try again with `1.37.1-SNAPSHOT` @vladimirfx? you'll have to [enable snapshots](https://github.com/database-rider/database-rider#15-snapshots) on your build system. Let me know how it goes so we can release the fix.

Thanks for the feedback!

**Comment by vladimirfx** [comment]
> I've changed the dbunit config loading a bit, can you try again with `1.37.1-SNAPSHOT` @vladimirfx? you'll have to [enable snapshots](https://github.com/database-rider/database-rider#15-snapshots) on your build system. Let me know how it goes so we can release the fix.
> 
> Thanks for the feedback!

Thank you. I will check snapshot tomorrow.

**Comment by vladimirfx** [comment]
> I've changed the dbunit config loading a bit, can you try again with `1.37.1-SNAPSHOT` @vladimirfx? you'll have to [enable snapshots](https://github.com/database-rider/database-rider#15-snapshots) on your build system. Let me know how it goes so we can release the fix.
> 
> Thanks for the feedback!

`1.37.1-SNAPSHOT` - works, either `dbunit.yaml` or `dbunit.yml`. Thank you!

**Comment by rmpestano** [comment]
Thanks for checking, `1.37.1` should be on central in the next hours. Cheers!
