### ISSUE TITLE
Make rider-core compatible with jakarta persistence

### ISSUE THREAD

**Issue by HongHanh9527** [database-rider/database-rider#561]
Hi sir, my java project is using database rider library provided by you. The problem we have is: EntityManagerProvider.em(puName);
is returning javax.persistence.EntityManager but we need a jakarta.persistence.EntityManager ( jakarta.jakartaee-api 10.0.0 ). It's in EntityManagerProvider.class inside your library (private EntityManager em;). Hope you reply soon!!! Thank !!!
![rider2](https://github.com/database-rider/database-rider/assets/76577878/dbcd4fad-6034-4007-a0ab-949bf29a25c9)

**Comment by rmpestano** [comment]
Hey @HongHanh9527, right now `rider-core` module is not compatible with jakarta, only rider-cd but I hope to get it jakarta compatible soon,  meanwhile, I suggest having your own implementation of EntityManagerProvider.

**Comment by HongHanh9527** [comment]
Yes I really appreciate your kind feedback, maybe I will develop the module
for my own project also I hope you will also implement the rider-core
module based on jakarta. Thank you very much !!!

Vào Th 2, 10 thg 7, 2023 vào lúc 03:33 Rafael Pestano <
***@***.***> đã viết:

**Comment by sjaakd** [comment]
I am trying to use Rider-CDI icw jakarta and Quarkus 3.0. However, I ran into the following problem when including:


```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/derksenjpam/Development/source/uitgifteloket/uitgifteloket-v2/app-portal/src/test/java/nl/bro/microservices/dlp/resources/CptGdwDataSet.java:[35,13] cannot access javax.persistence.metamodel.Attribute
  class file for javax.persistence.metamodel.Attribute not found
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

This is my maven dependency:

```
        <dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-cdi</artifactId>
            <version>1.38.1</version>
            <scope>test</scope>
            <classifier>jakarta</classifier>
            <exclusions>
                <exclusion>
                    <artifactId>stax-api</artifactId>
                    <groupId>stax</groupId>
                </exclusion>
            </exclusions>
        </dependency>

````
and the offending test data class

```java
import com.github.database.rider.core.api.dataset.DataSetProvider;
import com.github.database.rider.core.dataset.builder.DataSetBuilder;
import org.dbunit.dataset.IDataSet;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;

public class CptGdwDataSet implements DataSetProvider {

    // CHECKSTYLE:OFF

    GeometryFactory geometryFactory = new GeometryFactory();
    // CHECKSTYLE:ON

    @Override
    public IDataSet provide() {

        DataSetBuilder builder = new DataSetBuilder();
        return builder
            .table( "GDW_LKS_CPT_RD" )
            .row()
            .column( "OBJECT_ID", "12345" )
            .column( "BRO_ID", "CPT000000000001" )
            .column( "DELIVERY_ACCOUNTABLE_PARTY", "11112222" )
            .column( "GEOMETRY", createRdPoint() )
            .table( "LKS_BRO_ORGANISATION" )
            .row()
            .column( "COC", "11112222" )
            .column( "COC_NAME", "TNO" )
            .build();
    }

    private Geometry createRdPoint() {
        Coordinate coordinate = new Coordinate();
        coordinate.x = 155000.543;
        coordinate.y = 463000.220;
        Geometry point = geometryFactory.createPoint( coordinate );
        point.setSRID( 28992 );
        return point;
    }
}
```

Is this related to this issue?

Next (and I should probably write a separate feature request), hibernate 6 includes spatial queries. I'm testing with H2 DB as a light-weight (unit) test DB (Oracle in production).This is why I use a java class as test set iso an yaml file. I reckon there's no support yet for spatial datatypes in the H2 set, or do I miss something?

**Comment by HongHanh9527** [comment]
Hi, I'm sorry about your problem. Actually, I'm just another Data-Rider library user. I'm not sure about your problem. My problem was related to a library conflict when upgrading from javax to jakarta ee : while all of our libraries upgraded to jakarta, Data-Rider still uses javax. This caused our data tests to not work. As far as I know this is the mail key member in the Data-Rider project: ***@***.*** (you can contact him directly). Hope you get your problem resolved soon. Good luck !!! Sent from Mail for Windows From: Sjaak DerksenSent: Thursday, August 24, 2023 1:01 PMTo: database-rider/database-riderCc: HongHanh9527; MentionSubject: Re: [database-rider/database-rider] Make rider-core compatible with jakarta persistence (Issue #561) I am trying to use Rider-CDI icw jakarta and Quarkus 3.0. However, I ran into the following problem when including:[INFO] -------------------------------------------------------------[ERROR] COMPILATION ERROR : [INFO] -------------------------------------------------------------[ERROR] /C:/Users/derksenjpam/Development/source/uitgifteloket/uitgifteloket-v2/app-portal/src/test/java/nl/bro/microservices/dlp/resources/CptGdwDataSet.java:[35,13] cannot access javax.persistence.metamodel.Attribute  class file for javax.persistence.metamodel.Attribute not found[INFO] 1 error[INFO] -------------------------------------------------------------This is my maven dependency:        <dependency>            <groupId>com.github.database-rider</groupId>            <artifactId>rider-cdi</artifactId>            <version>1.38.1</version>            <scope>test</scope>            <classifier>jakarta</classifier>            <exclusions>                <exclusion>                    <artifactId>stax-api</artifactId>                    <groupId>stax</groupId>                </exclusion>            </exclusions>        </dependency> and the offending test data classimport com.github.database.rider.core.api.dataset.DataSetProvider;import com.github.database.rider.core.dataset.builder.DataSetBuilder;import org.dbunit.dataset.IDataSet;import org.locationtech.jts.geom.Coordinate;import org.locationtech.jts.geom.Geometry;import org.locationtech.jts.geom.GeometryFactory; public class CptGdwDataSet implements DataSetProvider {     // CHECKSTYLE:OFF     GeometryFactory geometryFactory = new GeometryFactory();    // CHECKSTYLE:ON     @Override    public IDataSet provide() {         DataSetBuilder builder = new DataSetBuilder();        return builder            .table( "GDW_LKS_CPT_RD" )            .row()            .column( "OBJECT_ID", "12345" )            .column( "BRO_ID", "CPT000000000001" )            .column( "DELIVERY_ACCOUNTABLE_PARTY", "11112222" )            .column( "GEOMETRY", createRdPoint() )            .table( "LKS_BRO_ORGANISATION" )            .row()            .column( "COC", "11112222" )            .column( "COC_NAME", "TNO" )            .build();    }     private Geometry createRdPoint() {        Coordinate coordinate = new Coordinate();        coordinate.x = 155000.543;        coordinate.y = 463000.220;        Geometry point = geometryFactory.createPoint( coordinate );        point.setSRID( 28992 );        return point;    }}Is this related to this issue?Next (and I should probably write a separate feature request), hibernate 6 includes spatial queries. I'm testing with H2 DB as a light-weight (unit) test DB (Oracle in production).This is why I use a java class as test set iso an yaml file. I reckon there's no support yet for spatial datatypes in the H2 set, or do I miss something?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by rmpestano** [comment]
Hi @sjaakd , can you try with latest snapshot?

```
 <dependency>
          <groupId>com.github.database-rider</groupId>
          <artifactId>rider-core</artifactId>
          <version>1.39.1-SNAPSHOT</version>
         <classifier>jakarta</classifier>
</dependency>

<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>

```

**Comment by sjaakd** [comment]
@rmpestano .. that looks better.. thanks 👍 got different issues now, but the compilation error is gone.

**Comment by sjaakd** [comment]
hold on.. I just realized my idea lost its project structure and was not recognizing tests.

**Comment by rmpestano** [comment]
Guys, I've just released DBRider `1.40.0` which should fix this issue. Please reopen if you find any issues with the jakarta classifier

**Comment by rmpestano** [comment]
Hey @sjaakd, let's open another issue regarding the geometry column. I'm not sure if its a dbrider problem

**Comment by sjaakd** [comment]
> Hey @sjaakd, let's open another issue regarding the geometry column. I'm not sure if its a dbrider problem

Hi @rmpestano .. first and foremost, thanks for the quick fix. I'll agree. I'm not sure whether its indeed a dbrider problem. I'll try to investigate further before I open an issue. However, this fix already helps me a lot. 

 I must honestly say, what happens in the different layers: DBrider, DBUnit, JPA and the H2 driver is a bit of a mystery for me yet (usually I'm only a user). I'll get back on that.

**Comment by mkwapisz** [comment]
rider-junit5 is still dependent to rider-core. There is no jakarta classifier for this lib.

**Comment by rmpestano** [comment]
Hi @mkwapisz, I've just created #565 to handle that

**Comment by sjaakd** [comment]
sorry for responding to a closed issue.. but did something happen? I tried 1.41.0

````xml
    <dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-cdi</artifactId>
            <version>${rider-cdi.version}</version>
            <classifier>jakarta</classifier>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-core</artifactId>
            <version>${rider-cdi.version}</version>
            <classifier>jakarta</classifier>
            <scope>test</scope>
        </dependency>
```
leading to:
`  class file for javax.persistence.metamodel.Attribute not found`

**Comment by NotSoOldNick** [comment]
Hi,

Since finding out about the apparent lack of progress of DBUnit, I found this framework and was hopeful for it to become a suitable replacement, so regardless of the outcome, kudos for the amazing effort so far!
That said, I found this issue and [its related one](https://github.com/database-rider/database-rider/issues/496) highlighting clashes between jakarta and javax dependencies.

I have been trying, and failing, to set up DBRider-based JUnit5 tests for a SpringBoot app based on SpringBoot 3.2.2 / Hibernate 6.4.1 / Jupiter 5.10.1. Needless to say all this stuff is now heavily anchored in the jakarta world, and no longer javax.

My DBRider dependencies are:

```
        <dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-core</artifactId>
            <version>1.41.0</version>
            <classifier>jakarta</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-junit5</artifactId>
            <classifier>jakarta</classifier>
            <version>1.41.0</version>
            <scope>test</scope>
        </dependency>
```

I followed the [getting-started guidelines](https://database-rider.github.io/getting-started/), but when loading the test, it gets stuck with:

```
ERROR com.github.database.rider.junit5.util.EntityManagerProvider -- Could not initialize persistence unit xyz
javax.persistence.PersistenceException: No Persistence provider for EntityManager named xyz
```

From looking a bit closer at the code the `com.github.database.rider.junit5.util.EntityManagerProvider` class seems to be attempting to initialise the persistence stack from the **javax**.persistence api. And in my `persistence.xml` file, my provider is set as 

```
<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
```

which implements `jakarta.persistence.spi.PersistenceProvider`, not the javax equivalent. The `org.hibernate.ejb.HibernatePersistenceProvider` (which implements the **javax** flavour of `PersistenceProvider`) provided as example in the getting-started guide is no longer available in later versions of hibernate. 

So, while I'm not 100% certain, I strongly suspect that not finding a suitable persistence provider is due to the reliance on javax and not jakarta. I would have thought the `rider-junit5` library with the jakarta classifier would have been converted to support jakarta, but maybe my assumption is incorrect? Or maybe it's on the cards for a future release? Not discarding of course the obvious possibility I'm looking at this completely the wrong way, so I'd be more than happy to be told so, it would make my life easier :)

Thanks !

**Comment by rmpestano** [comment]
Hi @NotSoOldNick, have you tried `1.41.1`, we've released it this week but I didn't have time to update the readme and release notes, please let me know

**Comment by NotSoOldNick** [comment]
Hi @rmpestano ,

Apologies for the delayed reply, I had to focus on other issues in the meantime.
I tried the `1.14.1` stack with `jakarta` classifier, and lo and behold, my tests all started working magically !! I can now see how much neater DBRider is compared to DBUnit.
Thank you so much for the super quick turnaround, much appreciated. Awesome work!
Best regards

**Comment by rmpestano** [comment]
That's good to know, thanks for your reply!
