### ISSUE TITLE
Unable to use Prolog assertions in conjunction with hibernate.

### ISSUE THREAD

**Issue by abigailCortis** [database-rider/database-rider#563]
I am currently trying to perform some integration testing on our spring-boot application which uses spring's JPA as well as hibernate and would like to use Database Rider's Prolog assertions. I am however encountering an issue with ANTLR as there is a conflict between the ANTLR versions in use as Database Rider requires ANTLR version 4.9.2 which hibernate requires version 4.10.1. Do you have any suggestion on a possible solution for this problem please? 

![image](https://github.com/database-rider/database-rider/assets/55800256/05758296-0142-405b-9c9d-e292a80a18bf)

**Comment by rmpestano** [comment]
Hey @abigailCortis, I hope [your PR](https://github.com/database-rider/database-rider/pull/564/files) fixes this issue. Once the master build passes, can you try with `1.39.1-SNAPSHOT`?

**Comment by abigailCortis** [comment]
Hi @rmpestano, looks like it's working. Thanks.

**Comment by rmpestano** [comment]
The fix is available in the just released `1.40.0`
