### ISSUE TITLE
Extract base class MapDataSet from JSONDataSet, to simplify integration with other test frameworks

### ISSUE THREAD

**Issue by beskow** [database-rider/database-rider#569]
RiderDSL provides an excellent mechanism for incorporating DbRider/DbUnit in other test frameworks and execution environments (such as e.g the Karate test framework). In such scenarios, DataSets might be created separately by the external test framework, and provided to RiderDSL for creation or validation.

DataSets based on java.util.Map provides a solid ground for such interoperability. The current JSONDataSet implementation in DbRider uses the java.util.Map output of the Jackson JSON parser to construct the DbUnit ITables. By extracting the java.util.Map based implementation into a separate Base class (which JSONDataSet would then extend) greatly simplifies integration with external frameworks.

I successfully use DbRider together with the Karate framework, which provides a really flexible and powerful combination.
I'll submit a pull request for this refactoring.

**Comment by beskow** [comment]
KarateDSL and DBRider works really nice in tandem, and allows for highly readable, hybrid tests. In the example below, the karate `Table` syntax is used for a `cleanInsert` opereration in the Background section (equivalent to `@BeforeEach` in JUnit5), wheres a JSON object used to describe the payload for a Rest POST call is reused in the `Contains` verification. The native table representation in Karate is the same as in `MapDataSet`, making the integration really simple and elegant.

```
  Background:
    * def product_db = karate.callSingle('classpath:/util/dbrider/databaseAccess.js', dataSource);
    * table initial
    |id | name        | sku    |
    |101|'Product 101'|'sku101'|
    |102|'Product 102'|'sku102'|
    * product_db.cleanInsert({"product": initial});

  Scenario: create product
    * def newProduct = {"name": "a new product", "sku": "new"}
    Given path '/products/'
    And request newProduct
    When method post
    Then status 201
    And match response contains newProduct
    And product_db.verifyContains({"product": [newProduct] })
```

**Comment by rmpestano** [comment]
Thank you @beskow
