### ISSUE TITLE
how to specify primary keys (combination of columns) while performing REFRESH

### ISSUE THREAD

**Issue by achyutha526** [database-rider/database-rider#57]
We have a table where we don't have the primary key. How can I configure DBRider the columns treated as Primary key while performing REFRESH operation?

**Comment by rmpestano** [comment]
Hi @achyutha526,

what's the error are you getting? any example where we can reproduce the issue?

t

**Comment by achyutha526** [comment]
Hi @rmpestano ,

I am not receiving any error. I have a table where there is not primary key configured. While inserting records database rider is just inserting records without issues. I don't want to populate duplicate records, I want to make sure the ID and Create_Date columns should be unique on the table. Is there any way I can guide the database rider to check for uniqueness of the records?

**Comment by rmpestano** [comment]
Hi @achyutha526,

can you try this:

```
ID: groovy: UUID.randomUUID().toString()
ID2: js:Math.floor(Math.random() * (10000))
DATE: "groovy:new Date()" 
```

The above dataset is using  is [scriptable dataset](https://database-rider.github.io/database-rider/1.2.5/documentation.html#Dynamic-data-using-scritable-datasets).

For groovy scripts you'll need grovy-all on test classpath:

```
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.4.6</version>
    <scope>test</scope>
</dependency>
``` 
I hope it helps
