### ISSUE TITLE
Could not find script engine with name http that the column's value is http URL

### ISSUE THREAD

**Issue by linux-china** [database-rider/database-rider#58]
I have a dataset as following: 
```
<adminlet_images id="1" app_name="spring-boot-demo" description="spring boot demo"
                            image_location="http://gitlab.company.com/xxx/adminlet-simple-demo" />
```
image location is a HTTP URL. When I run test, and I got the following exception: 
```
Caused by: java.lang.RuntimeException: Could not find script engine with name http in classpath
```
Should I do some escape for http url value?

**Comment by rmpestano** [comment]
Hi @linux-china,

this [was fixed](https://github.com/database-rider/database-rider/issues/53) on latest version 1.2.5, can you try with that version?

**Comment by linux-china** [comment]
it's good with 1.2.5, and I will close it.
