### ISSUE TITLE
Possibly add a warning in CDI component documentation for users of CdiTestRunner?

### ISSUE THREAD

**Issue by garyhodgson** [database-rider/database-rider#59]
Hi,

It may be worth mentioning in the documentation for the CDI component that when it is used in conjunction with Deltaspike CdiTestRunner the settings necessary to use DBUnitInterceptorImpl (i.e. deltaspike.testcontrol.use_test_class_as_cdi_bean=true) means that junit @Before functionality will not work as expected.  

There is a brief discussion about it on the deltaspike user mailing list here: https://lists.apache.org/thread.html/60ae2ade9ff8c5588a53a138b64c94e505455185358c21f663a5fd33@%3Cusers.deltaspike.apache.org%3E

Because the use_test_class_as_cdi_bean flag is an explicitly undocumented feature it may cause headaches for the unwary (as it did for me).

Regards

**Comment by rmpestano** [comment]
Hi @garyhodgson,

Just added the warn on docs, thanks for reporting.
