### ISSUE TITLE
Feature request: wildcard/regex support for `skipCleaningFor` in @DataSet

### ISSUE THREAD

**Issue by coiouhkc** [database-rider/database-rider#597]
Hi @rmpestano 
in my current project we found a use case which could profit from wildcard/regex support in `skipCleaningFor` - when using `cleanBefore=cleanAfter=true`, skip cleaning the Quartz (QRTZ_*) tables.
If you would agree to accept the feature, i'm ready to work on a PR.

**Comment by coiouhkc** [comment]
PR: https://github.com/database-rider/database-rider/pull/598

**Comment by rmpestano** [comment]
Hey @coiouhkc, thanks for the contribution. I'll try to get 1.43.0 released with your fix over this weekend.
