### ISSUE TITLE
DataSet names as array in @DataSet

### ISSUE THREAD

**Issue by rmpestano** [database-rider/database-rider#6]
Currently we declare multiple datasets using comma separated names:

```
@DataSet("dataset1.yml, dataset2.yml, datasetN.json")
```

But its more clear to use a list os names:

```
@DataSet({"dataset1.yml","dataset2.yml"})
```

Note that the current approach (comma separated) must also work in the new implementation.

**Comment by gilbertoca** [comment]
@rmpestano the yaml file is atomic? Say we have contrato.yml, cliente.yml and linha_credito.yml. Each one has its own test with correspondent yml, but ContratoTest needs data from others: Do I have to repeat the content of the other in contrato.yml?

**Comment by rmpestano** [comment]
Hi @gilbertoca,

I don't know if I got it but if the data is common among these tests you can reuse  contrato.yml, cliente.yml and linha_credito.yml but if they differ then you'll have to create different datasets.

For example, I have a dataset called cyties.yml which is the same for all tests then I just declare it along side with the test specific dataset.

```
@DataSet({"cities.yml","my_test_specific_dataset.yml"})
```

**Comment by rmpestano** [comment]
Also note that DBUnit will try to resolve the dependencies of these datasets looking at table constraints (look at [useSequencyFilter here](https://github.com/database-rider/database-rider#configuration)).

Sequence filter will work on most of the case but in the cases it can't infer these dependencies (e.g circular dependencies) then you will have to declare the hole dataset in a single file in the right order (dbunit uses declaration order to insert and inverse order for removal). You can also use tableOrdering to solve the dependent datasets issue.
