### ISSUE TITLE
Enable JSON Schema support

### ISSUE THREAD

**Issue by Micky002** [database-rider/database-rider#600]
Currently it is not possibly to specify a json-schema in a data file which is references via `@DataSet` annotation.

If i use the following data json i get a `ClassCastException` (`java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List`) because the `$schema` property is not a list.

```json
{
  "$schema": "https://www.dummy.com/schema.json"
  "tableName": [
    {
      "colum1": "data-value"
    }
  ]
}
```

Is there any possibility to exclude the `$schema` property from parsing. I have not found any in the source code, but maybe i have missed something.

Issue occurs in version **1.42.0**

**Comment by rmpestano** [comment]
Hey @Micky002, we should be able to exclude unknown properties while parsing the json dataset but I'm not sure the parsing happens on dbrider or dbunit side, do you have a stacktrace and a sample project reproducing the issue? Or even better, if you fork this project and create a (failing) test case where the issue happens. Thanks for the feedback

**Comment by Micky002** [comment]
I have created a very basic unit test and a potential fix for the issue. Maybe there should be some configuration possibilities to enable or disable the `$schema` ignore mechanism.

**Comment by rmpestano** [comment]
Thanks for the contribution @Micky002!
