### ISSUE TITLE
cleanBefore does not work with multiple schemas on postrgres

### ISSUE THREAD

**Issue by deadmeat333** [database-rider/database-rider#63]
Hi, guys!

I thank you for this tool. I use 1.2.5 version in my project and I faced with such a problem:
when using multiple schemas on postgresql 9.4 and higher with full qualified table names and cleanBefore = true, errors occurs and tables are not cleaned. I looked at the sources and found this code `schemaName = result.getString("TABLE_SCHEMA");` in `DataSetExecutorImpl.resolveSchema(ResultSet result)`, but postgresql driver name this column as TABLE_SCHEM, that's why errors occurs, database-rider can not resolve schemas and find tables by their qualified names. May be you can fix it something like this: `getRiderDataSource().getDBType() == POSTGRESQL ? "TABLE_SCHEM" : "TABLE_SCHEMA"` or more attractive way.

Also, when I try to find a workaround for this, I faced with problem, there is no way to pass a custom DataSetExecutor to DBUnitRule, and I even can't extend and override DataSetExecutorImpl.resolveSchema without copying entire class, because most of all methods are private. May be you should give some extension points?

**Comment by rmpestano** [comment]
Hi there, thank you for the tips, I can merge If you want to contribute!

About the public methods we can add them to the DatasetExecutor interface.

About passing a custom executor, can you fill another issue? I'll have a look.
