### ISSUE TITLE
ExpectedDataset

### ISSUE THREAD

**Issue by codeweb** [database-rider/database-rider#67]
```
@Test
@DataSet(cleanBefore=true)
@ExpectedDataSet(value = "expectedFoo.csv")
public void genericTest() throws Exception {
```

I'd know how ExpectedDataSet find the table name in this example. I read csv filename can be a custom name.
Table-ordering obviously cannot be the solution because I could have two tables having the same columns.
Thanks

**Comment by rmpestano** [comment]
Hi @codeweb,

have tou seen the [csv dataset examples here](https://github.com/database-rider/database-rider/tree/master/rider-core/src/test/resources/datasets/csv)  and the [test here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/DatabaseRiderIt.java#L176)? 

I hope it helps.

**Comment by rmpestano** [comment]
The table name is the filename

**Comment by rmpestano** [comment]
Does it work when you use the filename as table name?

**Comment by codeweb** [comment]
I edited filename and i edited also a value in csv to get an error but the test is ok.
Does ExpectedDataset work comparing entire table/columns/rows between database and csv?

**Comment by codeweb** [comment]
Maybe the problem is `@ExpectedDataSet(value = DATASET_FOLDER + "/" + EXPECTED_FILENAME)`
How can i specify the directory in a different way?

**Comment by codeweb** [comment]
Or CompositeDataSet if dataSets.length = 1
```
public CompositeDataSet(IDataSet[] dataSets, boolean combine, boolean caseSensitiveTableNames)
            throws DataSetException
    {
        super(caseSensitiveTableNames);
        
        // Check for duplicates using the OrderedTableNameMap as helper
        OrderedTableNameMap orderedTableMap = super.createTableNameMap();
        for (int i = 0; i < dataSets.length; i++)
        {
            IDataSet dataSet = dataSets[i];
            ITableIterator iterator = dataSet.iterator();
            while(iterator.next())
            {
                addTable(iterator.getTable(), orderedTableMap, combine);
            }
        }

        _tables = (ITable[]) orderedTableMap.orderedValues().toArray(new ITable[0]);
    }
```

**Comment by rmpestano** [comment]
Hi, just added an [example here](https://github.com/database-rider/database-rider/blob/b4d58de2c3149b3e03dfeee4a59901d10d107a34/rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetIt.java#L153)
