### ISSUE TITLE
problem with SeedStrategy.CLEAN_INSERT

### ISSUE THREAD

**Issue by codeweb** [database-rider/database-rider#69]
I tried the following code
```
@Test
@DataSet(strategy = SeedStrategy.CLEAN_INSERT, transactional = true)
@ExpectedDataSet(value = "foo.csv", ignoreCols = "id")
public void runGenericTest() throws Exception {
  // read every record of originalFileToPopulateTable and sums it (invoice and increment) 
}
```
table-ordering.txt:
`myTable`

myTable.csv
id, year, invoice, increment
"2", "2017", "10.0", "2"

originalFileToPopulateTable.csv
year, price
"2017", "0.5"
"2017", "0.5"

If i run test twice, i will get 20.0 and not 10!
The record in myTable is not deleted after every test (or i did a mistake understanding SeedStrategy)

**Comment by rmpestano** [comment]
Clean is done before test execution on dataset tables

**Comment by codeweb** [comment]
**myTable**
First test results:
id, year, invoice, increment
"2", "2017", "10.0", "2"
clean
second test results:
id, year, invoice, increment
"2", "2017", "10.0", "2"

I got:
First test results:
id, year, invoice, increment
"2", "2017", "10.0", "4"
second test results:
id, year, invoice, increment
"2", "2017", "20.0", "4"

**Comment by codeweb** [comment]
Dataset tables are not specified.

**myTable**

First test results:

```
id, year, invoice, increment
"2", "2017", "10.0", "2"
```

clean

expected second test results:

```
id, year, invoice, increment
"2", "2017", "10.0", "2"
```

I got:

First test results (ok):

```
id, year, invoice, increment
"2", "2017", "10.0", "2"
```

Real second test results:

```
id, year, invoice, increment
"2", "2017", "20.0", "4"
```

**Comment by rmpestano** [comment]
"Dataset tables are not specified." Just declare them, even If empty, see example here: https://github.com/database-rider/database-rider/blob/71ca3783a0dae20056fd68802651390b11dce618/rider-core/src/test/java/com/github/database/rider/core/EmptyDataSetIt.java#L47
