### ISSUE TITLE
Yaml exports nulls as empty strings

### ISSUE THREAD

**Issue by agogala** [database-rider/database-rider#7]
Exporting datasets in YAML format writes null values as empty strings. 

Error seems to be in YMLWriter.java in method `row()`:

Suggested change:

```java
                if (values[i] != null) {
                    if(!isNumber){
                        out.write("\"");
                    }
                    out.write(values[i].toString());
                    if(!isNumber){
                        out.write("\"");
                    }
                }
```

**Comment by rmpestano** [comment]
Hi @agogala,

just fixed it. If you want to test, it should be available in [snapshot](https://github.com/database-rider/database-rider#snapshots) soon. Thank you for the heads up.
