### ISSUE TITLE
Allow @DataSet annotation to be used as meta-annotation

### ISSUE THREAD

**Issue by njuro** [database-rider/database-rider#79]
Hello,

I'm using `rider-spring` and I found myself using the same datasets for quite a few tests, so I wanted to make a custom composed annotation, something like this:

```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@TestExecutionListeners(value = DBRiderTestExecutionListener.class, mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)
@DataSet(value = "/datasets/test.yml", useSequenceFiltering = false, disableConstraints = true, transactional = true)
public @interface UseMockDatabase {
}
```
But it does not work. After investigating a bit, I found the probable cause is in the method [SpringRiderTestContext#getClassAnnotation](https://github.com/database-rider/database-rider/blob/master/rider-spring/src/main/java/com/github/database/rider/spring/SpringRiderTestContext.java#L52), as this method only checks annotation presence on base class. I'm thinking it could be fixed by using Spring's [AnnotationUtils#findAnnotation](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AnnotationUtils.html#findAnnotation-java.lang.Class-java.lang.Class-) which traverses also parent classes and meta-annotations, however I'm not sure if that is enough. If this is a minor change for you and you got time, I'd be glad if it will be implemented, otherwise I will try to make a Pull Request sometimes when I have some free time.

NOTE: For now, the workaround is to make abstract parent class with such annotations (that will work, since they are `@Inherited`, but it's not very convenient, as often I need to extend another class and annotations are not inherited from interfaces.

**Comment by njuro** [comment]
Update: I created PR which solves this issue for `rider-core`. Fix for `rider-junit5` will follow in few days when I return from vacation, unless somebody else do it until then. As for `rider-core`, it may be possible, but since it doesn't have the AnnotationUtils methods, like Spring/Junit5 have, it may be needed to copy some boilerplate code from one of them.

**Comment by rmpestano** [comment]
Hi @njuro, thank you very much, I'll review ASAP!

**Comment by rmpestano** [comment]
>  As for rider-core, it may be possible, but since it doesn't have the AnnotationUtils methods, like Spring/Junit5 have, it may be needed to copy some boilerplate code from one of them.


It would be very interesting to have it on rider-core, we may incorporate/copy AnnotationUtils to core to not depend on Spring. Created issue #80.
