### ISSUE TITLE
Parsing table names from queries

### ISSUE THREAD

**Issue by agogala** [database-rider/database-rider#8]
Hi Rafael,

thanks for quickly resolving issue with nulls in YAML. I've encountered another problem with using queries in export. My queries are of form:

```sql
select * from TABLE1 where SOME_ID in (select SOME_ID from TABLE2 where ....)
```

This way I can export single record from table `TABLE2` together with all dependent tables.

Regular expression (`TABLE_MATCH_PATTERN` in `DataSetExporter.java`) that is used in figuring out table names in queries returns table name `TABLE2` instead of `TABLE1`. Quick fix would be to make first part of regular expression non greedy as in:

```java
".*?\\s+from\\s+(\\w+(\\.\\w+)?).*"
```

Would that be OK?

Best regards,

Andrej

P.S. I've also noticed that there is an r missing in folder/class name `.../database/rider/core/api/expoter/˙.

**Comment by rmpestano** [comment]
Hi Andrej, I'll have a look tomorrow, meanwhile If you want to provided a PR it will be very welcomed!

 Thank you so much for trying and pushing this project forward!

**Comment by rmpestano** [comment]
Hi again,

I've just fixed it but could not get the regex to work for subselects so I'm extracting the first select and then using the regex to parse the table name.
