### ISSUE TITLE
change log file

### ISSUE THREAD

**Issue by searhiy** [database-rider/database-rider#9]
Can you create the CHANGELOG.adoc file? You release RC2 and I can't find what was the changes?
i.e. https://github.com/asciidoctor/asciidoctor/blob/master/CHANGELOG.adoc

By the way, why you decided to migrate to this new repo? Just renamed the project or smth else?

Thank you

**Comment by rmpestano** [comment]
Hi @searhiy,

release notes can be found on each release: https://github.com/database-rider/database-rider/releases/tag/1.0.0-RC2

we can create a CHANGELOG based on all releases (also from dbunit-rules) if you think its necessary.


I decided to port the project to an organization so its not tied to my name but to a comunity. Also the project started with a single **JUnit Rule** hence the former name but now the project has various modules. Hope that answers your qustion ;)

**Comment by searhiy** [comment]
Hi @rmpestano,

It's just useful to have CHANGELOG file. 
And thank you for release notes!

**Comment by rmpestano** [comment]
I'll leave it opened until we create the changelog file, ok?

It will also be based on [dbunit-rules releases](https://github.com/rmpestano/dbunit-rules/releases?after=0.10.0) so we can have all releases history.

Thank you.

**Comment by searhiy** [comment]
That would be perfect!
