### ISSUE TITLE
Add ability to merge datasets

### ISSUE THREAD

**Issue by getarrenspieler** [database-rider/database-rider#92]
Case:

1. Meta dataset is defined and includes several dataset files are common for all tests.
2. Any test is needed its specific dataset in addition to common data in meta dataset.

DataSet in test is override metadataset.

I think it's a good idea to make some dataset mode flags to manage included datasets, for example:

```java
/*Meta dataset with common data*/
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@DataSet(value = {"SomeData1.xml", "SomeData2.xml", "SomeData3.xml"},
        strategy = SeedStrategy.CLEAN_INSERT)
public @interface MetaDataset {
}

@MetaDataset
public class SomeDaoTest {
  ...
  @Test
  @DataSet(value = "before-update.xml", mode=DatasetMergeMode .DATASET)
  @ExpectedDataSet(value = "after-update.xml")
  public void updateTest() {
      ...
  }

  @Test
  @DataSet(value = "before-delete.xml", mode=DatasetMergeMode .DATASET)
  @ExpectedDataSet(value = "after-delete.xml")
  public void deleteTest() {
      ...
  }
}
```

Possible modes can affect all dataset parameters:

```java
class DatasetMergeMode {
   public static final int DATASET = 1;   
   public static final int BEFORE_STATEMENTS= 2;
   public static final int AFTER_STATEMENTS = 4;
  .....
}
```

Because default behavior is "override", only merge is interested.

**Comment by rmpestano** [comment]
Thinking better the merging could also be applied to non metatasets, ex:

```
@DataSet(value = {"SomeData1.xml", "SomeData2.xml", "SomeData3.xml"},
        strategy = SeedStrategy.CLEAN_INSERT)
@DBunit(mergeDataSets=true, mergeDataSetPriority = METHOD) //method annotation will be applied first
public class SomeDaoTest {
  ...
  @Test
  @DataSet(value = "before-update.xml")
  @ExpectedDataSet(value = "after-update.xml")
  public void updateTest() {
      ...
  }

  @Test
  @DataSet(value = "before-delete.xml")
  @ExpectedDataSet(value = "after-delete.xml")
  public void deleteTest() {
      ...
  }
}
```

**mergeDataSetPriority** can be METHOD or CLASS.

WDYT?

**Comment by getarrenspieler** [comment]
Hi,

> 'BEFORE_STATEMENTS' and 'AFTER_STATEMENTS'

```java
/**
   * @return a list of jdbc statements to execute before test
   *
   */
  String[] executeStatementsBefore() default {};

  /**
   * @return a list of jdbc statements to execute after test
   */
  String[] executeStatementsAfter() default {};
```

I mean addition of before/after statements to the statements in metadataset. It's can be applied to other array attributes of `@DataSet`. I thought about separate merge setting for array attributes. May be it not useful, I just supposed that it can take place) For the first time `mergeDataSets=true` will be enough)

About global `@DBUnit` settings like `mergeDataSets=true, mergeDataSetPriority = METHOD` may be is a good idea, but firstly I think it should be implemented on particular (meta)datasets. It can be imlemented with annotations to have ability apply it on class and override global setting (using `@DataSet` as attribute is not excluded yet) (see code below)

> mergeDataSetPriority can be METHOD or CLASS (default value).

I agree)

`mergeDataSetPriority` can be applicable to array atributes only. Attributes like `strategy` will be applied on *override current setting* rule.

```java
@DataSet(value = {1.xml, 2.xml}, strategy = REFRESH)
@interface Meta {}

@Meta
//points to that all datasets in each test will be added to meta dataset for one concrete test
@MergeDataSet 
class TestCase {

@Test
  // total data set should contain 1.xml, 2.xml,  added.xml, because of MergeDataSet (or mergeDataSet = true in @DbUnit setting
  // strategy = REFRESH - from meta
  @DataSet(value = added.xml) 
  void testMerged {
  }

  @Test
  // total data set should contain only distinct.xml, because of local mergeDataSet = false. It's needed because of global setting = true
  // strategy = CLEAN_INSERT - because of it is default behavior of dataset. There no purpose to define priority for that parameter globally, because of it only one: if you want - use global and set nothing, or set local and it should be applied 
  @DataSet(value = distinct.xml, mergeDataSet=false, strategy=CLEAN_INSERT) 
  void testDistinct {
  }
}
```
Totally:

1. `@DbUnit` **mergeDataSet** and **mergeDataSetPriority** attributes - are global
2. Defaults: mergeDataSet = false, mergeDataSetPriority = CLASS
3. They can be overriden in TestCase class level with annotations `@MergeDataSet` and `@MergeDataSetPriority(CLASS/METHOD)` 
or
4. in`@DataSet` with the same attributes (like in `@DbUnit`) to override global or class behavior.
5. Both settings are applied to attributes which can have more than one value (may be restrict this only with datesets itself for now). 
6. Single-valued attributes (like **strategy**) overriden by common rules (as imlemented now)

What do you think?

**Comment by rmpestano** [comment]
> Maybe I'm being too simplistic but my idea is to create (merge) one dataset based on datasets declared on class level (be it metataset or not) and on dataset declared on the test level. So for example if both declare executeStatementsBefore their values will just be merged in one executeStatementsBefore

Another idea would be having two separated datasets (class and method level) and execute them independently, in the case I wouldn't call it `merge datasets` but may also be interesting to have.

**Comment by rmpestano** [comment]
Any thoughts @njuro @TopalSergeym @artemy-osipov @jenskreidler?

**Comment by rmpestano** [comment]
Hi, about the first (original approach) the merge mode is defined by @Dbunit annotation which can be on class or method. If @Dbunit is defined at class AND method  then method level will take place.

In other words if merge mode is defined at class and method, then we'll use the value from @Dbunit defined in method.

**Comment by getarrenspieler** [comment]
Hi,
I understand your point. I'm talking about that merge mode not affect stratagy and other single value attributes. There no need to define on class level to "get strategy from methods". It will be more clear, if strategy defined in method dataset it will be applied.

**Comment by rmpestano** [comment]
> It will be more clear, if strategy defined in method dataset it will be applied.
Agreed!

The main problem is that for array attributes it will have a different behavior, it may confuse users, but I think we can stick with your suggestion and **merge only the array attributes of @DataSet**.

**Comment by artemy-osipov** [comment]
Hi, 
I think merging datasets on annotations, classes and methods is good idea in some cases, but configuring priorities and modes are overcomplication. We can start with choosing good default merging behaviour.

> Maybe I'm being too simplistic but my idea is to create (merge) one dataset based on datasets declared on class level (be it metataset or not) and on dataset declared on the test level. So for example if both declare executeStatementsBefore their values will just be merged in one executeStatementsBefore

Agreed! For my opinion datasets on annotation must be specified for common setup like filling reference data, while datasets on methods are more test specific. 
What do you think about such ordering?
- executeStatementsBefore on annotation level
- executeStatementsBefore on class level
- executeStatementsBefore on method level
- executeScriptsBefore on annotation level
- executeScriptsBefore on class level
- executeScriptsBefore on method level
- datasets on annotation level
- datasets on class level
- datasets on method level
- executeScriptsAfter on method level
- executeScriptsAfter on class level
- executeScriptsAfter on annotation level
- executeStatementsAfter on method level
- executeStatementsAfter on class level
- executeStatementsAfter on annotation level

**Comment by getarrenspieler** [comment]
Hi!

I agree with @artemy-osipov. And setting in `@DbUnit` to enable/disable merging, like @rmpestano suggested. Default is `false` for backward-compatibility.

**Comment by artemy-osipov** [comment]
I don't really think we need toggle for merging. I agree that this may break backward-compatibility, but after implementing this feature current behaviour become deprecated

**Comment by rmpestano** [comment]
I think one (boolean) attribute on dbunit-config.yml or @Dbunit wouldn't hurt with the benefit of compatibility. 

In a future release e.g v1.3.x we could turn the feature ON by default.

WDYT?

**Comment by artemy-osipov** [comment]
I'm afraid that adding toggle to the public api will be difficult to remove it later. But I proceed from the assumption that merging flag is introduced only for transition period and merging-on mode is preferred.

**Comment by rmpestano** [comment]
My only concern is to make it easier to users to upgrade dbrider version although I think today users até using test level OR method level dataset annotation (on the same test) so they wouldn't be affedted by the merge anyway. 

So thinking better we don't need the flag after all. 

The next version will be 1.3.0.

Everyone agree? Anyone wants to gets the hands dirty and try to implement it?

**Comment by rmpestano** [comment]
I think if we're going to introduce any breaking changes we would need to release Rider 2.0. 

For now I would go with the flag in dbunit-config to enable the merge and with release v1.3.0 but I can change my mind (easily) as you saw above ;)

**Comment by rmpestano** [comment]
I've commited initial impl on my [local branch here](https://github.com/rmpestano/database-rider/commit/19a070ce0386cbc158f8b9538135bd10ddd63d3d). 

I didn't opened the pull request because it implements the merge for rider-core only, still need to add for other modules and add more tests.

Any feedback is really welcomed.

**Comment by rmpestano** [comment]
To make it easy to review here's the full diff: https://github.com/database-rider/database-rider/compare/master...rmpestano:master

My idea is to merge the PR and release v1.3.0 in next days.

**Comment by rmpestano** [comment]
Thank you @artemy-osipov for reviewing it and everyone involved!
